Ensure room is actually in space hierarchy when resolving its latest version
matrix-org/matrix-react-sdk pull request #10010
Opened 2023-01-27 14:00 UTC by Johennes

This fixes one of the issues from vector-im/element-web#24329

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-01-27 15:11 UTC, Johennes commented
Remaining static analysis errors are in a file I didn't touch. 🤷‍♂️

2023-01-27 15:35 UTC, florianduros requested changes
Seems good! If unit tests can be added to cover theses changes, it will be great :)

Thanks!

2023-01-27 19:21 UTC, Johennes commented
You passed the attentive reviewer test. 😅

Have added tests, too, now. 🙂

2023-01-30 07:34 UTC, Johennes commented
Hm, interestingly Sonarcloud _only now_ complains about the coverage being slightly below 80%. 🤔

2023-02-01 19:14 UTC, Johennes commented
@florianduros coverage is above 80% now. Would appreciate feedback on the quality of tests as I'm not sure if these are very great.

2023-02-02 09:29 UTC, florianduros approved these changes
Looks good! Imo, a small improvement can be made in the test :)

2023-02-02 09:29 UTC, florianduros commented on test/components/structures/SpaceHierarchy-test.tsx
> +        beforeEach(() => {
If we are not mutating the mock created in the `beforeEach`, we can created them in the `describe` scope.

2023-02-02 09:29 UTC, florianduros commented on test/components/structures/SpaceHierarchy-test.tsx
> +
If we are not mutating the mock created in the beforeEach, we can created them in the describe scope.

2023-02-02 20:00 UTC, merged