SatyarajRana:issue24358 solved
matrix-org/matrix-react-sdk pull request #10025
Opened 2023-01-30 18:16 UTC by SatyarajRana

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Users can now insert the markdown elements for formatting text (e.g. __ for italics, **** for bold) whenever the hotkeys are pressed, not just when the cursor is on a word, but also when on a blank space, so they can be activated before typing a word.

2023-01-31 08:53 UTC, weeman1337 commented
Thank you for your contribution @SatyarajRana . You should add something like `closes ISSUE_URL` to the description, so that GitHub knows what issue you are targeting. Mentioning the issue umber in the title is not enough. And can you change your title to something more meaningful?

2023-01-31 11:26 UTC, dbkr requested changes
Linking to the bug: https://github.com/vector-im/element-web/issues/24358

Note that this change will need a product decision, and this is an enhancement to a legacy feature. Also, this will need tests.

2023-02-05 06:49 UTC, SatyarajRana commented
@dbkr  any update?

2023-02-06 09:25 UTC, t3chguy commented
> Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-02-04T18%3A37%3A42Z))

Missing sign off, checking the box is not enough, see the linked document.

2023-03-31 17:21 UTC, closed without merging