Fix call buttons on the header being compressed due to long room name
matrix-org/matrix-react-sdk pull request #10155
Opened 2023-02-13 19:20 UTC by luixxiul

This PR adds the flex declaration to `mx_RoomHeader_button` to prevent the buttons from being compressed due to a long room name, copying the whole declarations from `mx_RightPanel_headerButton` for reference.

Before:
![Screenshot from 2023-02-14 04-15-17](https://user-images.githubusercontent.com/3362943/218552705-2db040b4-ad6b-44d6-a889-c644a88052b3.png)

After:
![Screenshot from 2023-02-14 04-15-07](https://user-images.githubusercontent.com/3362943/218552565-da098835-57b5-439a-b474-c782b3beb2e4.png)

Note `mx_RightPanel_headerButton` should be merged with `mx_RoomHeader_button` eventually (see the `fixme` comment on `_RightPanel.pcss`).

type: defect

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-02-14 10:57 UTC, richvdh reviewed
@luixxiul thanks for the contribution!

Rather than copying all the CSS definitions between `mx_RightPanel_headerButton` and `mx_RoomHeader_button`, maybe we should just have a single class `mx_HeaderButton` which is used in both places?  What do you think?

2023-02-14 15:39 UTC, luixxiul commented
It seems that creating `mx_HeaderButton` is likely to require refactoring of the block below (which might not be limited to it, as current CSS selector names do not tell us the structure of the elements):

https://github.com/matrix-org/matrix-react-sdk/blob/eb271891578bd0ee8fce1b5d75accaaec42eb42e/res/css/structures/_RightPanel.pcss#L41-L202

Though there is a class `mx_HeaderButtons`, it is used for a div wrapper of buttons, whose class is `mx_RightPanel_headerButton`, not `mx_RoomHeader_button`.

Since refactoring the whole block is too much for this PR, I would leave it for another PR dedicated to that task.

2023-02-14 16:08 UTC, richvdh commented
> It seems that creating ` is likely to require refactoring of the block below

How so?

I am literally thinking that you would replace all references in the code to `mx_RightPanel_headerButton` and `mx_RoomHeader_button` with `mx_HeaderButton`.   None of the other classes in the CSS you link to would be affected.

2023-02-14 16:26 UTC, luixxiul commented
Sorry, my explanation was not correct.

What I'm worried is that renaming `mx_RightPanel_headerButton` to `mx_HeaderButton` for example requires renaming other selectors as well, otherwise it would break the naming status like below:

````
.mx_RightPanel_headerButtonGroup { 
    ...
} 

.mx_HeaderButton { 
    ...
} 
  
.mx_RightPanel_threadsButton::before {
    ...
}
...
````

It seems to me that `mx_RightPanel_threadsButton::before` etc. should be renamed to `mx_HeaderButton_threadsButton::before` etc, in order to avoid confusion. What do you think?

2023-02-14 16:44 UTC, richvdh commented
I don't think it is necessary to rename `mx_RightPanel_headerButtonGroup` or `mx_RightPanel_threadsButton`.

2023-02-27 18:22 UTC, luixxiul commented
As the risk of occurring a regression is high due to the nature of style codebase discussed like [here](https://github.com/vector-im/element-web/issues/24684), I would not recommend to proceed with changing a class name before setting up a screenshot test. I think that currently it is risky to decide where the merged style rules are placed, without having the test on Percy.

I guess that after this PR with Percy enabled is merged, a base branch snapshot is created on Percy and regressions which would be caused by changing a name should be able to be detected. Otherwise, another PR for the test should be created, cherry-picking the commit for the test, and merged before this PR.

2023-02-28 12:52 UTC, richvdh approved these changes
I don't particularly agree that the risk of a regression in this case is significant compared to the cost of further propagating this duplicate code, but let's get on and land this rather than arguing about it.

2023-02-28 12:52 UTC, richvdh commented on cypress/e2e/create-room/create-room.spec.ts
> +    it("should create a room with a long room name with horizontal ellipsis", () => {
```suggestion
    it("should create a room with a long room name, which is displayed with ellipsis", () => {
```

2023-02-28 12:52 UTC, richvdh commented on res/css/structures/_RightPanel.pcss
> +/* See: mx_RoomHeader_button */
```suggestion
/* See: mx_RoomHeader_button, of which this is a copy.
 * TODO: factor out a common component to avoid this duplication.
 */
```

2023-02-28 12:53 UTC, richvdh requested changes
minor changes as requested above

2023-03-01 11:17 UTC, richvdh approved these changes

2023-03-01 12:21 UTC, merged

2023-03-01 13:26 UTC, richvdh commented
Thanks for the contribution @luixxiul !