Remove height of hidden DateSeparator on FilePanel
matrix-org/matrix-react-sdk pull request #10185
Opened 2023-02-19 06:15 UTC by luixxiul

This PR removes height of hidden `DateSeparator` on `FilePanel`. The height is created with block margin of Firefox's browser default styles. Note that the default style implicitly creates the height of date separators' `hr` on the main timeline.

|Before|After|
|---------|------|
|![Screenshot from 2023-02-19 14-55-27](https://user-images.githubusercontent.com/3362943/219931768-5c8ff820-4a24-44ac-83bc-09a691d9ed1d.png)|![Screenshot from 2023-02-19 14-57-11](https://user-images.githubusercontent.com/3362943/219931803-615743d0-6c6c-40f1-9f5d-0c8bce147d7b.png)|
|![Screenshot from 2023-02-19 14-56-34](https://user-images.githubusercontent.com/3362943/219931770-7f2ac0ee-56ae-41d0-9970-5cf65ac07a03.png)|![Screenshot from 2023-02-19 14-57-59](https://user-images.githubusercontent.com/3362943/219931781-aef62d26-bc96-4181-848a-bf6fadcd573c.png)|

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-02-20 07:57 UTC, weeman1337 commented
Can you trigger the CI again @luixxiul (for instance just push an empty commit).

2023-02-20 08:39 UTC, luixxiul commented
@weeman1337 Done!

2023-02-20 08:40 UTC, gsouquet requested changes
Could we then investigate removing the date separator altogether?
That indeed sounds a bit more appropriate

2023-02-27 16:29 UTC, luixxiul commented
I am not sure where to check in order to change where separators should be displayed. It would be helpful to give me a hint. Thanks in advance.

2023-03-09 17:47 UTC, closed without merging