Changed empty string to default value
matrix-org/matrix-react-sdk pull request #10206
Opened 2023-02-21 15:18 UTC by hemantmm

Fixes github.com/https://github.com/vector-im/element-web/issues/23458
Updated the logic as suggested please check;
changed the empty string to RoomEvent.name, please guide me if something is not appropriate. Thank you.

               this.state.readMarkerEventId ?? "",  // changed to below line

               this.state.readMarkerEventId ?? RoomEvent.Name,

2023-02-22 14:26 UTC, weeman1337 requested changes
Hey @hemantmm thank you for your contribution.

Please have a look at my review comments.
Since this is a bugfix, can you provide a test case as well?

2023-02-22 14:26 UTC, weeman1337 commented on src/components/structures/TimelinePanel.tsx
> +// @ts-ignore
There should be no `@ts-ignore` in new code.

2023-02-22 14:26 UTC, weeman1337 commented on src/components/structures/TimelinePanel.tsx
> +                    this.state.readMarkerEventId ?? RoomEvent.Name,
I don't think it is correct to use the room event name as fallback here.

2023-07-07 14:25 UTC, t3chguy commented
Closing as abandoned.

2023-07-07 14:25 UTC, closed without merging