Let „new device“ toast start verification when clicking „yes“
matrix-org/matrix-react-sdk pull request #10200
Opened 2023-02-21 10:24 UTC by weeman1337

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-02-22 09:33 UTC, weeman1337 commented
> @weeman1337 can we please separate out the toast layout change into its own PR for design to review

Done

2023-02-22 17:47 UTC, t3chguy requested changes
Looks sane otherwise

2023-02-22 17:47 UTC, t3chguy commented on test/toasts/UnverifiedSessionToast-test.tsx
> +        client.getDevice.mockImplementation(async (deviceId: string) => {
Can we resolve the tsc --strict failure here please

2023-02-22 17:47 UTC, t3chguy commented on test/toasts/UnverifiedSessionToast-test.tsx
> +        client.getStoredDevice.mockImplementation((userId: string, deviceId: string) => {
Can we resolve the tsc --strict failure here please

2023-02-22 17:47 UTC, t3chguy commented on src/utils/device/isDeviceVerified.ts
> +        return crossSigningInfo.checkDeviceTrust(crossSigningInfo, deviceInfo, false, true).isCrossSigningVerified();
Can we resolve the tsc --strict failure here please

2023-02-22 17:47 UTC, t3chguy commented on src/components/views/settings/devices/DeviceMetaData.tsx
> +                    ` (${formatLastActivity(device.last_seen_ts)})`}
Can we please not add tsc --strict errors in new code

2023-02-23 09:05 UTC, t3chguy approved these changes

2023-02-23 09:25 UTC, merged