Dark theme: resolving doubles, conflicts and prepared for next fixes
matrix-org/matrix-react-sdk pull request #10241
Opened 2023-02-24 23:38 UTC by JeanPaulLucien

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Excuse I'm don't read the text above. I need to go.
_2k23-global.pcss for styles for light and dark theme;
I used styles from dark theme as reference for _2k23_global.pcss
_temp_light.pcss is copy of _light.pcss with deleted same identificators.
New pcss were imported to dark.pcss
And finally background-color for html in dark theme (I did not spend time to fin

2023-02-27 16:31 UTC, robintown reviewed
Sorry, I think I'm a bit confused in general as to what's happening in this PR.

Mainly: What is the goal you're trying to achieve by removing "conflicting" rules from the dark theme? Our CSS processor is smart enough to resolve them without the need for more duplicated code, and as far as I'm aware, the layout of CSS files that we currently use is not causing any issues in the product.

2023-03-16 22:06 UTC, JeanPaulLucien commented on res/themes/global/css/_global.pcss
> +/*
It will able to continue to resolve conflicts and do not worry that may break something.

2023-03-17 00:56 UTC, JeanPaulLucien commented on res/themes/global/css/_global.pcss
> +}
No visual changes.

2023-03-20 00:29 UTC, JeanPaulLucien commented
Please, tell me where html tag is. Is it in react or other repository?

2023-03-20 16:39 UTC, robintown commented
It's here, in element-web: https://github.com/vector-im/element-web/blob/develop/src/vector/index.html

2023-03-21 01:13 UTC, JeanPaulLucien commented on res/themes/global/css/_global.pcss
> +    --lp-background-blur: 45px;
5px is difference. It's not many. I would to stay in standalone file, because it attracts people who want checks difference between 40px and 45px.

2023-03-21 01:14 UTC, JeanPaulLucien commented on res/themes/global/css/_global.pcss
> +}
Done.

2023-03-22 02:58 UTC, robintown requested changes
Before I would commit to reviewing this PR any further, I do really need this question to be addressed:

> What is the goal you're trying to achieve by removing "conflicting" rules from the dark theme? Our CSS processor is smart enough to resolve them without the need for more duplicated code, and as far as I'm aware, the layout of CSS files that we currently use is not causing any issues in the product.

I'm unable to tell what tangible benefit these changes would bring to the product or its developer experience. Rather, the addition of new CSS files that duplicate the content and purpose of existing ones, as proposed here, would harm developer experience.

2023-03-30 22:34 UTC, JeanPaulLucien commented
I have tried my own element-web server. Element strongly needs this PR.

2023-04-27 14:50 UTC, andybalaam commented
It's unclear what this PR is attempting to achieve, and it has actions that are unaddressed, so closing for now.

2023-04-27 14:50 UTC, closed without merging