Fix profile resizer to make first character of a line selectable in IRC layout
matrix-org/matrix-react-sdk pull request #10396
Opened 2023-03-16 19:38 UTC by luixxiul

This PR intends to fix the issue that the first character of a line in IRC layout cannot be selected by replacing the hard-coded inline inset value of `mx_ProfileResizer` with a variable. The issue may be specific to the desktop app for Linux distros (the issue is reproduced on Debian for me). 

To improve accessibility, it is possible to move the resizer a little bit (~5px?) to the left side by setting `- var(--resizer-a11y)` with `--resizer-a11y: 5px`. Let me know if such spacing should be added.

Fixes https://github.com/vector-im/element-web/issues/14764

|Before|After|
|---------|------|
|The resizer overlaps the first character etc.<br />![Screenshot from 2023-03-17 04-22-50](https://user-images.githubusercontent.com/3362943/225731258-cea5ebce-87e5-48d1-9531-044118a97581.png)|![Screenshot from 2023-03-17 04-22-07](https://user-images.githubusercontent.com/3362943/225731250-0e804ba0-681f-4085-8dc7-d55c34a50000.png)|

type: defect

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-03-16 19:48 UTC, luixxiul commented
In fact, moving just 3px feels like great a11y improvement for me. You could test it locally by setting `left: calc(70px + var(--name-width))` via browser's devtool.

2023-03-16 20:16 UTC, luixxiul commented on cypress/e2e/timeline/timeline.spec.ts
> +                cy.get(".mx_ProfileResizer").should("have.css", "inset-inline-start", "153px");
Since the resizer is transparent, it is not possible to use a screenshot test to detect a regression.

2023-03-16 20:17 UTC, luixxiul commented
@florianduros Would you please review when you have some time? Thanks in advance.

2023-03-17 10:03 UTC, florianduros requested changes

2023-03-17 10:04 UTC, florianduros commented
Also I tried to put `left: calc(70px + var(--name-width))` to the `mx_ProfileResizer ` but I didn't see any visible differences. I'am missing something ?

2023-03-17 14:59 UTC, luixxiul commented on res/css/views/rooms/_IRCLayout.pcss
> +        /* stylelint-disable-next-line declaration-colon-space-after */
I was too lazy to notice the deprecation messages on the console.

2023-03-20 13:54 UTC, florianduros reviewed
Better without the ignore rule, thanks!

About the extra `3px`, I think that's a good idea to improve the usability.  Do you to do it in this PR (which is improving the use case of your fix) ? 

If you want to keep the PR in this current state, I'm happy to merge it.

2023-03-20 14:43 UTC, luixxiul commented
> About the extra 3px, I think that's a good idea to improve the usability. Do you want to do it in this PR (which is improving the use case of your fix) ?

Yes, I'm adding the 3px with this PR. Please wait for a moment..

2023-03-21 09:09 UTC, florianduros approved these changes
Great, thank for your contribution !

2023-03-21 09:10 UTC, merged