Added auto focus to Github URL on opening of debug logs modal
matrix-org/matrix-react-sdk pull request #10479
Opened 2023-03-29 22:18 UTC by ShivamSpm

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-03-30 16:05 UTC, t3chguy commented
Can we not simplify this by just using the `autoFocus` attribute?

2023-03-30 16:05 UTC, t3chguy commented
> Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-03-29T22%3A18%3A09Z))

Where is your sign off?

2023-03-30 17:05 UTC, ShivamSpm commented
> > Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-03-29T22%3A18%3A09Z))
> 
> Where is your sign off?

I have added the sign off in this PR comments. I forgot to add it to my commit, sorry about that. I will add it in the commits from now on

2023-03-30 22:03 UTC, ShivamSpm commented
> Can we not simplify this by just using the `autoFocus` attribute?

The autoFocus doesn't work here as this attribute is inconsistent. I searched a little bit and many people are facing issues with this attribute as it only works on the first render (Issue link -> [react/issues/5534](https://github.com/facebook/react/issues/5534)). Hence, this attribute works inconsistently in different components. Its better to use Refs to manage the state of the current component

2023-03-31 11:06 UTC, t3chguy requested changes

2023-03-31 11:06 UTC, t3chguy commented on src/components/views/dialogs/BugReportDialog.tsx
> +    private issueRef: any;
This needs a type specified

2023-04-03 08:48 UTC, t3chguy approved these changes
Looks good to me, thanks for your contribution!

2023-04-03 09:09 UTC, merged