Update tests to ensure file size unit has been fixed
matrix-org/matrix-react-sdk pull request #10568
Opened 2023-04-11 16:29 UTC by luixxiul

This PR is a follow-up to https://github.com/matrix-org/matrix-react-sdk/pull/10561 in order to ensure that file size unit used on a file tile or audio player has been fixed.

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-04-11 17:42 UTC, t3chguy approved these changes

2023-04-11 21:31 UTC, richvdh requested changes

2023-04-12 05:26 UTC, luixxiul commented on cypress/e2e/right-panel/file-panel.spec.ts
> +                // Assert that the file size is displayed in kilobyte, not kibibyte (kB)
I understood. I have not known kilobyte could mean both.. :astonished:

2023-04-12 09:46 UTC, richvdh approved these changes
thanks!

2023-04-12 10:03 UTC, luixxiul commented
@richvdh Thanks for the review!

2023-04-12 11:17 UTC, merged