Include thread replies to message previews
matrix-org/matrix-react-sdk pull request #10631
Opened 2023-04-17 13:59 UTC by weeman1337

![image](https://user-images.githubusercontent.com/6216686/232506321-0b65c704-89e0-457b-8155-a0e63c51ef7e.png)

closes https://github.com/vector-im/element-web/issues/23920

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

element-web notes: Message previews are now also displayed for thread replies

2023-04-17 14:13 UTC, weeman1337 commented on test/components/views/rooms/RoomTile-test.tsx
> +                // Mock thread reply for tests.
If anyone knows how to properly add a thread in a more „integration test“ fashioned way, please leave a comment.

2023-04-18 08:01 UTC, weeman1337 commented on test/components/views/rooms/RoomTile-test.tsx
> +            // @ts-ignore
If anyone knows how to properly add a thread in a more „integration test“ fashioned way, please leave a comment.

2023-04-18 11:35 UTC, weeman1337 commented
Reactions are still an issue. Waiting for https://github.com/matrix-org/matrix-react-sdk/pull/10601

2023-05-08 13:22 UTC, justjanne requested changes

2023-05-08 13:22 UTC, justjanne commented on res/css/views/rooms/_RoomTile.pcss
> +        .mx_RoomTile_subtitle_text {
Long titles don't properly overflow with an ellipsis anymore, instead they break into the next line. The title also needs to be prevented from wrapping or overflowing, as it was before.

```suggestion
        .mx_RoomTile_title,
        .mx_RoomTile_subtitle_text {
```

2023-05-08 13:22 UTC, justjanne commented on res/img/compound/thread-16px.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M2.88867 0.138672C1.36989 0.138672 0.138672 1.36989 0.138672 2.88867V15.1109C0.138672 15.395 0.299174 15.6547 0.553262 15.7817C0.80735 15.9088 1.11141
In dark mode, this icon should have have the color `#a9b2bc`, just like e.g., the explore icon next to the spotlight search. `fill="currentColor"` is the elegant way to solve this.

```suggestion
<path fill-rule="evenodd" clip-rule="evenodd" d="M2.88867 0.138672C1.36989 0.138672 0.138672 1.36989 0.138672 2.88867V15.1109C0.138672 15.395 0.299174 15.6547 0.553262 15.7817C0.80735 15.9088 1.11141 15.8813 1.33867 15.7109L4.36089 13.4442C4.57726 13.2819 4.84043 13.1942 5.11089 13.1942H13.1109C14.6297 13.1942 15.8609 11.963 15.8609 10.4442V2.88822C15.8609 1.36922 14.6295 0.138672 13.1109 0.138672H2.88867ZM3.69421 5.33301C3.69421 4.91879 4.03 4.58301 4.44421 4.58301H11.5553C11.9695 4.58301 12.3053 4.91879 12.3053 5.33301C12.3053 5.74722 11.9695 6.08301 11.5553 6.08301H4.44421C4.03 6.08301 3.69421 5.74722 3.69421 5.33301ZM4.44421 7.24976C4.03 7.24976 3.69421 7.58554 3.69421 7.99976C3.69421 8.41397 4.03 8.74976 4.44421 8.74976H7.99977C8.41398 8.74976 8.74977 8.41397 8.74977 7.99976C8.74977 7.58554 8.41398 7.24976 7.99977 7.24976H4.44421Z" fill="currentColor"/>
```

2023-05-09 10:09 UTC, justjanne approved these changes

2023-06-01 08:28 UTC, merged