Room and user mentions for plain text editor
matrix-org/matrix-react-sdk pull request #10665
Opened 2023-04-19 14:41 UTC by alunturner

Draft for CI. Builds on the commands work (awaiting approval and merge) so will require rebasing.

Adds the ability for the plain text editor to recognise mentions in a message, and hooks it up to the autocomplete. Adds plenty of tests (but could do with some more cypress ones).

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-05-05 12:49 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> -export const mapSuggestion = (suggestion: SuggestionState): MappedSuggestion | null => {
This function was used once, so effectively implemented it as an anonymous function inline in the call to `useMemo` inside `useSuggestion`

2023-05-05 12:49 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +export function processCommand(
Altered for consistency in the file

2023-05-05 12:49 UTC, alunturner commented on test/components/views/rooms/wysiwyg_composer/hooks/useSuggestion-test.tsx
> -
No longer required, added very little value

2023-05-09 18:15 UTC, richvdh requested changes
I'm afraid I'm a bit confused.

2023-05-09 18:15 UTC, richvdh commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    while (shouldDecrementStartIndex(text, startCharIndex)) {
```suggestion
    // search backwards, starting at the character before the cursor, for the
    // start of a mention or command.
    while (shouldDecrementStartIndex(text, startCharIndex)) {
```

2023-05-09 18:15 UTC, richvdh commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    // We have looped throught the text in both directions from the current cursor position
```suggestion
    // We have looped through the text in both directions from the current cursor position
```

2023-05-09 18:15 UTC, richvdh commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    if (startCharIndex < 0 || endCharIndex > text.length) return null;
I'm struggling to understand why this condition is correct.

My understanding of the logic above is:

* `startCharIndex` will be -1 if the first character is a `/` or `@`
* `endCharIndex` will be `text.length + 1` if there is no whitespace after the cursor.

Is it really correct that we do not make a suggestion in these cases?

2023-05-10 08:39 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    }, [suggestion]);
This is a lot neater having a applied the change

2023-05-10 08:43 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
>      const [suggestion, setSuggestion] = useState<SuggestionState>(null);
Yes it is. I think `suggestionData` works, have updated to that.

2023-05-10 11:08 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    // if we have a command at the beginning of a node, but that node isn't the first text node, return
Agreed, much neater

2023-05-10 11:37 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    // a character index in the text string
Yes I suppose it could be thought of that way too. Have amended the comment.

2023-05-10 11:38 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> + * to determine if the current index should be changed.
Yes that's right

2023-05-10 12:13 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> +    return !currentCharIsMentionOrCommand || shouldIgnoreCurrentMentionChar;
Thanks for this - I've taken this suggestion as inspiration and it's improved the legibility greatly

2023-05-10 14:08 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
>      }
Thanks very much for this comment. Starting to write the answer lead me to refactoring this area considerably. Will comment the changes when pushed up.

2023-05-10 14:24 UTC, alunturner commented on cypress/e2e/composer/composer.spec.ts
> +                    cy.wait(250); // let the room list settle
This I took from another test that set up DMs. You're quite right though, `viewRoomByName` is a `findBy*` query so I removed this.

2023-05-10 14:42 UTC, alunturner commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> + * @param offset - the current cursor offset position
Done

2023-05-10 14:49 UTC, alunturner commented
@richvdh thank you very much for the comments - some of the questions lead to refactoring some of the more convoluted logic (especially in the area of decrementing the search index). The suggestions regarding changes to types and function arguments have also helped.

2023-05-11 12:16 UTC, richvdh approved these changes
seems much clearer now, thanks!

Looks good to me once you fix the nits below.

2023-05-11 12:16 UTC, richvdh commented on src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
> + * @returns the `MappedSuggestion` along with it's start and end offsets if found, otherwise null
```suggestion
 * @returns the `MappedSuggestion` along with its start and end offsets if found, otherwise null
```

2023-05-11 17:46 UTC, merged