Apply strictNullChecks to src/LegacyCallHandler.tsx
matrix-org/matrix-react-sdk pull request #10690
Opened 2023-04-21 12:52 UTC by alunturner

Closes https://github.com/vector-im/element-web/issues/25087

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-04-21 13:05 UTC, alunturner commented on src/LegacyCallHandler.tsx
> +
This will probably need to move somewhere else - going to ask about whether we have a place for typeguards

2023-04-21 14:23 UTC, florianduros requested changes
I think that instead of using `isNotNull`, we can use `if(myVar)`. Imo, it's simpler and easy to maintain

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +            if (isNotNull(mappedRoomId)) {
Can we just do ?

```ts
if (mappedRoomId) {
   this.removeCallForRoom(mappedRoomId)
}
```

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +            if (isNotNull(mappedRoomId)) {
`if (mappedRoomId)` ?

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +                if (isNotNull(mappedRoomId)) {
Same ^^ `if (mappedRoomId)`

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +                if (isNotNull(mappedRoomId)) {
`if (mappedRoomId)`

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +        if (isNotNull(roomId)) {
`if (roomId)`

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +            if (isNotNull(dmRoomId)) {
`if (dmRoomId)`

2023-04-21 14:23 UTC, florianduros commented on src/LegacyCallHandler.tsx
> +            if (isNotNull(room)) {
`if (room)`

2023-04-25 10:18 UTC, alunturner commented
> Imo instead of using `isNotNull`, we can use `if(myVar)`. It's simpler and easy to maintain

It is simpler, but we recently discussed not using implicit coercion to Booleans. Let me see if I can find the meeting notes where we discussed it and what the outcome was. 

Notes were from 6 Apr (in the Element Web Weekly notes). My reading of the meeting notes is we should prefer explicit comparison over coercion, which I think is what I have done here. In fact @justjanne some of the comments in the notes were attributed to you, interested to hear what you think too.

2023-04-26 09:47 UTC, justjanne commented
@alunturner It's important to be careful as falsy isn't always what we'd want it to be. In fact, I actually saw another case of a falsy value (first enum member) being treated as if it was false when it shouldn't have been just this week: https://github.com/matrix-org/matrix-js-sdk/pull/3248#discussion_r1176517807

So I'd keep the isNotNull helper.

2023-05-05 12:03 UTC, alunturner commented
@florianduros 👋 I'm back after a few days away and trying to get some stalled work moving. What do you think is the way ahead here? I think we should stick with the `isNotNull` typeguard and Janne seems to agree too.

2023-05-05 12:14 UTC, florianduros commented
@alunturner okay, seems fine to me !

2023-05-05 12:15 UTC, florianduros approved these changes

2023-05-05 16:08 UTC, merged