Update `timeline.spec.ts` - use Cypress Testing Library
matrix-org/matrix-react-sdk pull request #10721
Opened 2023-04-26 17:17 UTC by luixxiul

For https://github.com/vector-im/element-web/issues/25033

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-04-27 11:31 UTC, weeman1337 requested changes
:+1:  thank you for your contribution @luixxiul .

Looks good in general. Just a few minor comments.

2023-04-27 11:31 UTC, weeman1337 commented on cypress/e2e/timeline/timeline.spec.ts
> +                cy.get(".mx_GenericEventListSummary_summary")
I would personally remove `get(".mx_GenericEventListSummary_summary")` . This query does already run „within“ `.mx_GenericEventListSummary`.

→

```
cy.fndByText(OLD_NAME + " created and configured the room.")
```

2023-04-27 11:31 UTC, weeman1337 commented on cypress/e2e/timeline/timeline.spec.ts
> +                    cy.findByText("Hello world", { timeout: 1000 });
Can you remove the timeout? Sometimes tests run slowly. This is a possible cause for flaky tests.

2023-06-02 02:07 UTC, luixxiul commented
@weeman1337 The PR should be fine. Would you please have a look at again when you have some time?

2023-06-02 08:19 UTC, weeman1337 approved these changes
/lgtm thank you @luixxiul  :+1:

2023-06-05 15:57 UTC, merged