making sender name differentiable using < >
matrix-org/matrix-react-sdk pull request #10748
Opened 2023-04-29 12:49 UTC by rameshsinghppc

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-05-03 11:50 UTC, richvdh commented
This appears to be much the same as https://github.com/matrix-org/matrix-react-sdk/pull/10013, and as such has the same problems:

> This code is used throughout the whole product and not only in the context of chat exports.
> You will also need to write tests for this PR to be merged as per then contributing guidelines https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md

Please read [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md) which gives instructions on how to make a good pull request. Looking at the format of other pull requests on the repository should help too.

2023-05-03 11:50 UTC, richvdh requested changes
^

2023-05-06 20:37 UTC, rameshsinghppc commented
> Fixes [vector-im/element-web#23837](https://github.com/vector-im/element-web/issues/23837)

I have sent PR(https://github.com/matrix-org/matrix-js-sdk/pull/3345#issue-1698769126), please review it

2023-05-08 13:10 UTC, justjanne commented
Both this and [the other new PR](https://github.com/matrix-org/matrix-js-sdk/pull/3345) are currently not in a state that can be reviewed or merged.

If you genuinely want to contribute this, I'd suggest adding another parameter to the functions in TextForEvent and using that to control whether the sender name will be wrapped in brackets. Take a look at the parameter that's used for controlling whether hidden events are included as an example.

2023-05-23 17:31 UTC, rameshsinghppc commented
![Screenshot from 2023-05-23 23-00-44](https://github.com/matrix-org/matrix-react-sdk/assets/115406405/3c5bda49-15e5-4cc7-b679-1fb70f6337db)

2023-05-24 09:29 UTC, richvdh requested changes
This is looking slightly more plausible but is causing a large number of type-checking and test failures. Please take the time to go through the check failures and address them.

2023-05-24 09:30 UTC, richvdh commented on src/TextForEvent.tsx
> +export function textForEvent(ev: MatrixEvent, allowJSX = false, showHiddenEvents?: boolean,enclosedSender?:boolean): string | React.ReactNode {
Please document the new parameter in the doc-comment above.

2023-06-03 14:49 UTC, richvdh commented
@rameshsinghppc are you still keen to work on this? If you need pointers on how to fix up the CI failures then let us know.

2023-06-04 06:26 UTC, rameshsinghppc commented
> @rameshsinghppc are you still keen to work on this? If you need pointers on how to fix up the CI failures then let us know.

@richvdh Yes, please help me to fix these failures.

2023-06-05 08:56 UTC, richvdh commented
> @richvdh Yes, please help me to fix these failures.

Ok, what have you tried so far and which parts are confusing you?

2023-06-08 16:56 UTC, rameshsinghppc commented
> > @richvdh Yes, please help me to fix these failures.
> 
> Ok, what have you tried so far and which parts are confusing you?

![Screenshot from 2023-05-28 15-09-44](https://github.com/matrix-org/matrix-react-sdk/assets/115406405/e26e9414-0dff-4b82-b3ac-11377f9e6f5b)

2023-06-09 10:28 UTC, richvdh commented
Right; a lot of the problem here is that it is building against your fork of `matrix-js-sdk` (https://github.com/rameshsinghppc/matrix-js-sdk) which is outdated. (We have some magical branch matching.) You can see this happening at https://github.com/matrix-org/matrix-react-sdk/actions/runs/5159164960/jobs/9322532146#step:4:48.

Suggest, as a first step, you pull the latest `develop` into your fork of `matrix-js-sdk`. Ping me once you've done so and I'll re-run CI here.

2023-06-09 11:02 UTC, richvdh commented
> Right; a lot of the problem here is that it is building against your fork of `matrix-js-sdk` (https://github.com/rameshsinghppc/matrix-js-sdk) which is outdated. (We have some magical branch matching.) You can see this happening at https://github.com/matrix-org/matrix-react-sdk/actions/runs/5159164960/jobs/9322532146#step:4:48.
> 
> Suggest, as a first step, you pull the latest `develop` into your fork of `matrix-js-sdk`. Ping me once you've done so and I'll re-run CI here.

To be more accurate here: it's actually building against [the branch named `rameshsingh` in your fork of `matrix-js-sdk`](https://github.com/rameshsinghppc/matrix-js-sdk/tree/rameshsingh). (Our magic branch-matching will use a js-sdk branch with the same name as your react-sdk branch).

So you need to update that branch (or just delete it).

2023-06-09 14:28 UTC, rameshsinghppc commented
> > Right; a lot of the problem here is that it is building against your fork of `matrix-js-sdk` (https://github.com/rameshsinghppc/matrix-js-sdk) which is outdated. (We have some magical branch matching.) You can see this happening at https://github.com/matrix-org/matrix-react-sdk/actions/runs/5159164960/jobs/9322532146#step:4:48.
> > Suggest, as a first step, you pull the latest `develop` into your fork of `matrix-js-sdk`. Ping me once you've done so and I'll re-run CI here.
> 
> To be more accurate here: it's actually building against [the branch named `rameshsingh` in your fork of `matrix-js-sdk`](https://github.com/rameshsinghppc/matrix-js-sdk/tree/rameshsingh). (Our magic branch-matching will use a js-sdk branch with the same name as your react-sdk branch).
> 
> So you need to update that branch (or just delete it).

2023-06-09 14:32 UTC, rameshsinghppc commented
> > Right; a lot of the problem here is that it is building against your fork of `matrix-js-sdk` (https://github.com/rameshsinghppc/matrix-js-sdk) which is outdated. (We have some magical branch matching.) You can see this happening at https://github.com/matrix-org/matrix-react-sdk/actions/runs/5159164960/jobs/9322532146#step:4:48.
> > Suggest, as a first step, you pull the latest `develop` into your fork of `matrix-js-sdk`. Ping me once you've done so and I'll re-run CI here.
> 
> To be more accurate here: it's actually building against [the branch named `rameshsingh` in your fork of `matrix-js-sdk`](https://github.com/rameshsinghppc/matrix-js-sdk/tree/rameshsingh). (Our magic branch-matching will use a js-sdk branch with the same name as your react-sdk branch).
> 
> So you need to update that branch (or just delete it).

@richvdh  Thank you for your help. I just deleted that repository.

2023-06-09 14:50 UTC, rameshsinghppc commented
![Screenshot from 2023-06-09 20-19-34](https://github.com/matrix-org/matrix-react-sdk/assets/115406405/57af9295-9da8-4a68-b73a-85cf7b549b96)

2023-06-09 15:49 UTC, richvdh commented
you don't need to paste a screenshot - I can see the errors in CI.

Look at the line of code it is complaining about:

> else return textForEvent(mxEv, this.room.client,true) + mediaText;

What is the return type of `textForEvent`? (Hint: look at the [typescript definitions](https://github.com/matrix-org/matrix-react-sdk/pull/10748/files#diff-0e42a43897ea37a7954b73214502ba56f4d62b4adc509229c4fc483379102caeR964-L963) and consider which of the two prototypes your code is calling). Is it definitely a valid type to use in a string concatenation?

2023-06-12 17:22 UTC, richvdh commented
@rameshsinghppc once you have made some changes you think will fix the CI please say so in a comment.

2023-06-12 18:13 UTC, rameshsinghppc commented
> @rameshsinghppc once you have made some changes you think will fix the CI please say so in a comment.

@richvdh No sir, It's contributor's responsibility to resolve all the issues. This is my first open source contribution, so I don't know the steps for the open source contribution. I want to do open source contribution and learn through that.
One thing also I know that reviewer are very busy they don't have time for bad pull request but I am not getting any other ways through that I can learn open source contribution.
If you think my pull request is causing some problems for the maintainers then I am really sorry for that, you want then I can close this PR.

2023-06-12 18:20 UTC, rameshsinghppc commented
@richvdh Few days back I made some changes in the code, please re- run the CI.

2023-06-13 09:45 UTC, richvdh commented on src/TextForEvent.tsx
> +): string;
the problem here is that the new overload signature doesn't match the real definition of the function: the third parameter is always `allowJSX`.

https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads has more information on overload signatures, and explains it better than I can.

2023-06-13 20:16 UTC, richvdh requested changes

2023-06-13 20:16 UTC, richvdh commented on src/utils/exportUtils/PlainTextExport.ts
> +        else return textForEvent(mxEv, this.room.client, true, true) + mediaText;
This appears to set `allowJSX` and `showHiddenEvents` to `true` where neither was true before? Is that deliberate? If so, why?

2023-06-20 15:34 UTC, richvdh commented
@rameshsinghppc there's no need to merge `develop` every day.

2024-05-17 11:24 UTC, richvdh commented
Thanks for your contribution. I'm going to close this for now as the changes requested haven't been made. If you're interested in continuing to work on this please let us know and we can reopen the pull request. Thanks!

2024-05-17 11:24 UTC, closed without merging