Optimize `mx_AppTileMenuBar_title`
matrix-org/matrix-react-sdk pull request #10895
Opened 2023-05-14 07:38 UTC by luixxiul

For https://github.com/vector-im/element-web/issues/25269

This PR intends to optimize the structure of `mx_AppTileMenuBar_title` by removing an inline style and adopting our naming policy, to make it possible for us to update the style rules of `mx_AppTileMenuBar` easily.

|Before|After|
|---------|------|
|![0_1](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/4895aee7-f34a-44f1-b428-1a93de9ba339)|![1](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/27125656-d82b-43c0-8962-f1479c6f5e8c)|
|![0_2](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/e5fbb15b-ef0a-4b19-b449-63265bf51381)<br/>![0_3](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/fac164e4-d385-4de2-84f3-8396aed38513)|![1](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/d5e941c0-6aad-4ac7-87d5-84a5cf110b1d)|
|![0](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/ab1396bf-4309-4200-ab1a-13675b9360c9)|![1_1](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/c06e084c-7372-4aa3-87e4-f5b69b111e34)|

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-05-14 08:44 UTC, luixxiul commented on res/css/views/rooms/_AppsDrawer.pcss
> -        > :last-child {
`.mx_AppTileMenuBar_title > :last-child` was [this `span` element](https://github.com/matrix-org/matrix-react-sdk/pull/10895/files#diff-0a893165e4d1987c581fd62cbf23363bc9412783e5cb24ac2fba68d2a2a5bba7L511) below.

2023-05-15 07:12 UTC, gsouquet requested changes
I'm struggling to see the optimisation here?
Why is it a bad thing to have an inline element?

2023-05-15 07:37 UTC, luixxiul commented
I do not have a strong opinion of inlining styles, so I am going to revert that change.

2023-05-15 08:06 UTC, luixxiul commented
> You mention confirming to the naming policy, but I only see you created some new CSS classes and not changed old ones? 

I am not quite sure if I understood you well, but I intentionally am trying to split tasks for the sake of reviewers who prefer small PRs. If we address several tasks on this PR, we would rename `mx_AppTileMenuBar` into `mx_AppTile_menuBar`, creating `_AppTile.pcss`, moving the style rules to the file, but I would like to address them with other PRs.

2023-05-15 09:11 UTC, gsouquet commented
I'm going by the description of the pull request here, and you mention that the changes are to conform the classes names with our styleguide. 
But I do not see any changes related to that besides `mx_AppTileMenuBar_title_widgetAvatar`, and I do not think it was violating the style guide in the first place.

The class is scoped within `mx_AppTileMenuBar`, so that should not be a concern.

---

But I would also like to address the small pull request comment. 
I believe it is important to a small pull request. The ideal is to make the smallest pull request possible for a coherent unit of work.

2023-05-15 09:17 UTC, luixxiul commented
> The class is scoped within mx_AppTileMenuBar, so that should not be a concern.

Yes, I would agree. 

Despite the difficulty of understanding how `> :last-child` works, the PR seems to have become irrelevant.

2023-06-01 14:45 UTC, closed without merging