Improve user experience of the decryption banner
matrix-org/matrix-react-sdk pull request #11012
Opened 2023-05-30 13:59 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-05-31 14:19 UTC, richvdh requested changes

2023-05-31 14:19 UTC, richvdh commented on src/components/views/rooms/DecryptionFailureBar.tsx
> +    } else if (developerMode && !needsVerification && hasOtherVerifiedDevices && anyUnrequestedSessions) {
The comment should really be inside the relevant `if` clause:

```suggestion
    } else if (developerMode && !needsVerification && hasOtherVerifiedDevices && anyUnrequestedSessions) {
        // In developerMode, show a button to resend key requests if there are other devices we could request keys from.
```

2023-05-31 14:19 UTC, richvdh commented on test/components/views/rooms/DecryptionFailureBar-test.tsx
> +    it("The banner is hidden if there are no other verified devices", async () => {
```suggestion
    it("The banner is hidden if there is a key backup but no other verified devices", async () => {
```

2023-05-31 14:19 UTC, richvdh commented on test/components/views/rooms/DecryptionFailureBar-test.tsx
> +    it("The banner is hidden if there are no other verified devices", async () => {
it seems like the code doesn't actually care about key backup or other verified devices?

2023-06-01 13:47 UTC, florianduros commented
Irrelevant since https://github.com/vector-im/element-meta/issues/1358#issuecomment-1572049548

Closing it in favor of https://github.com/matrix-org/matrix-react-sdk/pull/11027.

2023-06-01 13:47 UTC, closed without merging