Move Room context threadId our of RoomView state
matrix-org/matrix-react-sdk pull request #11064
Opened 2023-06-08 10:26 UTC by t3chguy

Fixes https://github.com/vector-im/element-web/issues/25487

2023-06-09 12:00 UTC, richvdh requested changes

2023-06-14 11:22 UTC, t3chguy commented on src/components/structures/RoomView.tsx
> +                            defaultSize={this.state.threadRightPanel ? 500 : undefined}
Its an optional parameter, because of its presence in `defaultProps` and React's Defaultize behaviour on types

2023-06-15 11:16 UTC, richvdh commented on src/components/structures/RoomView.tsx
> +                            defaultSize={this.state.threadRightPanel ? 500 : undefined}
>  otherwise TSC strict would have been shouting at me

I did wonder!

2023-06-15 11:22 UTC, richvdh approved these changes
lgtm

2023-06-15 12:27 UTC, merged