`CreateKeyBackupDialog.tsx`: Remove logic for servers which are not supporting cross-signing
matrix-org/matrix-react-sdk pull request #11076
Opened 2023-06-12 16:27 UTC by florianduros

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Closes https://github.com/vector-im/crypto-internal/issues/101

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

2023-06-13 10:33 UTC, richvdh requested changes
It seems like we should get rid of `state.secureSecretStorage` ?

2023-06-15 11:14 UTC, richvdh commented on src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
>          let info;
looks like maybe this needs a type annotation to avoid a typescript warning at line 100?

2023-06-15 13:57 UTC, florianduros commented on test/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
> +    });
Yes good catch

2023-06-16 12:25 UTC, richvdh commented
Let's skip the quality gate on this. 3 out of the 4 changes are covered, and this represents a substantial increase in test coverage overall.

2023-06-16 12:25 UTC, merged