Disable 3pid fields in settings when `m.3pid_changes` capability is disabled
matrix-org/matrix-react-sdk pull request #11430
Opened 2023-08-21 01:38 UTC by kerryarchibald

Fixes https://github.com/vector-im/element-web/issues/25995

Disable 3pid fields in settings when `m.3pid_changes` capability is disabled

<img width="656" alt="Screenshot 2023-08-21 at 13 31 37" src="https://github.com/matrix-org/matrix-react-sdk/assets/3055605/b01dd9c4-d534-4ace-9f59-a8226ce02e80">
<img width="652" alt="Screenshot 2023-08-21 at 13 31 28" src="https://github.com/matrix-org/matrix-react-sdk/assets/3055605/9e6648f3-21fc-497e-a8d3-3df4dcc0d496">

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-08-21 09:26 UTC, t3chguy requested changes
Looks sane otherwise

2023-08-21 09:26 UTC, t3chguy commented on src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
> +        const canMake3pidChanges = capabilities["m.3pid_changes"]?.enabled === true;
We support as far back as `v1.1` which doesn't have `m.3pid_changes` so the behaviour for when it is missing has to be assume `true` when it missing

2023-08-22 04:33 UTC, kerryarchibald commented
@t3chguy have also enabled auto-merge here

2023-08-22 06:07 UTC, t3chguy approved these changes

2023-08-22 06:42 UTC, merged