Allow creating public knock rooms
matrix-org/matrix-react-sdk pull request #11481
Opened 2023-08-29 14:29 UTC by charlynguyen

We @nordeck are currently implementing the knock rooms behind the feature flag `feature_ask_to_join` (introduced in https://github.com/matrix-org/matrix-react-sdk/pull/11182).

This pull request allows creating public knock rooms.

Follow up of: https://github.com/matrix-org/matrix-react-sdk/pull/11464
Epic: https://github.com/vector-im/element-web/issues/18655

#### Relates to

- https://github.com/matrix-org/matrix-react-sdk/pull/11404
  - https://github.com/matrix-org/matrix-js-sdk/pull/3673
- https://github.com/matrix-org/matrix-react-sdk/pull/11353
  - https://github.com/matrix-org/matrix-js-sdk/pull/3647
- https://github.com/matrix-org/matrix-react-sdk/pull/11248
- https://github.com/matrix-org/matrix-react-sdk/pull/11182
- https://github.com/vector-im/element-web/pull/25923

### Screens

![CreateRoomDialog](https://github.com/matrix-org/matrix-react-sdk/assets/1422657/ccfc463f-2d63-427f-bea6-823176676232)

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: enhancement

2023-08-30 10:45 UTC, richvdh commented
Sadly I think this is still blocked on an answer from the design team. @daniellekirkwood [wrote](https://github.com/matrix-org/matrix-react-sdk/pull/11464#issuecomment-1691902413):

> > You're happy for the setting to only appear for knockable rooms, and not (say) "public" rooms. (This seems particularly unintuitive to me)
> 
> Good point -- when someone selects Public it doesn't necessarily add it to the directory, right? Maybe this checkbox should appear there also... @nadonomy i would like support on that question...

@nadonomy / @daniellekirkwood can we get some clarity on why this checkbox only applies to knockable rooms?

2023-08-30 11:15 UTC, richvdh requested changes

2023-08-30 11:15 UTC, richvdh commented on src/components/views/elements/LabelledCheckbox.tsx
> +    // Optional CSS class to apply to the label
```suggestion
    // Optional CSS class to apply to the label
```

2023-08-30 11:15 UTC, richvdh commented on test/components/views/dialogs/CreateRoomDialog-test.tsx
> +        describe("when disabling feature", () => {
```suggestion
        describe("when feature is disabled", () => {
```

2023-08-30 11:15 UTC, richvdh commented on test/components/views/dialogs/CreateRoomDialog-test.tsx
> +        describe("when enabling feature", () => {
```suggestion
        describe("when feature is enabled", () => {
```

2023-08-30 11:15 UTC, richvdh commented on test/components/views/dialogs/CreateRoomDialog-test.tsx
>              const onFinished = jest.fn();
we either need to reset this mock after each test, or create a new one before each test.

2023-08-31 08:43 UTC, richvdh commented
> Sadly I think this is still blocked on an answer from the design team. @daniellekirkwood [wrote](https://github.com/matrix-org/matrix-react-sdk/pull/11464#issuecomment-1691902413):
> 
> > > You're happy for the setting to only appear for knockable rooms, and not (say) "public" rooms. (This seems particularly unintuitive to me)
> > 
> > 
> > Good point -- when someone selects Public it doesn't necessarily add it to the directory, right? Maybe this checkbox should appear there also... @nadonomy i would like support on that question...
> 
> @nadonomy / @daniellekirkwood can we get some clarity on why this checkbox only applies to knockable rooms?

Design folks say: let's go with it as designed and implemented for now. We may return to this and clean it up in future.

2023-08-31 17:29 UTC, daniellekirkwood commented
> We may return to this and clean it up in future

We will -- it's in the roadmap already :)

2023-09-04 14:32 UTC, richvdh commented on src/components/views/dialogs/CreateRoomDialog.tsx
>      canChangeEncryption: boolean;
thank you for adding all these! for future reference they should really be `/** ... */` -style comments for future interpretation by `tsdoc`.

2023-09-04 14:32 UTC, richvdh commented on src/components/views/dialogs/CreateRoomDialog.tsx
> +    // Indicates whether the knock room is public visible. Applies only for rooms with knock join rule.
```suggestion
    /**
      * Indicates whether the created room should have public visibility (ie, it should be
      * shown in the public room list). Only applicable if `joinRule` == `JoinRule.Knock`.
      */
```

2023-09-04 14:34 UTC, richvdh commented
@charlynguyen thanks for updating this! For future reference, please avoid force-pushing to git after a review has been done. Github makes it very hard to see what has changed since the previous review!

2023-09-04 15:52 UTC, richvdh approved these changes
thank you for your work on this!

2023-09-04 17:47 UTC, merged