Fix: Right panel keeps showing chat when unmaximizing widget.
matrix-org/matrix-react-sdk pull request #11697
Opened 2023-10-02 17:27 UTC by manancodes

## Checklist

- [x] Tests written for new code (and old code if feasible)
- [x] Linter and other CI checks pass
- [x] Sign-off given on the changes (see [CONTRIBUTING.md] (https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

[Fixes https://github.com/vector-im/element-web/issues/25285](https://github.com/vector-im/element-web/issues/26265)
Signed-off-by: Manan Sadana manancodes.dev@gmail.com

This was the behaviour before the fix:
Unmaximizing the widget does not close the Right panel, resulting in 2 chat views
<img width="600" alt="Before" src="https://github.com/matrix-org/matrix-react-sdk/assets/54790263/8c5fea2f-5165-4b56-aac2-46283546e157">

And this is the behaviour after the fix:
Unmaximizing closes the Right panel.
<img width="600" alt="After" src="https://github.com/matrix-org/matrix-react-sdk/assets/54790263/eec5526b-b028-403a-8d0b-1b4db6f40ad2">

Type: defect

2023-10-02 17:39 UTC, t3chguy commented
> Tests written for new code (and old code if feasible)

You checked this but actually wrote no tests..?

2023-10-02 17:50 UTC, manancodes commented
> > Tests written for new code (and old code if feasible)
> 
> You checked this but actually wrote no tests..?

Sorry, corrected now. 
Did not realise I had to write tests for this. I'm still getting familiar with testing, looking into this. If you could refer some resources, it would really help.

2023-10-03 11:04 UTC, andybalaam commented
> Did not realise I had to write tests for this. I'm still getting familiar with testing, looking into this. If you could refer some resources, it would really help.

There's some general guidance at https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md

> Also, there must be tests which check if the chat opens in Right Panel when widget is maximised. Where can I find that? It will help me with writing the new tests. Thanks.

Take a look at `cypress/e2e/right-panel/right-panel.spec.ts` and the other tests in that directory. Hopefully they are similar to what you need. You might possibly need to add some new Cypress commands, similar to `cy.openRoomSettings();` which is fiddly but can be done. Take a look at how that one is made.

This might be quite difficult at first, so do please ask questions in #element-dev:matrix.org . It will be easiest to help if you have some code in a branch or PR that you can point at, so your questions are specific.

Thanks!

2023-10-05 16:26 UTC, manancodes commented
I'm still learning cypress, I have some questions:

1. Am I using the right selectors?
2. I'm sure this is not enough, how can I check if the widget is taking the whole height when maximising?
3. It checks if the right panel is opened, how can I check if the right panel has the chat in it?
4. Are the tests in the right file? If no, where should I put them?

2023-10-12 09:51 UTC, manancodes commented
@florianduros Can you please look into this?

2023-10-12 09:59 UTC, florianduros commented
> @florianduros Can you please look into this?

I'll take a look today or tomorrow

2023-10-13 15:42 UTC, florianduros requested changes

2023-10-13 17:45 UTC, manancodes commented on cypress/e2e/widgets/layout.spec.ts
> +        cy.get('div[title="Maximise"]').click();
I have used accessible selectors now, can you review again? Thanks.

2023-10-13 17:49 UTC, manancodes commented
Also, when you get time, can you please answer the queries that I had?

2023-10-16 08:19 UTC, manancodes commented
Is it ready to be merged?
I'm participating in hacktoberfest so it will help if this gets merged soon. Thanks.

2023-10-16 14:06 UTC, florianduros commented
> Also, when you get time, can you please answer the queries that I had?

1. With your last changes yes!
2/3. Let me check how this part of the code is made and your fix is working
4. They seems to be in the right file.

2023-10-16 15:14 UTC, florianduros commented
@manancodes 

I think we can check if the chat/timeline is in the right panel with this piece of code:

```ts
this.context.rightPanelStore.currentCard.phase === RightPanelPhases.Timeline
```

2023-10-16 15:43 UTC, manancodes commented
Thanks. I will add this.

2023-10-17 11:46 UTC, manancodes commented
@florianduros 

This is how it is being checked in another file

https://github.com/matrix-org/matrix-react-sdk/blob/fd08e742757031bbb1ec7b050f83642d712c5fd0/cypress/e2e/right-panel/right-panel.spec.ts#L44-L46

How about using
`cy.get(".mx_BaseCard_header").should("contain", "Chat"); `

I am new to cypress, implementing your suggestion will take longer because I could not find a similar implementation. I will work on this if you are not ok with my proposal.

2023-10-17 13:13 UTC, florianduros commented
@manancodes I thought you asked how to check in the component implementation, not in the test. My fault.

`cy.get(".mx_BaseCard_header").should("contain", "Chat"); ` is not specific to the right panel, I think it will get the main chat too. 

We need first to select the right panel and query the chat in it:

```ts
cy.get(".mx_RightPanel").within(() => {
    cy.get(".mx_BaseCard_header").should("contain", "Chat"));
})
```
[Cypress documentation within](https://docs.cypress.io/api/commands/within)

2023-10-17 14:22 UTC, manancodes commented
Perfect, I will add this.

2023-10-21 10:40 UTC, manancodes commented
Done. Added and tested.

2023-10-23 06:29 UTC, manancodes commented
@florianduros , sorry for disturbing you, but I'm participating in hacktoberfest, if this get's merged soon it will really help me with that.

2023-10-23 08:20 UTC, florianduros approved these changes
Thanks!

2023-10-23 09:03 UTC, merged