Update RoomSummaryCard navigation links
matrix-org/matrix-react-sdk pull request #11812
Opened 2023-10-31 15:46 UTC by germain-gg

For https://github.com/vector-im/element-web/issues/25883

<img width="359" alt="Screenshot 2023-10-31 at 15 41 53" src="https://github.com/matrix-org/matrix-react-sdk/assets/769871/3eefc473-7d66-4dbf-b807-1f02666de629">

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2023-11-01 09:01 UTC, weeman1337 requested changes
The new sidebar looks really good :art: 

Should the widgets item not also be a new menu item? It does now look a bit out of place.

![image](https://github.com/matrix-org/matrix-react-sdk/assets/6216686/4a91a8c4-7b53-499a-bb8c-6122488086a6)

Also without using the new room header you can now no longer reach the member list. Designs use tabs here. Maybe as an intermediate solution we could add a „People“ item?

2023-11-14 03:13 UTC, kerryarchibald commented on src/components/views/right_panel/RoomSummaryCard.tsx
> +            <MenuItem
<img width="333" alt="Screenshot 2023-11-14 at 16 02 26" src="https://github.com/matrix-org/matrix-react-sdk/assets/3055605/f88e43f6-4f68-46f7-a279-1e56c0a5b681">

Fixed in compound 0.8.1

2023-11-14 11:02 UTC, americanrefugee commented
I created a [new disabled menu item state](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=2999-18282&mode=design&t=wkBXeDJWuNL511WL-4
).

2023-11-15 03:08 UTC, kerryarchibald commented
hey @weeman1337, this is ready for another pass. thanks!

2023-11-15 07:47 UTC, weeman1337 approved these changes
The disabled buttons are now looking disabled :+1: 

Still the widgets actions are having a „link“ style:

![image](https://github.com/matrix-org/matrix-react-sdk/assets/6216686/66db5b57-eaf4-45a7-9d98-731bcdceafab)

Is there another issue to migrate the widget actions to the new menu design?

2023-11-15 22:44 UTC, t3chguy approved these changes
Approving the yarn.lock change

2023-11-16 02:38 UTC, kerryarchibald commented
@weeman1337 the widgets change is captured here, under the 'next iteration' epic https://github.com/vector-im/wat-internal/issues/77

2023-11-16 04:41 UTC, merged