Fix TAC opening with keyboard
matrix-org/matrix-react-sdk pull request #12285
Opened 2024-02-26 14:51 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Closes https://github.com/element-hq/element-web/issues/27016

The compound Menu component is putting the keyboard listeners on the trigger through the props but the `AccessibilityButton` is already handling some keyboard events.

- Replace the current implementation with the tooltip and icon button of compound components.
- The compound tooltip visual is different than the EW Web

https://github.com/matrix-org/matrix-react-sdk/assets/2621378/edad5d8a-a3e9-4b77-9b41-a8e039240981

2024-02-26 16:07 UTC, t3chguy requested changes
What do we get from using AccessibilityButton without its accessible keyboard handling? Why not just switch to Compound button for usecases which need `disableKeyboardOverrides`

2024-02-26 16:48 UTC, florianduros commented
> What do we get from using AccessibilityButton without its accessible keyboard handling? Why not just switch to Compound button for usecases which need `disableKeyboardOverrides`

Because, it means add all the glue to between the EW tooltip and the compound button.
The compound tooltip doesn't have the same style than the other tooltip in the spaces, so I'm using the old one of EW

2024-02-26 16:49 UTC, t3chguy commented
We have a 50/50-ish mix of Compound/local tooltips already, so please do not consider that a blocker, preferring Compound tooltips going forward

2024-02-26 16:53 UTC, t3chguy commented
> > We have a 50/50-ish mix of Compound/local tooltips already, so please do not consider that a blocker, preferring Compound tooltips going forward
> 
> Okay, I'll discard the use of the `AccessibilityButton` here and use the `Tooltip` and `IconButton` of compound instead

Compund ftw

2024-02-29 13:33 UTC, florianduros commented on src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
> +                        {/* This is dirty, but we need to add the label to the indicator icon */}
The issue is that the space panels are till not migrated to compound and we doesn't implement new design. I'm trying to keep visual consistency especially when the space is expanded.

But i agree, I don't like it, it's hacky and dirty

2024-02-29 13:48 UTC, florianduros commented on src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
> +                    ref={ref}
Indeed !
I was extending the HTMLDiv props of the previous impl instead of the compound component

2024-02-29 13:50 UTC, t3chguy approved these changes

2024-02-29 14:28 UTC, merged