Make widget theme reactive - Update widget url when the theme changes
matrix-org/matrix-react-sdk pull request #12295
Opened 2024-02-28 19:46 UTC by toger5

Signed-off-by: Timo K <toger5@hotmail.de>

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-02-28 20:10 UTC, t3chguy requested changes
This would cause you to be kicked out of conferences, docs, games etc, we should not be causing the widget to reload without user intervention, they may lose whatever they were typing etc.

2024-02-28 20:30 UTC, toger5 commented
depends on where in the url the widget is adding the theme.
If it is adding it to the hash it will not reload the page.

This needs to be documented so that widgets that cannot just be reloaded are aware, that the theme part of the url can change on the fly.

What do you think about only updating it if the url has the theme in the hash?
Another idea to improove that situation would be to make this a widget capability. So the default would be to not change the url onChange. Widget devs have to opt in to make url change on theme change and they can only do so if that is compatible with their widget like with EC.

2024-02-29 11:44 UTC, toger5 commented
> How about sending the theme update over postMessage?

That was the initial plan but this is simpler and does not require a new msc.
(action would need changes in: react-sdk, rust-sdk, matrix-widget-api, element-call + new spec)

I still think the action would be the most conventional solution. It just would be a much bigger work piece. Maybe worthit though. I like this workaround to support the light theme soonish. It reuses the url template system and the theme property that already exists there.

2024-03-04 10:03 UTC, t3chguy requested changes
Looks like it needs test coverage to be merged

2024-03-04 10:03 UTC, t3chguy commented on src/components/views/elements/AppTile.tsx
> +        if (this.props.app.type === WidgetType.CALL.preferred) this.setState({ widgetUrl: this.sgWidget?.embedUrl });
Isn't there a `matches` method on WidgetType.CALL to check both?

2024-03-06 11:17 UTC, t3chguy requested changes

2024-03-06 11:17 UTC, t3chguy commented on test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
> +      aria-label="widget-container"
This it not an accessible label.

2024-03-06 11:17 UTC, t3chguy commented on src/components/views/elements/AppTile.tsx
> +                            data-widget-url={this.state.widgetUrl}
Maybe use `data-test-*` so its clear its only for tests

2024-03-11 09:12 UTC, t3chguy commented on src/theme.ts
>          }
why nested if? `&&` is a thing

2024-03-11 09:12 UTC, t3chguy commented on src/settings/watchers/ThemeWatcher.ts
> +export default class ThemeWatcher extends EventEmitter {
Please use a TypedEventEmitter instead

2024-03-13 10:17 UTC, t3chguy approved these changes

2024-03-13 15:15 UTC, merged