Refine styles of menus, toasts, popovers, and modals
matrix-org/matrix-react-sdk pull request #12332
Opened 2024-03-11 13:36 UTC by robintown

This is a reintroduction of https://github.com/matrix-org/matrix-react-sdk/pull/12247, with the difference that modal styles have now been refreshed as well.

Before|After
-|-
![Screenshot from 2024-02-13 19-18-43](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/90bb7cbd-6ce6-4a60-8c2b-467855d9768c)|![Screenshot from 2024-02-13 19-19-42](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/84b1ed21-5720-4d5c-8834-95e95cf38b3a)
![Screenshot 2024-02-13 at 19-18-54 Element 3 general](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/742c65c4-8c24-4997-b576-cff3c0f53485)|![Screenshot 2024-02-13 at 19-19-27 Element Test](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/fea22ddd-cc0f-4df3-86b5-3a249a3afa07)
![Screenshot from 2024-03-11 09-34-16](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/244c4ca9-6057-472b-a71b-646a9508a6f1)|![Screenshot from 2024-03-11 09-33-20](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/0b5f3907-a84d-4f2f-97a7-b2b580a45f28)
![Screenshot from 2024-03-11 09-34-02](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/cae01daa-3290-4050-823a-4389281d0c4a)|![Screenshot from 2024-03-11 09-32-08](https://github.com/matrix-org/matrix-react-sdk/assets/48614497/29762faf-6367-42a5-a979-6a86868e3db9)

2024-03-11 13:44 UTC, t3chguy requested changes
test are unhappy, please fix CI and re-request review

2024-03-11 14:10 UTC, t3chguy commented on playwright/snapshots/room-directory/room-directory.spec.ts/filtered-no-results-linux.png
This loss of min-height seems unintentional, it was by design a fixed height to not bounce in size as you type

2024-03-12 18:43 UTC, t3chguy approved these changes

2024-03-13 13:38 UTC, BillCarsonFr approved these changes
From a crypto point of view it's not changing styles of shields/warnings so LGTM

2024-03-13 14:00 UTC, merged