Update widget tile if the url should change
matrix-org/matrix-react-sdk pull request #12381
Opened 2024-03-27 18:02 UTC by Half-Shot

The scalar token can arrive async after we've rendered a widget, which means we may need to change the URL of the app tile after this has happened. It felt reasonable to me to raise an event from the widget to the tile when this happens.

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-03-27 18:06 UTC, t3chguy requested changes
This was specifically not done as it'd kick you out of conferences/forms etc if the widget takes a param which changes, e.g. theme combined with https://github.com/matrix-org/matrix-react-sdk/pull/12295

2024-03-27 18:11 UTC, Half-Shot commented
Okay, then I think we probably need a way to raise the non-ready state so the tile isn't presented as ready until we have our URL.

2024-03-27 18:23 UTC, t3chguy reviewed
This wants a test for the scalar token & the theme variable cases

2024-04-03 10:16 UTC, richvdh commented
Moving to draft while this remains in progress

2024-09-11 17:46 UTC, closed without merging