Send user credentials to service worker for MSC3916 authentication
matrix-org/matrix-react-sdk pull request #12414
Opened 2024-04-11 22:25 UTC by turt2live

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-04-22 20:09 UTC, turt2live commented
As noted in the diff, tests for this are effectively impossible. See https://github.com/microsoft/playwright/issues/15684#issuecomment-2070862042 for a bit more detail.

2024-04-22 20:21 UTC, turt2live commented
SonarCloud appears to be complaining about code which is tested implicitly by Playwright tests. The functions have been refactored here rather than being newly introduced.

2024-04-22 21:02 UTC, turt2live commented
End to end test failure looks like a flake of some kind (cause appears unrelated to this PR's changes).

2024-04-23 12:32 UTC, richvdh requested changes
I'm slightly confused what's going on here. I see lots of factoring out to new files, which is great, but I don't think the methods are being used anywhere new? So is this just groundwork for future changes? (In other words: how does this actually help with service workers?)

2024-04-23 12:32 UTC, richvdh commented on src/utils/tokens/pickling.ts
> + * are not available, this function returns undefined regardless of input.
I think it's important to start documentation with a single-sentence summary of what the method does. Which this kinda does, but if I only read the first sentence, I'm kinda left expecting that the function will do something :sparkles:magical:sparkles: to populate the data. (Also, that first sentence should be a paragraph on its own).

Also also: surprised not to see the word "decrypt" in this description.

```suggestion
 * Decrypts the provided data into a pickle key and base64-encodes it ready for use elsewhere.
 *
 * If `data` is undefined in part or in full, returns undefined.
 *
 *  If crypto functions are not available, returns undefined regardless of input.
```

2024-04-23 12:32 UTC, richvdh commented on src/utils/tokens/pickling.ts
> + * @param data An object containing the pickle key data: encrypted payload, initialization vector (IV), and crypto key.
```suggestion
 * @param data An object containing the encrypted pickle key data: encrypted payload, initialization vector (IV), and crypto key. Typically loaded from indexedDB.
```

2024-04-23 14:08 UTC, turt2live commented on src/utils/StorageAccess.ts
> +        return self?.indexedDB ? self.indexedDB : window.indexedDB;
For reasons I have not yet been able to comprehend, this does not work. It needs to be a ternary at best. 

I'm not sure why. I agree it shouldn't matter.

2024-04-23 14:12 UTC, turt2live commented
> I'm slightly confused what's going on here. I see lots of factoring out to new files, which is great, but I don't think the methods are being used anywhere new? So is this just groundwork for future changes? (In other words: how does this actually help with service workers?)

This refactoring is for the service worker at the element-web layer. The functions are used there, and not splitting them out would mean imports which bring in half the react-sdk. Those imports include things which cannot run in a service worker, namely localstorage access. 

This PR splits out the minimum required functions to avoid bringing in stacks upon stacks of error-inducing code.

2024-04-23 14:18 UTC, richvdh commented
> This refactoring is for the service worker at the element-web layer. The functions are used there, and not splitting them out would mean imports which bring in half the react-sdk. Those imports include things which cannot run in a service worker, namely localstorage access.

Yes, I've now read https://github.com/element-hq/element-web/pull/27326. Sorry, should have checked that sooner!

2024-04-23 14:21 UTC, richvdh commented on src/utils/StorageAccess.ts
> +        return self?.indexedDB ? self.indexedDB : window.indexedDB;
[is self.indexedDB falsy but not-nullish, maybe? In which case maybe `self?.indexedDB || window.indexedDB` would do the right thing? Not that that is necessarily better than the ternary.]

2024-04-23 14:34 UTC, richvdh commented on src/utils/StorageAccess.ts
> +        return self?.indexedDB ? self.indexedDB : window.indexedDB;
`||` does not convert anything into a boolean in JS. But I agree that's not completely obvious to the casual reader, hence "Not that that is necessarily better than the ternary." I don't have a strong preference for `||` vs `?:`; I'm just musing about the problem.

2024-04-23 19:21 UTC, turt2live commented on src/utils/StorageAccess.ts
> + */
This is a copy/paste artifact. I don't think it provides value anymore - will remove.

2024-04-23 19:31 UTC, turt2live commented on src/utils/tokens/pickling.ts
> + * stored in IndexedDB).
It is the cryptographic sense: authenticated, but not encrypted. I can't really speak to *why* we do this, or if it's a good idea, but I have added a bunch of documentation around this particular area in hopes of someone else improving it.

2024-04-24 13:14 UTC, richvdh approved these changes
lgtm

2024-05-02 22:41 UTC, merged