Tooltip: Use AccessibleButton for composer & rich text editor
matrix-org/matrix-react-sdk pull request #12459
Opened 2024-04-26 14:53 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-04-30 12:36 UTC, t3chguy commented on src/components/views/rooms/MessageComposerButtons.tsx
> +                    placement="right"
Isn't this the default?

2024-04-30 12:36 UTC, t3chguy commented on src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
The changes here feel like a visual regression, can @matrix-org/design sign off on losing the keyboard key styling here?

2024-04-30 12:46 UTC, t3chguy commented on src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
Actually my bad, there's no visual regression, only an a11y one. The `kbd` elements are lost and thus also are the semantics

Before:
![image](https://github.com/matrix-org/matrix-react-sdk/assets/2403652/5c1d307d-56f6-44f0-a593-654e0d04fbb0)

2024-04-30 12:46 UTC, t3chguy requested changes
See above comments

2024-05-03 10:27 UTC, florianduros commented on src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
Good catch, will need to update the tooltip compound to be able this use case.

2024-05-15 08:53 UTC, merged