Remove code smell assrertion identified by Sonar
matrix-org/matrix-react-sdk pull request #12547
Opened 2024-05-17 18:17 UTC by EdGeraghty

This assertion is unnecessary since the receiver accepts the original…

(picked up by [SonarCloud](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=matrix-react-sdk&open=AY93Oz-hosZ_cIjsRm-v)

Signed-off-by: Ed Geraghty <ed@gergahty.family>

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-05-17 18:34 UTC, EdGeraghty commented
🤣 Playwright doesn't like that.

2024-05-20 08:44 UTC, dbkr requested changes

2024-05-20 08:44 UTC, dbkr commented on src/SlidingSyncManager.ts
> +            const clientWellKnown = await AutoDiscovery.findClientConfig(client.getDomain());
`AutoDiscovery.findClientConfig` needs a string, not null, so I think the right fix here would be to null-check `client.getDomain()` and throw an exception.

2024-05-20 17:40 UTC, EdGeraghty reviewed
Derp.

2024-05-20 18:28 UTC, EdGeraghty commented
Thanks for your help, @dbkr

2024-05-21 11:59 UTC, dbkr reviewed
Looks good otherwise though, thanks for updating it!

2024-05-21 11:59 UTC, dbkr commented on src/SlidingSyncManager.ts
> +            // client.getDomain() is null, we've thrown
`AutoDiscovery.findClientConfig ` still could have thrown though from it being invalid in a different way, so I think the comment probably needs to have both of these cases.

2024-05-21 12:26 UTC, dbkr approved these changes

2024-05-21 14:23 UTC, merged