Spotlight: don't join a public room when clicking on it
matrix-org/matrix-react-sdk pull request #12579
Opened 2024-06-05 15:07 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-06-05 15:52 UTC, t3chguy commented on src/components/views/dialogs/spotlight/SpotlightDialog.tsx
> -                        onClick={listener}
Won't this break keyboard accessibility?

2024-06-07 08:09 UTC, t3chguy requested changes
This has a very bad UX right now. The hover effect + cursor pointer makes it look clickable but clicking on it does nothing, it feels broken.

2024-06-07 08:46 UTC, t3chguy commented
Given this moves away from the designs provided to us I think we will want a design review to confirm they are happy with the new UX.

2024-07-04 09:55 UTC, gaelledel approved these changes
Thx - all good. To think about if we're willing to change the colour on Hover now or later.

2024-07-04 10:04 UTC, florianduros commented
@gaelledel the colour change should be easy, will do in the PR

2024-07-05 07:16 UTC, t3chguy requested changes
Keyboard accessibility seems broken. Enter is not working to activate the tile


https://github.com/matrix-org/matrix-react-sdk/assets/2403652/44b900f2-326a-4f54-9c77-0f8a5e3c42fc




Otherwise this does what it says on the tin but I am worried about the inconsistency in the Spotlight dialog when you switch into `Public rooms/spaces` more. Prior the whole tile is clickable, after only the button is clickable. I feel like this inconsistency is not ideal for a11y.

2024-09-11 17:45 UTC, closed without merging