SlidingSync does not work when hostet on path other than / (root)
matrix-org/matrix-react-sdk pull request #12658
Opened 2024-06-20 09:49 UTC by dreske

When sliding-sync is hostet on the same domain, but in a sub path, the url resolution will fail.

Example:
base domain: matrix.example.com
sliding-sync: matrix.example.com/sliding-sync

the URL constructur `new URL("/client/server.json", proxyUrl)` will create the url _matrix.example.com/client/server.json_ and not as required _matrix.example.com/sliding-sync/client/server.json_.

Removing the leading slash from the will solve the issue as per the documentation [https://developer.mozilla.org/en-US/docs/Web/API/URL/URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)

2024-06-20 09:51 UTC, t3chguy commented
The spec specifies the path as an absolute, so the MSC would need clarifying to allow this

2024-06-20 09:51 UTC, t3chguy requested changes
The spec specifies the path as an absolute, so the MSC would need clarifying to allow this

2024-06-20 09:56 UTC, dreske commented
This is our _https://example.com/.well-known/matrix/client_

```json
{
    "org.matrix.msc3575.proxy": {
        "url": "https://matrix.exampe.com/sliding-sync"
    }
}
```

But element is trying to load _https://matrix.exampe.com/client/server.json_ which fails because of the constructur behaviour.

2024-06-20 09:59 UTC, t3chguy commented
@dreske https://github.com/matrix-org/matrix-spec-proposals/pull/3575/files/7036c29db2b0ea40dccb0c505d6ef4b6085bf192#diff-1f7276cbbee4eeaaca06b07d2fe58312eab735259f2490e28e04710dde77fdcc

2024-06-20 10:03 UTC, dreske commented
I can't follow you.
We've used the default ansible workbook installation and that creates this configuration. Where is the error?

2024-06-20 10:18 UTC, t3chguy commented
The MSC states that the path is as such

![image](https://github.com/matrix-org/matrix-react-sdk/assets/2403652/ea3d273f-69a5-4902-98e9-7af2be7f4417)

It says nothing about it supporting being at a subpath. The ansible script letting this be configured as such is not in line with the MSC.

2024-06-25 08:30 UTC, richvdh commented
I'm rather confused.

> But element is trying to load https://matrix.exampe.com/client/server.json which fails because of the constructur behaviour.

I don't see any reference to an object called `server.json` in either the MSC (https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md) or the CS API spec (https://spec.matrix.org/v1.11/client-server-api/).

What am I missing?

2024-06-25 08:47 UTC, dreske commented
> I'm rather confused.
> 
> > But element is trying to load https://matrix.exampe.com/client/server.json which fails because of the constructur behaviour.
> 
> I don't see any reference to an object called `server.json` in either the MSC (https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md) or the CS API spec (https://spec.matrix.org/v1.11/client-server-api/).
> 
> What am I missing?

I was not talking about the MSC, but the implementation in element and the react sdk. They are loading the server.json to get the URL of the sync service.

2024-06-25 08:54 UTC, richvdh requested changes
If this endpoint isn't documented anywhere, I don't think the react-sdk should be supporting it at all.

2024-06-25 09:06 UTC, t3chguy commented
> If this endpoint isn't documented anywhere, I don't think the react-sdk should be supporting it at all.

It is a healthcheck endpoint for the sliding sync proxy for whilst the implementation on both sides is unstable

2024-09-11 17:45 UTC, closed without merging