Align RoomSummaryCard styles with Figma
matrix-org/matrix-react-sdk pull request #12793
Opened 2024-07-18 14:00 UTC by t3chguy

For https://github.com/element-hq/wat-internal/issues/166

2024-07-23 11:45 UTC, richvdh requested changes
Generally lgtm. A few nits about documentation and others.

Thanks for making the effort to help review by breaking it down into smaller commits - that definitely helped. Though I would say it feels like it could have been two PRs - one to move the extensions to a new tab, and another to do the other rearrangements to the summary card.

2024-07-24 10:33 UTC, t3chguy commented on src/components/views/right_panel/ExtensionsCard.tsx
> +            {_t("right_panel|add_integrations")}
The designs don't have such a state anymore

2024-07-24 10:33 UTC, t3chguy commented on src/components/views/right_panel/EmptyState.tsx
> +const EmptyState: React.FC<Props> = ({ Icon, title, description }) => {
Sorry this landed in a separate PR already

2024-07-24 10:33 UTC, t3chguy commented on res/css/views/right_panel/_EmptyState.pcss
> +        /* Bloom using magic numbers directly out of Figma */
Sorry this landed in a separate PR already

2024-07-24 10:34 UTC, t3chguy commented on res/css/views/right_panel/_EmptyState.pcss
> +        transform: rotate(-89.69deg);
You'd have to ask design, these are the parameters which they specified in Figma

2024-07-24 10:34 UTC, t3chguy commented on res/css/views/right_panel/_EmptyState.pcss
> +        transform: rotate(-89.69deg);
(and this already landed)

2024-07-24 10:34 UTC, t3chguy commented on res/css/views/right_panel/_EmptyState.pcss
> +        width: 642px;
This already landed and is what is specified in the designs

2024-07-24 10:35 UTC, t3chguy commented on res/css/views/right_panel/_EmptyState.pcss
> -        display: block;
Yeah sorry this PR ended up a mess as I ended up splitting out EmptyState as another PR needed it and then forgot to rebase here. Do keep meaning to try `git-absorb`, thanks

2024-07-24 13:31 UTC, t3chguy commented on src/components/structures/RightPanel.tsx
> +                if (!!this.props.room) {
Yeah went for consistency here

2024-07-24 14:11 UTC, richvdh commented on res/css/views/right_panel/_EmptyState.pcss
> +        transform: rotate(-89.69deg);
why am I wasting hours of my time reviewing things that have already landed

2024-07-24 14:14 UTC, t3chguy commented on res/css/views/right_panel/_EmptyState.pcss
> +        transform: rotate(-89.69deg);
https://github.com/matrix-org/matrix-react-sdk/pull/12793#discussion_r1689544665 has the explanation

2024-07-30 15:47 UTC, t3chguy commented
`useIsVideoRoom` split out into https://github.com/matrix-org/matrix-react-sdk/pull/12843

2024-07-30 16:23 UTC, t3chguy commented
Extensions tab split out into https://github.com/matrix-org/matrix-react-sdk/pull/12844

2024-08-01 11:53 UTC, dbkr approved these changes

2024-08-01 12:16 UTC, merged