Make widget tests throw when a modal is shown
matrix-org/matrix-react-sdk pull request #12834
Opened 2024-07-29 12:36 UTC by AndrewFerr

Instead of waiting for tests to time out if they show a dialog that they cannot interact with, throw an error immediately if a dialog is shown.

Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

2024-07-29 12:43 UTC, t3chguy requested changes
This change does not match its title. The test is not responsible for making the app fail fast

2024-07-29 12:50 UTC, t3chguy approved these changes

2024-08-08 09:07 UTC, t3chguy commented
@AndrewFerr do you need me to hit the merge button or are you able to yourself?

2024-08-08 11:44 UTC, AndrewFerr commented
> @AndrewFerr do you need me to hit the merge button or are you able to yourself?

The former, as I currently don't have write access to this repo.

2024-08-08 12:00 UTC, merged