Support do not distrub setting for platforms
matrix-org/matrix-react-sdk pull request #5097
Opened 2020-08-10 18:09 UTC by Half-Shot

Paired with https://github.com/vector-im/element-web/pull/14924

2020-08-10 20:10 UTC, t3chguy commented
This'll conflict with #5089

2020-08-24 10:56 UTC, jryans commented
I'd like to get a Product call on this before proceeding with code review. Removing from queue for now.

2020-09-29 16:30 UTC, Half-Shot commented
The failing test seems unrelated to my change?

2020-10-02 00:41 UTC, turt2live requested changes

2020-10-02 00:41 UTC, turt2live commented on src/Notifier.ts
> +
this is not needed

2020-10-02 00:41 UTC, turt2live commented on src/Notifier.ts
> +        if (!plaf) return;
this is after we already try to use it?

2020-10-02 00:41 UTC, turt2live commented on src/BasePlatform.ts
> +     * to display notifications. Otherwise false.
the booleans are in the wrong order, which is why we try to name everything with positive intent. Can we rename this to `isDisturbable` or something for positive intent?

2022-01-20 23:32 UTC, turt2live commented
@Half-Shot is this still on your radar?

2022-01-21 10:34 UTC, Half-Shot commented
As per the other PR, no :(

2022-01-21 10:34 UTC, closed without merging