Add a minimum width to the RoomView for mobile devices with narrow screens
matrix-org/matrix-react-sdk pull request #5119
Opened 2020-08-16 18:11 UTC by sirnewton01

My setup involves a PinePhone running a variant of Debian Linux. The screen is very narrow.

I have been using a user CSS file in Firefox to force a minimum width on the mx_RoomView so that it doesn't squeeze the text messages onto one word per line and make the attach file, emoji, voice, video call buttons disappear. You can see this effect even on desktop if you make your firefox window verry narrow.

With this minimum width on PinePhone there is still a bit of wasted screen real-estate on the left with the communities bar, but at least the user can scroll the whole panel right to see the full text messages in a reasonable width and access some of the less frequently used buttons like voice call, video call, members, notifications.

2020-08-17 10:02 UTC, t3chguy commented
Needs sign-off as per the contributing doc;

https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off

2020-08-17 11:52 UTC, sirnewton01 commented
Signed-off-by: Chris McGee <newton688@gmail.com>

2020-08-18 23:53 UTC, sirnewton01 commented
@t3chguy ^^^

2020-08-19 08:53 UTC, t3chguy commented
It is in the review queue.

![image](https://user-images.githubusercontent.com/2403652/90613811-c8354380-e201-11ea-9b7b-8e4d94783aed.png)

2020-08-19 10:04 UTC, jryans commented
@sirnewton01 Could you add some before and after screenshots here to help me understand what this is solving for you? We may want a different approach, but first I'd like to understand your goal a bit better.

2020-08-19 12:25 UTC, sirnewton01 commented
Thanks @jryans I have attaching a before and after screenshot that gives an idea of what this looks like on a narrow low-resolution mobile device screen. Note that the latter screenshot is scrollable to the right if the extra buttons or panels are needed. I think it's a significant improvement with this one css change. Still not ideal for mobile, but at least workable imo.

![Screenshot_2020-08-19 Element RED KNIGHT(1)](https://user-images.githubusercontent.com/3670311/90634209-5951ed80-e1f5-11ea-8081-b712bc2da4f9.png)
![Screenshot_2020-08-19 Element RED KNIGHT](https://user-images.githubusercontent.com/3670311/90634215-5b1bb100-e1f5-11ea-9eb3-d627fcdb7fc7.png)

2020-08-24 10:41 UTC, jryans requested changes
Hmm, in my testing, this does seem to do anything, because there's a separate block `.mx_MatrixChat > :not(.mx_LeftPanel):not(.mx_ResizeHandle)` with high specificity which sets `min-width: 0`. Even if you get past that, the `min-width` here causes the content to overlap into the room list area.

I think we may need to find a different approach here. What if instead you disable the community filter panel and read receipts in your preferences, to give more horizontal space for messages?

2020-08-24 14:45 UTC, sirnewton01 commented
> Hmm, in my testing, this does seem to do anything, because there's a separate block `.mx_MatrixChat > :not(.mx_LeftPanel):not(.mx_ResizeHandle)` with high specificity which sets `min-width: 0`. Even if you get past that, the `min-width` here causes the content to overlap into the room list area.

Sorry, maybe there needs to be an !important in there to make it work as I'm seeing it. I first applied this using a userContent.css from Firefox to force the view into something usable on mobile.

> I think we may need to find a different approach here. What if instead you disable the community filter panel and read receipts in your preferences, to give more horizontal space for messages?

Sure, dropping the community panel, while a bit difficult to find, especially when the screen is narrow (zoom out and tiny finger presses does seem to make this possible), it improves things slightly. Maybe one or two words per line now instead of one or just individual letters. The buttons at the top are not all accessible though and there's still a tiny area to tap to type a message.

How best to proceed here do you think?

2022-05-12 20:23 UTC, turt2live commented
Thanks for the contribution, and apologies for not getting to it sooner. It looks like this might already be fixed for the time being. Even with a very awful warning about room versions (expected - I'm playing with them in this screenshot) the timeline is still legible.

![image](https://user-images.githubusercontent.com/1190097/168161358-dcbc2963-e9aa-49dc-8763-d7dccef5f48e.png)

Now, we can obviously improve this by cutting away some of the read receipt gutter, but I believe this is on the roadmap with our new read receipts approach. 

It also appears as though I can't make the window any narrower than 500px on my machine, which helps maintain some of the layout.

If you're keen to try and tackle the read receipts issue, let us know in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org) so we can coordinate :)

2022-05-12 20:23 UTC, closed without merging