#7130  Fix forfFull screen mode scale problem
matrix-org/matrix-react-sdk pull request #5141
Opened 2020-08-24 10:58 UTC by ozanbatuhanceylan

When video call is recieved from mobile device there is a scaling problem in full screen mode. This bug is caused by full width approach to not break the aspect ratio. I changed the approach to full height. With this approach both desktop and mobile will be covered with same behaviour.

This pull request will also solve this issue [#7130](https://github.com/vector-im/element-web/issues/7130)

2020-08-24 11:03 UTC, t3chguy commented
Needs DCO sign-off as per the CONTRIBUTING doc: https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off

2020-08-24 11:13 UTC, ozanbatuhanceylan commented
I edited the pull request comment due to the CONTRIBUTING doc

2020-09-01 13:37 UTC, JorikSchellekens commented
Thanks @ozanbatuhanceylan! That massive bottom rectangle was bothering me too. Unfortunately this will cause a problem on vertical displays where a wide image may scale far too much in order to fit the full height. I think that can be avoided by filling the space and relying on `object-fit`, for example:

```
.mx_VideoView video {
  height: 100%;
  width: 100%;
  object-fit: contain;
}
```

That's pretty quick and simple to maintain but if you want to do something fancier so it fills all available space when it's a near fit but doesn't scale when it's appropriate then that's also more than welcome.

2020-09-01 13:39 UTC, JorikSchellekens requested changes
See above ^

2021-03-04 16:33 UTC, SimonBrandner commented
@jryans, the problem was fixed by [#5676](https://github.com/matrix-org/matrix-react-sdk/pull/5676)
@ozanbatuhanceylan, sorry for taking this away from you...

2021-03-05 06:53 UTC, closed without merging

2021-03-05 06:54 UTC, ozanbatuhanceylan commented
As @SimonBrandner mentioned this bug was fixed