Fix stuttering when typing in font name
matrix-org/matrix-react-sdk pull request #5150
Opened 2020-08-27 18:41 UTC by resynth1943

This fixes a major point of lag when a user changes the font used
in Element. When the "use system font" input is updated (by a
keystroke), the client updates the font, by dispatching a font
change event to the central dispatcher. One then assumes that
this changes the font family in the style sheet, as there is quite a
substantial amount of lag on every keystroke.

This commit fixes that problem, by introducing a "debounce" to the
"use system font" controller's dispatcher method. After some testing,
3000 milliseconds seemed to work the best, but that's easily changed.

Would it be a good idea to move the milliseconds outside of the
call to debounce?

Can't find any issues about this. That's surprising.

Signed-off-by: resynth1943 <resynth1943@tutanota.com>

2020-08-27 18:45 UTC, resynth1943 commented
/cc @turt2live

2020-08-27 19:28 UTC, t3chguy commented
Might be nice to have it happen immediately on Blur in that case

2020-08-28 00:51 UTC, resynth1943 commented
> Might be nice to have it happen immediately on Blur in that case

Focus blur away from the input, right?

2020-08-28 07:46 UTC, t3chguy commented
Yup

2020-08-28 17:31 UTC, resynth1943 commented
On it.

2020-09-03 14:45 UTC, jryans requested changes
Thanks for the patch! 😄 As @t3chguy suggests, let's use a blur-based approach for this.

2020-09-21 20:32 UTC, resynth1943 commented
Right I'm back. Let's take a look at this

2021-03-04 16:19 UTC, jryans commented
I believe the author is no longer engaged, so it makes sense to close this for now.

2021-03-04 16:19 UTC, closed without merging