Fix for issue #14670
matrix-org/matrix-react-sdk pull request #5300
Opened 2020-10-08 14:57 UTC by RinkiyaKeDad

Hi! I've tried to fix issue #14670 by renaming TagPanel and TagOrderStore with GroupFilterPanel and GroupFilterOrderStore in the entire codebase. Please let me know if something needs to changed. Thanks!

2020-10-08 14:59 UTC, t3chguy commented
You have multiple merge conflicts, would be great to resolve those

Also as per the contributing doc, this needs a sign-off as per https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off

2020-10-08 21:48 UTC, turt2live requested changes

2020-10-08 21:48 UTC, turt2live commented on CHANGELOG.md
> + * Remove unused GroupFilterPanelButtons
please do not change mentions in the changelog

2020-10-08 21:48 UTC, turt2live commented on src/components/structures/CustomRoomGroupFilterPanel.js
> +class CustomRoomGroupFilterPanel extends React.Component {
The `CustomRoomTagPanel` was already correctly named - it should not be modified.

2020-10-08 21:48 UTC, turt2live commented on src/settings/Settings.ts
> +    "GroupFilterPanel.enableGroupFilterPanel": {
this is a breaking change - we either need to be backwards compatible in the setting handlers or not rename the setting for now.

2020-10-10 12:37 UTC, RinkiyaKeDad commented
Opened a [new PR](https://github.com/matrix-org/matrix-react-sdk/pull/5309) to fix this.

2020-10-10 12:37 UTC, closed without merging