Replace bind by arrow functions (PasswordLogin.js)
matrix-org/matrix-react-sdk pull request #5400
Opened 2020-11-06 09:12 UTC by czeidler

The member functions `onUsernameFocus` was not bound which caused
uncaught exceptions. Use arrow functions instead to make it unnecessary
to bind member functions.

Signed-off-by: Clemens Zeidler <clemens.zeidler@gmail.com>

2020-11-09 22:34 UTC, turt2live requested changes
The first commit looks fine overall - the TypeScript conversion is incomplete. There are types missing on most functions (many of which github won't let me leave inline comments on), and the imports haven't been fixed as part of the migration (we remove instances of `getComponent()` when we do a conversion).

2020-11-09 22:34 UTC, turt2live commented on src/components/views/auth/PasswordLogin.tsx
>      static propTypes = {
We drop `propTypes` when we do the conversion.

2020-11-09 22:34 UTC, turt2live commented on src/components/views/auth/PasswordLogin.tsx
>          let phoneNumber = null;
These should get types too.

2020-11-09 22:34 UTC, turt2live commented on src/components/views/auth/PasswordLogin.tsx
> +    onUsernameChanged = (ev: any) => {
`any` is not acceptable during a conversion - it needs to be a defined type, or a comment giving a good reason why the type can't be defined.

2020-11-10 07:25 UTC, czeidler commented
There is only one implicit any left (as far as I see):

`let forgotPasswordJsx;`

but I think that is ok for this case?

Do we allow implicit any?

2020-11-23 07:29 UTC, czeidler commented
@turt2live I applied the requested changes

2020-11-23 15:31 UTC, jryans commented
It looks like @t3chguy happened to make a similar conversion in https://github.com/matrix-org/matrix-react-sdk/pull/5433 which has been merged, so this one appears to no longer be needed. Thanks for the contribution in any case, and please do look around for other areas to help out. 😄

2020-11-23 15:31 UTC, closed without merging