Add live password validation to change password dialog
matrix-org/matrix-react-sdk pull request #5436
Opened 2020-11-21 19:44 UTC by SimonBrandner

I've added live password validation to `ChangePassword.js`.

2020-11-22 09:16 UTC, SimonBrandner commented
I realized there was a bit more to be done so I added more things. This is what I've added overall:

+ Check if the new password field and confirm password field have the same values
+ Check if the old password field is empty
+ Validate on `Change password` button click

2020-11-23 16:50 UTC, t3chguy commented
Needs DCO Sign-off as per https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off

2020-11-23 18:46 UTC, SimonBrandner commented
I am sorry that I forgot the sign-off.

Signed-off-by: Šimon Brandner simon.bra.ag@gmail.com

2020-11-25 14:01 UTC, jryans commented
@SimonBrandner Can you include a video / animated GIF of the new experience? That will make it easier to review.

2020-11-25 15:07 UTC, SimonBrandner commented
@jryans Sure, here you go:

![Peek 2020-11-25 16-05](https://user-images.githubusercontent.com/25768714/100245262-22981b80-2f38-11eb-97c4-ccc257e1f399.gif)

2020-11-26 14:28 UTC, t3chguy commented on src/components/views/settings/ChangePassword.js
> +                                onBlur={() => CountlyAnalytics.instance.track("onboarding_registration_email_blur")}
this shouldn't be here, this isn't onboarding and there isn't a matching focus track

2020-11-26 14:28 UTC, t3chguy commented on src/components/views/settings/ChangePassword.js
> +                                onBlur={() => CountlyAnalytics.instance.track("onboarding_registration_email_blur")}
this shouldn't be here, this isn't onboarding and there isn't a matching focus track

2020-11-26 14:28 UTC, t3chguy commented on src/components/views/settings/ChangePassword.js
> +                                onBlur={() => CountlyAnalytics.instance.track("onboarding_registration_email_blur")}
this shouldn't be here, this isn't onboarding and there isn't a matching focus track

2020-11-26 14:29 UTC, t3chguy requested changes
Other than the spurious CountlyAnalytics tracks it looks sane. Thanks

2020-11-26 15:25 UTC, nadonomy approved these changes

2020-11-26 15:59 UTC, SimonBrandner commented
Sorry about that...

2020-11-27 13:36 UTC, t3chguy approved these changes
If you could just pull develop and re-run i18n that would be great, thanks

2020-11-27 13:54 UTC, SimonBrandner commented
@t3chguy Done

2020-11-27 14:01 UTC, merged

2020-11-27 14:01 UTC, SimonBrandner commented
Thanks

2020-11-27 14:02 UTC, t3chguy commented
No, thank you!