Add optional send message button
matrix-org/matrix-react-sdk pull request #5535
Opened 2021-01-09 08:37 UTC by SimonBrandner

This PR adds an optional send message button. It fixes [#4963](https://github.com/vector-im/element-web/issues/4963).

![Screenshot_20210109_093552](https://user-images.githubusercontent.com/25768714/104087168-1359fc80-525e-11eb-936d-a7f23b7fb6c8.png)

2021-02-05 17:40 UTC, nadonomy commented
Hey @SimonBrandner thanks for this! 

We've actually recently designed a similar change, which included some custom iconography and the icon/button changing state depending on input on the composer. Would you be ok to implement those changes? If so we can prepare assets for you next week.

2021-02-05 17:49 UTC, SimonBrandner commented
Hi @nadonomy, sure!

2021-02-10 11:13 UTC, SimonBrandner commented
@nadonomy I am wondering what's the view of the design team on [this](https://github.com/vector-im/element-web/issues/16416) (closing the emoji picker after an emoji was chosen). As this is another composer change I could include it in the PR with the other changes if you wanted.

2021-02-12 13:45 UTC, gaelledel commented
Hi @SimonBrandner,

Thank you for your inputs!
I have some specs regarding the integration of the send button in the composer. Please have a look at this Figma file for more details: https://www.figma.com/file/DFBvBKfg2sZw6YrbqOYWK6/Composer?node-id=0%3A1
We'll have a default state in which the Send button isn't visible. The second state gets activated as soon as users are typing in the composer revealing the Send button. Give me a shout if you need anything.

Cheers,
Gaelle

2021-02-12 13:48 UTC, SimonBrandner commented
Hi @gaelledel, thank you, I'll start working on this!

2021-02-12 13:51 UTC, SimonBrandner commented
@gaelledel, one question. Should I remove the setting that allows you to always hide the send button?

2021-02-12 14:33 UTC, gaelledel commented
@SimonBrandner, Yes please if you could remove this setting that would be best. Thanks a lot!

2021-02-12 15:17 UTC, SimonBrandner commented
@gaelledel, how should the button exactly behave on hover? I don't think we have any similar icon button with a background in the app to compare this to. This is how it looks out of the box:
![Screenshot_20210212_160826](https://user-images.githubusercontent.com/25768714/107785171-8d454000-6d4c-11eb-856f-9b0cd34253f9.png)

By the way, the Figma design's sizes don't match up what we have currently:
![Screenshot_20210212_161306](https://user-images.githubusercontent.com/25768714/107785701-32f8af00-6d4d-11eb-81da-9e4a403984a2.png)
![Screenshot_20210212_161235](https://user-images.githubusercontent.com/25768714/107785649-207e7580-6d4d-11eb-8f85-3825d92733b1.png)

2021-02-12 15:51 UTC, gaelledel commented
> @gaelledel, how should the button exactly behave on hover? I don't think we have any similar icon button with a background in the app to compare this to. This is what it all looks like now (I diverged from the design a bit on the size of the button):
> ![Peek 2021-02-12 16-24](https://user-images.githubusercontent.com/25768714/107787082-ed3ce600-6d4e-11eb-9c26-81cf18ca9582.gif)
> 
> If you wanted to discuss this in a more real-time fashion you can DM me (`@simon.brandner:envs.net`)
> 
> By the way, the Figma design's sizes don't match up what we have currently:
> ![Screenshot_20210212_161306](https://user-images.githubusercontent.com/25768714/107785701-32f8af00-6d4d-11eb-81da-9e4a403984a2.png)
> ![Screenshot_20210212_161235](https://user-images.githubusercontent.com/25768714/107785649-207e7580-6d4d-11eb-8f85-3825d92733b1.png)




@SimonBrandner No Problem, the button should be at 32px. We can dismiss any visual change on Hover just now.

2021-02-12 16:12 UTC, SimonBrandner commented
@gaelledel, thank you for all your help with this! PR is now ready for review

2021-02-17 11:34 UTC, jryans requested changes
Looks generally good code wise, just a small change to make.

2021-02-17 11:34 UTC, jryans commented on src/components/views/rooms/SendMessageComposer.js
> +        if (this.props.onIsEmptyChanged) {
Hmm, at the moment, I think this is actually being called on _every_ change to the composer text, not only when the empty state changes. I guess this component could maintain some internal state so it only calls `onIsEmptyChanged` for an actual empty change, or alternatively you could call the props function just `onChange` so it's clear it receives the whole model for every change.

2021-02-17 12:50 UTC, gaelledel approved these changes
All good provided the Send button has 16px padding on each side

2021-02-26 21:10 UTC, turt2live approved these changes
Looks great, thank you! Yet another PR of yours that solves something for an upcoming feature you weren't aware of 😇

2021-02-26 21:11 UTC, turt2live commented
(I'll take care of merge conflicts, considering I created them)

2021-02-26 21:41 UTC, merged