Improved language search
matrix-org/matrix-react-sdk pull request #5549
Opened 2021-01-17 09:54 UTC by 2580ayush2580

It improves the language search.

before Pull Request:-

It is searching through include method.

![s2](https://user-images.githubusercontent.com/56980422/104836968-8d7e2700-58d7-11eb-82a1-1c0e0a7b4b75.png)
After Pull Request:-

It is searching through startwith method.

![s1](https://user-images.githubusercontent.com/56980422/104836967-8bb46380-58d7-11eb-8acf-b615a8ddb238.png)

2021-01-17 10:25 UTC, SimonBrandner commented
@2580ayush2580 I am not sure if this is desirable. One of the languages is for example `Norsk Nynorsk` the user may just search for `Nynorsk` and expect to find it.

2021-01-17 10:30 UTC, SimonBrandner commented
While you are at it, you can increase the width of the search if you want. Some languages are cut off...

![Screenshot_20210117_112851](https://user-images.githubusercontent.com/25768714/104837802-31a3a600-58b7-11eb-8f8a-2c18e58948ce.png)

2021-01-17 12:01 UTC, 2580ayush2580 commented
> @2580ayush2580 I am not sure if this is desirable. One of the languages is for example `Norsk Nynorsk`. The user may just search for `Nynorsk` and expect to find it.

okay sure, I will increase the width of the search bar.

2021-01-17 13:22 UTC, 2580ayush2580 commented
done!

![s3](https://user-images.githubusercontent.com/56980422/104844232-0e97e700-58f5-11eb-8716-d1062cdfac84.png)

2021-01-17 15:01 UTC, SimonBrandner requested changes
@2580ayush2580 Could you please update the description?

Otherwise LGTM :+1:

2021-01-17 15:29 UTC, 2580ayush2580 commented on res/css/views/auth/_LanguageSelector.scss
> +    width: 160px;
If I remove this line then login page language search bar will have no width change.

![s6](https://user-images.githubusercontent.com/56980422/104847528-989c7b80-5906-11eb-9f49-2e4ae9de28c4.png)

2021-01-17 15:39 UTC, SimonBrandner commented on res/css/views/auth/_LanguageSelector.scss
> +    width: 160px;
Ok, sorry...

2021-01-17 15:40 UTC, SimonBrandner approved these changes

2021-01-28 12:56 UTC, jryans requested changes

2021-01-28 12:56 UTC, jryans commented on res/css/views/auth/_LanguageSelector.scss
> +    width: 160px;
Hmm, I don't think is quite what we want, as it means the menu is no longer centered in the column. If you can fix that up as well, then the larger widget could be okay.

2021-02-01 13:50 UTC, jryans approved these changes
Looks good to me, thanks for working on it! 😄

2021-02-01 13:50 UTC, merged