Add ConfirmDirectMessage Dialog
matrix-org/matrix-react-sdk pull request #5599
Opened 2021-01-30 22:30 UTC by 2580ayush2580

Fix [https://github.com/vector-im/element-web/issues/16300](https://github.com/vector-im/element-web/issues/16300)

2021-01-31 07:11 UTC, SimonBrandner requested changes
Otherwise LGTM to me! Thank you very much! I am pretty sure this will save my life at some point :joy: 

Also, do you plan to implement the invite reason in another PR or should I try to do it?

2021-01-31 07:11 UTC, SimonBrandner commented on src/components/views/dialogs/ConfirmDirectMessageDialog.js
> +                    {_t("Are you sure you wish to start a direct message with the ") + `${this.props.name}` + " ?"}
I don't think there should be an article before a username. So "Are you sure you wish to start a direct message with" should be enough. Also, there probably shouldn't be the space before the question mark: "?"

2021-01-31 07:11 UTC, SimonBrandner commented on src/components/views/dialogs/ConfirmDirectMessageDialog.js
> +            title={this.props.title || _t("Confirm Message")}
Maybe a different string would be better. "Confirm Direct Messages"?

2021-01-31 07:11 UTC, SimonBrandner commented on src/components/views/right_panel/UserInfo.tsx
> +    return modal.close();
I am not really sure, maybe returning `createRoom(createRoomOptions)` would be better.

2021-01-31 07:13 UTC, SimonBrandner commented on src/components/views/right_panel/UserInfo.tsx
> +    return modal.close();
It's up to you or a member of the dev team

2021-01-31 09:23 UTC, 2580ayush2580 commented
> @2580ayush2580 Also, do you plan to implement the invite reason in another PR or should I try to do it?

I don't know how it's working and currently, I am learning how it works. If you want to work  on this you may.

2021-01-31 19:08 UTC, SimonBrandner approved these changes

2021-01-31 22:52 UTC, 2580ayush2580 commented
@t3chguy @jryans Please review my PR

2021-02-01 13:57 UTC, jryans requested changes
Generally okay technically, but we'll need a Product review of this change.

2021-02-01 13:57 UTC, jryans commented on src/components/views/dialogs/ConfirmDirectMessageDialog.js
> +                    {_t("Are you sure you wish to start a direct message with ") + `${this.props.name}` + "?"}
Please use a single string for the entire sentence and string variable for the name:

```suggestion
                    {_t("Are you sure you wish to start a direct message with %(name)s?", { name: this.props.name })}
```

This way, localisers for other languages can reorder the entire sentence in any way needed.

2021-02-01 13:58 UTC, jryans commented
@2580ayush2580 Could you add a screenshot of the dialog in the top comment of the PR for easier review?

2021-02-05 14:53 UTC, nadonomy commented
@2580ayush2580 Thanks for this! I've been pouring some thought into this PR for the last couple of days and unfortunately can't merge this. As always though, you're free to maintain & run these changes in your own fork of Element.

While I empathise with https://github.com/vector-im/element-web/issues/16300 this PR puts unnecessary friction in creating DMs for everyone. The impact of this change is too great— it means new users need to confirm they'd like to direct message someone immediately after clicking on a 'Direct Message' interaction on a user profile.

The best solution (also alluded to in https://github.com/vector-im/element-web/issues/16300) would be to improve the styling of the user profile to avoid accidental clicks for all users.

Relatedly, if you do continue to use this in your own fork:

1. I'd recommend to test to ensure this isn't breaking the current implementation of opening an existing DM if it exists.
2. I'd recommend to update copy to be more terse all round— perhaps simplifying the title to 'New Direct Message' and the body copy to 'Start a new Direct Message with user'
3. The call to action button looks inconsistent with others in the app, worth double checking if there's any extraneous margin or padding.

2021-02-05 14:58 UTC, SimonBrandner commented
@nadonomy I understand the reasoning here and I agree that improving the styling is a better solution. I am just wondering what do you think about making this dialog opt-in? Something like "Require confirmation before starting a DM" could be added to the settings

2021-02-05 14:58 UTC, jryans commented
Given Nad's feedback above, let's close this, as a different approach is needed.

2021-02-05 14:58 UTC, closed without merging