ignore whitespace
matrix-org/matrix-react-sdk pull request #5623
Opened 2021-02-06 12:07 UTC by dennisroczek

for the case you copy & paste the email address you misses whitespaces. A trim is already integrated in the RegistrationForm.

2021-02-06 12:29 UTC, SimonBrandner commented
@dennisroczek, please include a sign off as described [here](https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off)

2021-02-06 13:14 UTC, dennisroczek commented
> @dennisroczek, please include a sign off as described [here](https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off)

err, I always miss the -s part :-/

2021-02-08 14:10 UTC, jryans requested changes
Hmm, I don't think we can accept as-is... There are various other components that call this same function which **do not** trim, so they would then have a confused idea of validity.

If you'd like to move forward here, I suggest visiting each component and checking how they should handle spaces.

2022-06-30 15:37 UTC, turt2live commented
@dennisroczek apologies for the delayed reply here - are you able to take a look at this still?

2022-07-05 14:52 UTC, dennisroczek commented
There was no bug report. I found the bug myself and simply tried to fix it. Sadly, haven't the time at all to do anything.

Feel free to overtake.

2022-07-05 19:17 UTC, turt2live commented
I think the testing steps for this would be to try to register an account with email, adding spaces to the end.

2022-07-06 06:54 UTC, ankur12-1610 commented
> I think the testing steps for this would be to try to register an account with email, adding spaces to the end.

Thanks, I'll do it and I'll create an issue for it first of all

2022-07-07 16:37 UTC, ankur12-1610 commented
> Would a simpler approach be to just tweak that form field in the UI so it ignores any attempts to input whitespace? As in, you press space and the field value doesn't change, you paste in a string containing spaces and the spaces get automatically removed. That should solve this issue without requiring code changes elsewhere, right? It also feels more syntactically correct in some ways; rather than accepting strings that aren't valid email addresses, we just force the input to be a valid email.

Yeah, actually I didn't get the chance to look at it, I'll look at it now.

This sounds a good idea to me I'll try to add some jquery or something like that so that even if the user enters the input it will convert it to null.

2022-07-07 16:47 UTC, turt2live commented
We don't have a jquery dependency and wouldn't really want to add one to be honest - we can just keep `trim()` on the field handling.

2022-07-08 05:11 UTC, ankur12-1610 commented
> We don't have a jquery dependency and wouldn't really want to add one to be honest - we can just keep `trim()` on the field handling.

Ok! I'll go with `trim()` then

2022-07-08 15:46 UTC, ankur12-1610 commented
I've raised the PR which solves this issue and is the continuation of this PR.
PR: #9027

2022-07-08 15:46 UTC, turt2live commented
Closing in favour of https://github.com/matrix-org/matrix-react-sdk/pull/9027

2022-07-08 15:46 UTC, closed without merging