Add mx_pollTimeout configuration option
matrix-org/matrix-react-sdk pull request #5685
Opened 2021-02-25 11:39 UTC by Half-Shot

This is mostly to alleviate the symptoms I am seeing in https://github.com/vector-im/element-web/issues/16505. This is a deliberately hidden feature as users shouldn't need to configure their poll timeout.

2021-03-01 23:44 UTC, turt2live requested changes
otherwise seems generally fine.

2021-03-01 23:44 UTC, turt2live commented on src/MatrixClientPeg.ts
> +        const pollTimeout = parseInt(localStorage.getItem("mx_pollTimeout"));
We should be using `SettingsStore` for configuration options.

2021-03-05 15:02 UTC, Half-Shot commented
Honestly, I'm not sure this solved my issue for me and it might have little value for anyone else so I wonder if I should close this. What do you think @turt2live ?

2021-03-05 15:57 UTC, turt2live commented
Up to you, if it doesn't end up helping then I'd be inclined to close it to avoid maintenance burden.

2021-03-05 18:48 UTC, closed without merging