Changed text color of highlights
matrix-org/matrix-react-sdk pull request #5724
Opened 2021-03-06 00:52 UTC by nhhollander

This is a reintroduction of the changes from #2896.

Previously this change was rejected because in the absence of a pill, it would be impossible to tell if a message was highlighted or not. Since fc3c4fccc2a3b8d6f4d7a2d737fba6cb26df014b a yellow background has been added to highlighted messages making the red text redundant. I believe this also resolves the concerns discussed in in #2896.

This should address some issues with element (and probably a few more I'm missing):
vector-im/element-web/issues/9070
vector-im/element-web/issues/13963

2021-03-06 06:25 UTC, SimonBrandner commented
@nhhollander, thanks! Could you please include a screenshot so it's easier to review to the visual side?

2021-03-07 03:39 UTC, nhhollander commented
@SimonBrandner Updated, thanks for the tip

2021-04-01 00:12 UTC, turt2live requested changes
thanks for taking a look at this! It's a very complex space to review: can we also get screenshots for what user mentions, keyword mentions, etc all look like? These are the same concerns with the previous PR.

2021-04-09 01:50 UTC, turt2live reviewed
Thanks for adding the screenshots. I gave this a quick test and found that keyword (or non-pill) notifications don't seem to work correctly, but I'm not sure that's a major issue. Keywords are incredibly hard to detect in our current notifications system, so it is likely an impossible feat to try and consider them.

This is what I mean:
![image](https://user-images.githubusercontent.com/1190097/114117225-754cf100-98a3-11eb-892a-203840a80f95.png)

The third and seventh messages are "keyword" notifications, effectively. They don't have a highlight to show what pinged the user, but the yellow background might be enough?

@matrix-org/design what are your thoughts on this? I'm fine with the code changes as-is if the caveat is acceptable.

2021-04-26 19:09 UTC, nhhollander commented
Looking at discord, it seems that in addition to the highlight, they have a solid bar of color on the left side to increase visibility. When matrix is in dark mode, the contrast from the highlight alone is pretty visible, but in light mode it gets kind of washed out. I'll give that  shot and see how it looks.

2021-07-15 18:44 UTC, nhhollander commented
It appears at first glance that this issue has been fixed (along with a bunch of other improvements) in https://github.com/matrix-org/matrix-react-sdk/pull/3553.

2021-07-15 19:33 UTC, robintown commented
@nhhollander I don't believe #3553 covered most of the changes in this PR. Messages are still entirely highlighted red when they ping you, that's just now with the exception of quoted messages in replies.

2021-07-15 19:34 UTC, nhhollander commented
Oops, looks like I misread that PR!

2021-10-04 18:13 UTC, haydenmc commented
Hi friends! Been a few months - any chance of this getting merged? Seems like low hanging fruit!

2021-10-05 07:05 UTC, nhhollander commented
@haydenmc I lost my dev environment when I moved computers, but I'll try to pull these changes with the latest release and see if it still works sometime this week. There's been loads of changes over the last few months, I haven't gotten a chance to check if there are any potentially conflicting changes.

2022-03-08 19:33 UTC, mdsina commented
Any progress on this?

2022-07-25 09:14 UTC, niquewoodhouse commented
I'd like to review this on behalf of design but can't find the view deployment option

2022-07-25 09:16 UTC, SimonBrandner commented
@nhhollander, could you please merge develop?

2022-08-17 12:26 UTC, robintown commented
I've created https://github.com/matrix-org/matrix-react-sdk/pull/9199 to replace this PR and allow the design team to take a look.

2022-08-17 12:26 UTC, closed without merging

2023-02-18 23:50 UTC, newdawncrypto commented
When will the hideous red color be removed and replaced? It's been years...

2023-02-18 23:51 UTC, turt2live commented
Please stop posting in multiple places. One comment is more than enough to get the attention of the people who can help you.