Warn on access token reveal
matrix-org/matrix-react-sdk pull request #5755
Opened 2021-03-12 05:00 UTC by aaronraimist

Fixes vector-im/element-web#15367

This is the same code from @resynth1943 in #5355, just with the merge conflicts fixed and an updated screenshot

<img width="1031" src="https://user-images.githubusercontent.com/5855073/110894450-87943900-82bd-11eb-9a59-3183a1be5215.png">

2021-03-12 11:42 UTC, jryans requested changes
A tiny thing to change code wise, otherwise looks good. Will need a Design review as well.

2021-03-12 11:42 UTC, jryans commented on src/components/views/dialogs/AccessTokenDialog.tsx
> +Copyright 2017 Vector Creations Ltd
Hmm, remove Vector here...? Seems confusing / unneeded.

2021-03-12 11:47 UTC, aaronraimist commented
Hmm apparently the re-request review button removes other existing requests? you'll have to add the design request back

2021-03-12 11:48 UTC, SimonBrandner commented
@aaronraimist, yep, it seems to be a common GitHub bug....

2021-03-12 17:44 UTC, jryans approved these changes

2021-04-15 18:13 UTC, niquewoodhouse commented
Thanks @aaronraimist I notice the previous version already had design feedback, the only comment being to change the body copy.  And @nadonomy has way more familiarity with these areas than I do.

So I'm tempted to just approve it because it's a good iteration but I have a couple of additional notes.  I welcome your opinions on these notes, I'm not too familiar with the users who are likely to interact with this, or why someone would, so please share your thoughts.  I also don't know the effort required to do them.

**Notes**
- I wondered if keeping the `<click to reveal>` made sense, and changing it to `<click to hide>` to enable hiding after it's been shown.  It's just we're now saying this is a really important thing, don't share it, and then there's no visual way to hide it.   I think _some_ people might get a bit concerned by that, and would be re-assured they can hide it again.  If that's easy, it seems a simple iteration to make this a bit more friendly if non-technical people ever need to do this.

- My final note was about the button, I don't quite get why the button is red, it's not an error?  I can see for security flows there's a few times there's red buttons used for primary actions so maybe it's the right thing to do for security flows (@jryans do you know if that's true) but my personal bias says it makes it hard to know what to do.  My second point on the button is "Ok" might not be the right copy for the primary action, "reveal access token" or "reveal" or "reveal token"  or "show access token".  They just feel a bit more accurate as to what's happening next, whereas "Ok" just sounds like "Understood".


Thanks

2021-04-20 20:52 UTC, aaronraimist commented
@niquewoodhouse right now the access token is hidden again when you navigate away from the Help & About section of settings. When you come back it will be hidden.

How about we just simplify this a bit and remove the dialog box and the custom click to hide/reveal button and make the access token hidden behind a standard [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element. Something like this:

<details>
    <summary>Access Token</summary>
    <b>Your access token gives full access to your account. Do not share it with anyone.</b>  

   MDA123ABC...
</details>

2021-04-22 16:05 UTC, niquewoodhouse commented
@aaronraimist I really really like that!  You wierdly read my mind - I wanted to propose this as the change originally, but felt there had already been lots of good done so didn't want to suggest undoing a lot of it.  

I noticed there's already some UI for expanding/collapsing in settings, under appearance.

![image](https://user-images.githubusercontent.com/1587166/115744397-72b1c780-a38a-11eb-88a2-a8c2e094ce94.png)

And there's these in security and privacy.

![image](https://user-images.githubusercontent.com/1587166/115746595-5c0c7000-a38c-11eb-9597-c2a12ec39c13.png)

I prefer the ones in security and privacy, they look more like the proposal and reflect the room list sections.

Thanks for coming back with this.

2021-04-28 00:37 UTC, aaronraimist commented
Okay I think this is ready to go. Here is what it looks like now:

Collapsed:
<img width="305" src="https://user-images.githubusercontent.com/5855073/116328836-83e64400-a78f-11eb-9ba9-921c20821ab0.png">

Expanded:
<img width="667" src="https://user-images.githubusercontent.com/5855073/116328934-bd1eb400-a78f-11eb-84aa-58482f91ecb7.png">

2021-04-28 00:38 UTC, aaronraimist commented
(someone will need to re-request design review)

2021-04-28 15:08 UTC, jryans approved these changes
Looks good to me code wise, thanks! 😄

2021-04-30 09:14 UTC, niquewoodhouse commented
That's so much better, thank you.

- Couldn't tell if this is a netlify thing, or my browser but, after I copy the field, the copied! text remains when I leave the settings and go to other areas in Element.  Maybe it's just a thing with the copy field component but just raising in case its not.

![image](https://user-images.githubusercontent.com/1587166/116673495-5ff74e00-a99b-11eb-8d90-389e320fab94.png)

- Quick win: It would be nice if we could bold the following sentences.  `Your access token gives full access to your account. Do not share it with anyone.`  Otherwise this warning is quite muted and can go unseen.  There is some precedence in settings for bolding key information, such as your identity server.

Thank you again

2021-05-01 02:51 UTC, aaronraimist commented
@niquewoodhouse Before it was only closing the tooltip if you moved your mouse. It should now close the tooltip if you close the settings screen in some other way such as pressing escape. Let me know if it closes for you now.

2021-05-04 10:22 UTC, niquewoodhouse approved these changes
Thanks for this, works great and is much better.

2021-05-05 15:32 UTC, jryans approved these changes
Looks good, thanks for working on this! 😄

2021-05-05 15:32 UTC, merged