fix password change popup message
matrix-org/matrix-react-sdk pull request #5791
Opened 2021-03-25 13:05 UTC by thermaq

Fixed bad error message when providing bad old password during password change.

2021-03-25 13:17 UTC, t3chguy commented
Needs DCO sign-off as per https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off

2021-03-26 01:10 UTC, turt2live requested changes
The code looks to do something, but we need a bit of information in the PR description for what the broken behaviour is, what the new behaviour looks like, and what sorts of errors we expect to surface now.

If you have an issue link, that would be great to add as well.

2021-03-26 06:04 UTC, thermaq commented
> The code looks to do something, but we need a bit of information in the PR description for what the broken behaviour is, what the new behaviour looks like, and what sorts of errors we expect to surface now.
> 
> If you have an issue link, that would be great to add as well.

Added explanations in the description

2021-03-26 06:07 UTC, turt2live approved these changes
Thanks!

2021-03-26 06:07 UTC, merged