Improve message editing UI
matrix-org/matrix-react-sdk pull request #5876
Opened 2021-04-16 14:37 UTC by SimonBrandner

2021-05-11 02:00 UTC, turt2live requested changes
Overall the code looks fine, just a few small lint/maintenance concerns

2021-05-11 02:00 UTC, turt2live commented on res/css/views/rooms/_EditMessageComposer.scss
> +    position: absolute;
it's not immediately obvious what this will be relative to - a quick comment would be appreciated.

2021-05-11 05:42 UTC, SimonBrandner commented
Oops, the design review missing as usual...

2021-05-15 01:33 UTC, turt2live approved these changes
Thanks!

2022-05-12 10:27 UTC, closed without merging