Lazily decrypt events on room view
matrix-org/matrix-react-sdk pull request #5980
Opened 2021-05-06 11:34 UTC by gsouquet

View matrix-org/matrix-js-sdk#1684

2021-05-07 14:52 UTC, jryans commented on src/stores/BreadcrumbsStore.ts
> +        const breadcrumbs = client.store.getAccountData("im.vector.setting.breadcrumbs");
Hmm, it feels a bit strange to go directly to the account data here when the main purpose of this store is reading and tracking the breadcrumbs anyway... 

Maybe it fit a bit better in `updateRooms`, and you could check for the case of transitioning from no rooms to some rooms, so it only fires once...?

2021-05-07 15:13 UTC, jryans commented
As discussed, I expect we'll need to tweak the event indexer as well, but anyway you're already looking into that. 😄

2021-05-10 14:32 UTC, gsouquet commented on src/components/structures/TimelinePanel.js
> +
Removed, and also tracked it here https://github.com/vector-im/element-web/issues/17232

2021-05-11 01:25 UTC, turt2live requested changes
I am mostly being a nitpick linter here: the code looks fine, just a bunch of small things about the style.

2021-05-11 01:25 UTC, turt2live commented on src/components/structures/TimelinePanel.js
> +        // `slice` performs a shallow copy of the array
`arrayFastClone` when you're in this layer please, so we can always keep the most performant option readily available

2021-05-11 01:25 UTC, turt2live commented on src/indexing/EventIndex.js
> +            await ev._decryptionPromise;
should get an `XXX: Private member access` to acknowledge the danger

2021-05-11 01:25 UTC, turt2live commented on src/indexing/EventIndex.js
> +                        return event._decryptionPromise;
maintain the private member access warning, or expose properly

2021-05-11 01:25 UTC, turt2live commented on src/stores/BreadcrumbsStore.ts
> +import {MatrixClientPeg} from '../MatrixClientPeg';
match brace styles please:
```suggestion
import { MatrixClientPeg } from '../MatrixClientPeg';
```

2021-05-11 01:25 UTC, turt2live commented on src/stores/BreadcrumbsStore.ts
> +                        await client._crypto.onCryptoEvent(cryptoEvent);
I thought we exposed this properly? If not, should either be exposed or acknowledged as private member access

2021-05-12 03:46 UTC, turt2live approved these changes
thank you for your patience with the human linter :)

2021-05-12 11:19 UTC, merged