EventTilePreview fixes
matrix-org/matrix-react-sdk pull request #6000
Opened 2021-05-09 01:26 UTC by robintown

Just a couple of things I noticed while referencing EventTilePreview code for #5999. (see commits)

2021-05-09 01:31 UTC, robintown commented
Also, PR 6000 ;)

2021-05-11 01:14 UTC, turt2live requested changes
otherwise looks sane, but we do need a comment of some kind for why we'd be dropping to a lower avatar size (risking blurry images)

2021-05-11 01:14 UTC, turt2live commented on src/components/views/elements/EventTilePreview.tsx
> +const AVATAR_SIZE = 30;
why?

2021-06-06 02:23 UTC, robintown commented
Reverted the thumbnail size change as I wasn't aware that 32 is just the value that's used everywhere. This should just be the one bug fix for when the user doesn't have a display name, then

2021-06-07 23:08 UTC, robintown commented
Also removed the mystery dot added by #6154

![settings](https://user-images.githubusercontent.com/48614497/121098366-b5592300-c7c3-11eb-8fac-1e765dda165b.png)

2021-06-22 19:56 UTC, turt2live approved these changes
Thank you! Apologies for the super delayed turnaround time on this...

2021-06-22 19:57 UTC, merged