Show a gray shield when encrypted by deleted session
matrix-org/matrix-react-sdk pull request #6119
Opened 2021-05-29 11:31 UTC by SimonBrandner

Fixes [#13701](https://github.com/vector-im/element-web/issues/13701)

Before:
![Screenshot_20210529_133101](https://user-images.githubusercontent.com/25768714/120068659-1ecd8900-c082-11eb-8496-80955cf89034.png)

After:
![Screenshot_20210529_132910](https://user-images.githubusercontent.com/25768714/120068619-dca44780-c081-11eb-954d-ec512464f086.png)

2021-05-29 13:45 UTC, robintown commented
Shouldn't the icon be `e2e/normal.svg` if it's gray?

2021-05-29 13:46 UTC, SimonBrandner commented
> Shouldn't the icon be `e2e/normal.svg` if it's gray?

I am not really sure what is the best thing I can do here..

2021-05-29 13:53 UTC, robintown commented
Well, it would be in line with how messages appear when their authenticity cannot be verified (and I'm pretty sure that "encrypted by a deleted session" mostly means the same thing)

2021-05-29 15:44 UTC, SimonBrandner commented on res/css/views/rooms/_EventTile.scss
>          mask-image: url('$(res)/img/e2e/warning.svg');
```suggestion
        mask-image: url('$(res)/img/e2e/normal.svg');
```

2021-06-07 09:41 UTC, harmathy commented
I could live with this solution as a fix for [#13701](https://github.com/vector-im/element-web/issues/13701)!

2021-06-10 12:27 UTC, jryans requested changes
Looks fine code wise, but this is really a Product choice here on how much to scream about this case.

2021-06-10 12:27 UTC, jryans commented on res/css/views/rooms/_EventTile.scss
>  .mx_EventTile_e2eIcon_unknown {
While we're here, let's consolidate the blocks, joining the selectors that use the same values. It looks like there's only normal or warning images, so we should only need two blocks.

2021-06-14 14:58 UTC, jryans approved these changes
Thanks, looks great code wise, so now we need Design input.

2021-11-01 17:17 UTC, amshakal commented
Sorry it took me a while get to this. I think this is a reasonable solution.

Overall I think we could a better job of explaining to the user what's going on, what it means for them and what they need to do to resolve a specific encryption related issue in layperson terms but I think that's out of scope for this PR. :D

2021-11-01 17:28 UTC, merged

2022-04-25 16:38 UTC, FernOfEdison commented
I think the grey shield is an issue for deleted and unverified sessions.

For sessions that were **unverified and deleted**, the grey shield with "_Encrypted by a deleted session_" still shows. This should not be the case as the source is unverified.

2023-09-20 16:45 UTC, richvdh commented
Worth noting we'll be going back to red shields here as part of the change to Element-R (https://github.com/vector-im/element-web/issues/21972)