[WIP] Add VoIP event tiles
matrix-org/matrix-react-sdk pull request #6121
Opened 2021-05-30 17:49 UTC by SimonBrandner

![Screenshot_20210530_194627](https://user-images.githubusercontent.com/25768714/120114503-ba90ef00-c17f-11eb-8693-8a7e69d105a2.png)

<hr></hr>

+ [ ] Find fixes
+ [ ] Delete leftovers

2021-06-03 17:56 UTC, dbkr approved these changes
some very minor feedback, otherwise looks 100% amazing: thank you!

Will prod design for signoff.

2021-06-03 17:56 UTC, dbkr commented on src/CallHandler.tsx
> +        }
probably worth a `return null;` here just to avoid surprise `undefined`s

2021-06-03 17:56 UTC, dbkr commented on src/components/views/messages/CallEvent.tsx
> +        // XXX: Should we translate this?
Yeah, probably

2021-06-04 06:20 UTC, SimonBrandner commented
/me sometimes loves Github - could someone please re-request the design review...

2021-06-04 10:10 UTC, dbkr approved these changes

2021-06-17 09:08 UTC, gaelledel requested changes
It seems there are padding issues and colours do not match designs. Could you reffer to the Design specs here? https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=2863%3A45199

2021-06-19 18:05 UTC, SimonBrandner commented
Since https://github.com/matrix-org/matrix-react-sdk/pull/6082 is now merged, I also implemented call silencing here:

![Screenshot_20210619_200459](https://user-images.githubusercontent.com/25768714/122651518-ad8d6d00-d139-11eb-9579-b6074201ee9a.png)

2021-07-08 11:29 UTC, gaelledel commented
@SimonBrandner 
Thanks for the updates!
I can see a few UI issues here and there otherwise it's great thank you:

- [ ] The buttons on the call tiles are stuck together and need more padding
<img width="1411" alt="Screenshot 2021-07-08 at 11 24 43" src="https://user-images.githubusercontent.com/76945183/124913859-8b279a80-dfe7-11eb-8c8f-a23f2333805c.png">

- [ ] The silence ringtone icon seems too light
- [ ] Unsure if part of this PR or if there is any but it'd be great if we could move the call notification on the top left corner of the UI where other notifications are?
- [ ] The icons on the buttons and the call notification are missing
- [ ] Same issue on Dark theme
<img width="1400" alt="Screenshot 2021-07-08 at 11 22 25" src="https://user-images.githubusercontent.com/76945183/124914051-c924be80-dfe7-11eb-860f-1fd3f2255e1e.png">

- [ ] I also noticed that the silence functionality isn't always working

2021-07-08 14:37 UTC, SimonBrandner commented
For context: incoming call box issues were split out into https://github.com/vector-im/element-web/issues/17912

2021-07-08 14:46 UTC, gaelledel approved these changes

2021-07-08 14:47 UTC, SimonBrandner commented
Re-requested code review as quite a few things changed from the last one

2021-07-20 12:19 UTC, tulir commented on res/css/views/rooms/_EventTile.scss
> +            background-color: inherit !important;
This seems to break all highlighting of events now

2021-07-20 12:29 UTC, dbkr approved these changes

2021-07-20 12:31 UTC, merged