Add dialpad to transfer dialog + various dialpad UI improvements
matrix-org/matrix-react-sdk pull request #6363
Opened 2021-07-13 11:12 UTC by anoadragon453

This PR simply merges the feature branch `feature/transfer_dialpad_improvements` to develop. This branch is the combination of PRs #6217, #6301, #6325 and #6338, which have already been independently reviewed.

See each linked PR for the details, but the high-level summary is that the call transfer dialog now has a built in dial pad for transferring a call to a number you can dial:

![image](https://user-images.githubusercontent.com/1342360/125442214-6f0d3f97-0e03-407e-b0de-e44bcadfa812.png)

as well as various improvements to the dial pad itself such as better sizing, letters under the buttons and a better-placed backspace button:

![image](https://user-images.githubusercontent.com/1342360/125442327-3391e05b-5d44-485b-ad69-be5edc562de2.png)

Design by @gaelledel, implementation by @dbkr and myself.

`Signed-off-by: Andrew Morgan <andrewm@element.io>`

2021-07-13 11:30 UTC, gsouquet requested changes
Mainly looks good to me! Thank you for working on that

Before merging that in `develop` could you extract all the hardcoded colour into `_dark.scss`, `_legacy-dark.scss`, `_light.scss` and `_legacy-dark.scss`

2021-07-13 11:30 UTC, gsouquet commented on res/css/views/dialogs/_InviteDialog.scss
> +    border-color: #6F7882;
We might want to put that one in a variable, and check whether it needs to be different for the light and dark theme

2021-07-13 11:30 UTC, gsouquet commented on res/css/views/dialogs/_InviteDialog.scss
> +    border-color: #0DBD8B;
Same comment about putting this value in a variable

2021-07-13 11:30 UTC, gsouquet commented on res/css/views/elements/_DialPadBackspaceButton.scss
> +        background-color: #8D97A5;
Should be in a variable

2021-07-13 11:30 UTC, gsouquet commented on res/css/views/elements/_DialPadBackspaceButton.scss
> +        height: 28px;
To avoid duplication you can use `inherit` here
```suggestion
        width: inherit;
        height: inherit;
```

2021-07-13 11:30 UTC, gsouquet commented on res/css/views/voip/_DialPadContextMenu.scss
> +    border-bottom: 1px solid #6F7882;
To put in a variable

2021-07-13 11:31 UTC, jryans commented
@anoadragon453 Did a design review already happen? I did not notice a green check from @gaelledel on the other PRs...

2021-07-13 15:40 UTC, anoadragon453 commented
@jryans yes, it was reviewed at the end of the work in https://github.com/matrix-org/matrix-react-sdk/pull/6338.

2021-07-13 16:22 UTC, anoadragon453 commented
Thanks for the review @gsouquet. It turns out all of those colours were already variables :sweat_smile:. I noticed a few more instances of `#6F7882` being hardcoded in `_legacy-dark.scss` as well, though the colour is only officially named in `_dark.scss`:

https://github.com/matrix-org/matrix-react-sdk/blob/9ce041a47a3c5ce8da702da3a988e1b8f36432b5/res/themes/dark/css/_dark.scss#L12

https://github.com/matrix-org/matrix-react-sdk/blob/9ce041a47a3c5ce8da702da3a988e1b8f36432b5/res/themes/legacy-dark/css/_legacy-dark.scss#L214-L216

1. Would we use variables from `_dark.scss` in legacy-dark.scss and if so,
2. Do you want to fix that up? Either in this PR or a separate one?

2021-07-14 06:48 UTC, gsouquet commented
As far as I understand `_dark.scss` and `_legacy-dark.scss` are two separate things and the latter is used independently in some hardened Element themes.
If you can fix it as part of this PR that is great, but I do not want to needlessly block you from getting that PR across

2021-07-14 06:50 UTC, t3chguy commented
> the latter is used independently in some hardened Element themes.

Actually is the based for all custom themes, not at all exclusive to Hardened Element https://github.com/vector-im/element-web/blob/develop/docs/theming.md#custom-themes https://github.com/aaronraimist/element-themes

2021-07-14 14:06 UTC, anoadragon453 commented
@gsouquet I think we should move this fix to another PR as we have a customer waiting on this PR landing.

But thanks for the information both!

2021-07-15 06:58 UTC, gsouquet approved these changes

2021-07-15 08:55 UTC, merged