Go to space landing page when clicking on a selected space
matrix-org/matrix-react-sdk pull request #6442
Opened 2021-07-22 12:15 UTC by robintown

Context for design: In the spaces feedback room, Matthew raised the point that the explore rooms page still feels a bit too hidden and difficult to get to. My proposed solution, which this implements, was to make clicking on a space that's already selected pull up the explore rooms page. This also changes the home/all rooms space to take you to the Ctrl+Alt+H landing page if it's already selected.

2021-07-22 13:14 UTC, gsouquet approved these changes
That makes sense code-wise. 
Waiting on product feedback whether we want to enable that behaviour

2022-05-10 13:19 UTC, niquewoodhouse commented
I know its listed as needing product to review it, but just to say I find this a little confusing when I have `People` or `Favourites` selected, it just goes to my Home

2022-05-10 13:22 UTC, robintown commented
I may end up removing the 'metaspace -> home' behavior entirely given the work that Delight is now doing in this area

2022-05-11 09:11 UTC, kittykat requested changes
From a product POV: Danielle, Nique and I discussed this and we feel it should apply only to real spaces (not metaspaces). Otherwise, looks good.

2022-05-11 21:09 UTC, kittykat commented
Found this issue when testing: https://github.com/vector-im/element-web/issues/22156

I experience it on develop as well, but I can't test the build properly until it's resolved :(

2022-05-16 21:43 UTC, kittykat approved these changes
LGTM

2022-05-16 21:44 UTC, robintown commented
Requesting re-review from the team since it's been a while

2022-05-17 09:39 UTC, t3chguy approved these changes
LGTM otherwise

2022-05-17 09:39 UTC, t3chguy commented on src/components/views/spaces/SpaceTreeLevel.tsx
> +        : () => SpaceStore.instance.setActiveSpace(spaceKey ?? space.roomId));
this is a little difficult to read, can we break it up?

2022-05-17 13:22 UTC, merged