Fix call events layout for message bubble
matrix-org/matrix-react-sdk pull request #6465
Opened 2021-07-23 13:16 UTC by gsouquet

Fixes vector-im/element-web#18144

2021-07-23 15:09 UTC, SimonBrandner requested changes
![Screenshot_20210723_170730](https://user-images.githubusercontent.com/25768714/126802150-471bf1c4-9156-40b4-abdc-e7b9d314f093.png)

This doesn't seem to be really solving the issue for me :thinking: The call event tiles should probably span over a big part of the timeline.

2021-07-26 07:16 UTC, gsouquet commented on res/css/views/rooms/_EventBubbleTile.scss
> +        .mx_EventTile_info {
```suggestion
        .mx_EventTile_line,
        .mx_EventTile_info {
```

2021-07-26 07:28 UTC, gsouquet commented
> This doesn't seem to be really solving the issue for me 🤔 The call event tiles should probably span over a big part of the timeline.

Looks like different replies have different DOM structures, I added an extra selector that does seem to help here!

2021-07-26 07:37 UTC, SimonBrandner commented
@gsouquet, I think that if you change 

https://github.com/matrix-org/matrix-react-sdk/blob/dbe24fab70bcebdc789a0f8a9865db28339d6203/res/css/views/messages/_CallEvent.scss#L26 

to 

```
width: 75%; 
```

We should actually achieve the effect of the tiles having the same width

2021-07-26 07:43 UTC, SimonBrandner approved these changes
Thank you!

2021-07-30 01:50 UTC, turt2live approved these changes
Screenshots in the PR description are appreciated for these sorts of changes to aide review and to be a reference point down the line when we're trying to debug why it broke or where it broke.

Please include screenshots :)

2021-07-30 07:08 UTC, gsouquet commented
Thank you for the review, this fixes a regression and does not bring any new feature nor changes in design

<img width="557" alt="Screen Shot 2021-07-30 at 09 07 59" src="https://user-images.githubusercontent.com/769871/127614745-67a845f7-58bb-45c1-b0ad-669ad74f1321.png">

2021-07-30 08:07 UTC, merged