Spaces let users switch between Home and All Rooms behaviours
matrix-org/matrix-react-sdk pull request #6497
Opened 2021-07-28 16:42 UTC by t3chguy

Makes it so that a page reload is no longer required and takes them out of the feature/labs/beta namespace. It will mean the option is reset for users and the default has also changed.

Fixes https://github.com/vector-im/element-web/issues/18093

![image](https://user-images.githubusercontent.com/2403652/127362479-d086e79d-c511-4d0d-ae65-861813d21661.png)
![image](https://user-images.githubusercontent.com/2403652/127362500-54995992-5912-4199-8a5c-16b5375bae0c.png)
![image](https://user-images.githubusercontent.com/2403652/127362523-11bc58ef-6fe3-40b9-afae-3a10fce1ea8f.png)

https://user-images.githubusercontent.com/2403652/127362571-a36fff09-839c-4649-8f41-a999ea2c2efc.mov

2021-07-28 18:16 UTC, niquewoodhouse requested changes
This is much better for the user than what I was originally thinking - a link to Preferences in settings.

Some small comments 

- Name of 'Space' should always be Home, whatever preferences are selected (the icon is a house, and that's just an option within the...house)
- Text could be 'show all rooms' (don't think you need the 'in Home', given the context
- I'm not personally convinced of the settings icon.  It might be because I personally think the context menu design puts too much emphasis on the icons to the left, but it just kind of sticks out as random? Or is that just me?  Any ideas of something better?  I was thinking the hash icon for 'rooms' might make more sense, but that's used in places already....so maybe it's not that good, but it would copy the "favourite" item on each room's context menu.

2021-07-28 18:22 UTC, t3chguy commented
> Name of 'Space' should always be Home, whatever preferences are selected (the icon is a house, and that's just an option within the...house)

This should already be the case

> Text could be 'show all rooms' (don't think you need the 'in Home', given the context

Will change

> I was thinking the hash icon for 'rooms' might make more sense, but that's used in places already....so maybe it's not that good, but it would copy the "favourite" item on each room's context menu.

Will change

2021-07-28 18:24 UTC, nadonomy commented
> I'm not personally convinced of the settings icon. It might be because I personally think the context menu design puts too much emphasis on the icons to the left, but it just kind of sticks out as random? Or is that just me? Any ideas of something better? I was thinking the hash icon for 'rooms' might make more sense, but that's used in places already....so maybe it's not that good, but it would copy the "favourite" item on each room's context menu.

@niquewoodhouse Agree! I wonder if we could reduce to no icon and just simply 'Show all rooms'?

2021-07-28 18:28 UTC, niquewoodhouse commented
> @niquewoodhouse Agree! I wonder if we could reduce to no icon and just simply 'Show all rooms'?

I'm not sure if the component can handle having no icon - @t3chguy?

2021-07-28 18:33 UTC, t3chguy commented
It is called the IconizedContextMenu but I can provide it an iconClass which does magic

![image](https://user-images.githubusercontent.com/2403652/127377064-fcb2e940-f908-4d8d-b78e-e6ca79fc52ab.png)


Have just pushed the above

2021-07-28 18:37 UTC, niquewoodhouse approved these changes

2021-07-30 01:49 UTC, turt2live approved these changes
otherwise lgtm

2021-07-30 01:49 UTC, turt2live commented on src/settings/Settings.tsx
> +    "Spaces.all_rooms_in_home": {
the naming scheme for dotted settings is `Spaces.allRoomsInHome` - there used to be a style note somewhere in this file, but that seems to have gone missing.

2021-07-30 11:25 UTC, merged