Show simple file name and size on image & video thumbnails
matrix-org/matrix-react-sdk pull request #6511
Opened 2021-07-30 01:33 UTC by turt2live

Fixes https://github.com/vector-im/element-web/issues/18197

This is very much developer design at the moment, but has been tested on a couple different types of media I had laying around:
![image](https://user-images.githubusercontent.com/1190097/127586432-c76300b7-6461-47bf-bd23-58358b034fb7.png)

2021-07-30 07:14 UTC, gsouquet approved these changes
Looks good to me 👏

2021-07-30 08:02 UTC, Portt56 approved these changes

2021-07-30 08:08 UTC, SimonBrandner requested changes
Could a border radius please be added so that it matches the image border radius?

2021-07-30 13:46 UTC, turt2live commented
@SimonBrandner which border radius specifically? There's already a border radius in the PR.

2021-07-30 14:38 UTC, SimonBrandner commented
> @SimonBrandner which border radius specifically? There's already a border radius in the PR.

I meant giving the title a bottom-right radius, though it might already be there and I might be blind

2021-07-30 14:43 UTC, turt2live commented
The bottom right is somewhat deliberately not included to avoid a trapezoid feel, though maybe the design team has thoughts :)

2021-07-30 17:03 UTC, robintown commented
I feel like this would frequently get in the way of seeing images, especially smaller ones. Just a suggestion, but could it be something that appears on hover?

2021-08-01 13:46 UTC, DoM1niC commented
Reply a bit buggy ??? :D 
![image](https://user-images.githubusercontent.com/1436958/127773151-cec17210-8d08-474e-a4ad-712fda7d97a2.png)

2021-08-01 13:47 UTC, SimonBrandner commented
> Reply a bit buggy ??? :D 
> ![image](https://user-images.githubusercontent.com/1436958/127773151-cec17210-8d08-474e-a4ad-712fda7d97a2.png)
> 

Yeah, should be hidden for replies as we already show the name on the right of the image

2021-08-01 13:57 UTC, ShadowJonathan commented
Shouldn't this only show up when the mouse is hovering over the image?

2021-08-01 13:58 UTC, SimonBrandner commented
> Shouldn't this only show up when the mouse is hovering over the image?

See https://github.com/matrix-org/matrix-react-sdk/pull/6511#issuecomment-890029883

2021-08-18 13:07 UTC, robintown commented
Also fixes https://github.com/vector-im/element-web/issues/18611

2021-11-20 18:15 UTC, DoM1niC commented
Avatar images don't to show 

```
rageshake.ts:65 TypeError: Cannot read property 'getContent' of undefined
    at O.render (ImageView.tsx:545)
    at qa (react-dom.production.min.js:187)
    at Ga (react-dom.production.min.js:186)
    at qs (react-dom.production.min.js:269)
    at Sc (react-dom.production.min.js:250)
    at yc (react-dom.production.min.js:250)
    at vc (react-dom.production.min.js:250)
    at pc (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

2022-05-13 15:24 UTC, t3chguy commented on src/components/views/messages/MImageBody.tsx
> +        const isTimeline = !this.props.tileShape
The FilePanel has the name + size already printed below the image

2022-05-14 08:31 UTC, SimonBrandner approved these changes
Otherwise LGTM!

2022-05-14 08:31 UTC, SimonBrandner commented on src/components/views/messages/MImageBody.tsx
> +        ].includes(this.context.timelineRenderingType);
Is this trying to make sure we don't show the banner in the file panel or something else? Perhaps a comment would help here to be a little more explicit about why are we doing this

2022-05-14 08:31 UTC, merged