First cleanup of the theme files
matrix-org/matrix-react-sdk pull request #6540
Opened 2021-08-04 08:13 UTC by SimonBrandner

This pull request adds the colours from Figma and uses them inside the theme files where possible. It should be reviewable commit-by-commit

<hr>

element-web notes: none

2021-08-04 08:40 UTC, SimonBrandner commented
CI fails should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6541

2021-08-04 14:03 UTC, Palid commented
@janogarcia could you look at that to double-check we got everything right?

2021-08-05 21:45 UTC, turt2live requested changes
overall this is probably fine, but I'm a little concerned about where/how the variables are used.

2021-08-05 21:45 UTC, turt2live commented on res/themes/dark/css/_dark.scss
> +$message-body-panel-bg-color: $quinary-content; // "Dark Tile"
we can remove the comment

2021-08-05 21:45 UTC, turt2live commented on res/themes/light/css/_light.scss
> +$username-variant3-color: $accent;
This is an incorrect usage of the variable

2021-08-05 21:45 UTC, turt2live commented on res/themes/dark/css/_dark.scss
> +$avatar-initial-color: $primary-content;
This is an incorrect usage of the variable

2021-08-05 21:45 UTC, turt2live commented on res/themes/light/css/_light.scss
> +$lightbox-fg-color: $background;
This doesn't feel right: I think we're trying to hardcode the image view styles, not make them variable.

2021-08-05 21:45 UTC, turt2live commented on res/themes/light/css/_light.scss
> +$button-primary-fg-color: $background;
There's just something wrong about setting a foreground colour to a background colour. We should fix the variable naming so it reads less insane throughout.

2021-08-05 21:45 UTC, turt2live commented on res/themes/light/css/_light.scss
> +$message-body-panel-bg-color: $quinary-content; // "Separator"
Comment can go

2021-08-05 21:45 UTC, turt2live commented on res/themes/light/css/_light.scss
> +$voice-record-stop-border-color: $quinary-content; // "Separator"
Comment can go

2021-08-06 15:33 UTC, turt2live approved these changes
Looks good! Out of an abundance of caution, I'm going to block this on the RC happening: it's uncomfortably close to the end of the cycle for such a visual change.

2021-08-11 16:55 UTC, merged