Migrate components to TypeScript
matrix-org/matrix-react-sdk pull request #6619
Opened 2021-08-16 08:16 UTC by gsouquet

- Migrate JumpToBottomButton to TypeScript
- Migrate ReadReceiptMarker to TypeScript
- Migrate RoomDetailList to TypeScript
- Migrate RoomUpgradeWarningBar to TypeScript
- Migrate SimpleRoomHeader to TypeScript
- Migrate TopUnreadMessagesBar to TypeScript
- Migrate AvatarSetting to TypeScript
- Migrate ChangeAvatar to TypeScript
- Migrate ChangeDisplayName to TypeScript
- Migrate DevicesPanel to TypeScript
- Migrate DevicesPanelEntry to TypeScript
- Migrate IntegrationManager to TypeScript
- Migrate ProfileSettings to TypeScript

2021-08-16 08:28 UTC, SimonBrandner commented on src/components/views/rooms/ReadReceiptMarker.tsx
>  import * as sdk from "../../../index";
Could we please get rid of these

2021-08-16 08:30 UTC, SimonBrandner commented on src/components/views/rooms/RoomDetailList.tsx
>  import * as sdk from '../../../index';
Could we please get rid of these

2021-08-16 08:30 UTC, SimonBrandner commented on src/components/views/rooms/RoomUpgradeWarningBar.tsx
>  import * as sdk from '../../../index';
Could we please get rid of these

2021-08-16 08:30 UTC, SimonBrandner commented on src/components/views/settings/DevicesPanel.tsx
>  import * as sdk from '../../../index';
Could we please get rid of these

2021-08-16 08:30 UTC, SimonBrandner commented on src/components/views/settings/IntegrationManager.tsx
>  import * as sdk from '../../../index';
Could we please get rid of these

2021-08-17 17:26 UTC, SimonBrandner approved these changes
Seems sane! Just some nitpicks.

Also, CI seems to not be happy. The removal of `sdk.getComponent()` in some cases can actually cause some test failures :( It might be worth checking that if the cause isn't obvious

2021-08-17 17:26 UTC, SimonBrandner commented on src/components/views/rooms/ReadReceiptMarker.tsx
> +import { RoomMember } from 'matrix-js-sdk/src';
```suggestion
import { RoomMember } from "matrix-js-sdk/src/models/room-member";
```

I do have a feeling that not doing this has caused problems before but I might be wrong

(same in other files)

2021-08-17 17:26 UTC, SimonBrandner commented on src/components/views/settings/ChangeAvatar.tsx
> +    public UNSAFE_componentWillReceiveProps(newProps): void {
```suggestion
    public UNSAFE_componentWillReceiveProps(newProps: IProps): void {
```

2021-08-17 17:26 UTC, SimonBrandner commented on src/components/views/settings/ProfileSettings.tsx
> +}
I think you can just do:

```
export default class ProfileSettings extends React.Component<{}, IState> {
```

2021-08-23 21:34 UTC, turt2live commented
Removed team review request while this is considered blocked.

2021-08-25 08:08 UTC, SimonBrandner requested changes
There still seems to be a few imports that aren't using the full-path which seems to be problematic - see https://github.com/matrix-org/matrix-react-sdk/pull/6671

2021-08-25 08:44 UTC, SimonBrandner commented on src/components/views/rooms/RoomUpgradeWarningBar.tsx
> +import { MatrixEvent, Room, RoomState } from 'matrix-js-sdk/src';
`/models`?

2021-08-25 08:50 UTC, SimonBrandner commented on src/components/views/settings/DevicesPanelEntry.tsx
> +import { IMyDevice } from 'matrix-js-sdk/src';
Here too please

2021-08-25 08:50 UTC, SimonBrandner commented on src/components/views/settings/ChangeAvatar.tsx
> +import { MatrixEvent, Room } from 'matrix-js-sdk/src';
Here too, please

2021-08-25 09:05 UTC, SimonBrandner approved these changes
LGTM

2021-09-03 04:05 UTC, turt2live approved these changes
lgtm, though the copyright header stuff might change again 🙃 (internal discussion)

2021-09-03 07:47 UTC, merged