Improve Telegram gif handling
matrix-org/matrix-react-sdk pull request #6649
Opened 2021-08-20 12:20 UTC by tulir

Telegram (and basically all other modern chat apps) use video files instead of actual .gif files for any features called "gifs", which makes sense because gif files are huge. However, Matrix doesn't have such modern features, so users will see a full video player instead of a nice looping gif. This change adds support for simple custom flags that can be used to make the video player behave similar to actual .gif files.

The flags are set by the Telegram bridge here: https://github.com/mautrix/telegram/blob/v0.10.1/mautrix_telegram/portal/telegram.py#L252-L260

2021-08-23 21:30 UTC, turt2live requested changes
Per https://github.com/matrix-org/matrix-react-sdk/pull/6642, this is not an appropriate approach.

2021-08-23 22:10 UTC, tulir commented
This is about telegram gifs (= short looping video clips with no audio), not stickers. I'm not sure what other approach there is?

(the bridge coincidentally sends animated stickers the same way as gifs, but that's not relevant)

2021-08-23 22:16 UTC, turt2live reviewed
hmm, in that case I think it'd be best to run this through a fairly brief MSC just so we have documentation to point to for how this works.

2023-06-22 14:08 UTC, andybalaam commented
Marking as draft since it could be plausible, but we'll need an MSC before we can merge.

2024-09-11 17:46 UTC, closed without merging