Add basic support for attachments (as per MSC2881)
matrix-org/matrix-react-sdk pull request #6683
Opened 2021-08-25 23:05 UTC by chayleaf

Type: enhancement

See https://github.com/matrix-org/matrix-doc/pull/2881/

Ideally, m.relates_to needs to be an array for multiple attachments to work, and to implement file/image replies properly, but that would require way more changes (including in Synapse) to make all relations code work with arrays. Currently, I just show "In reply to" without the message actually being a reply.

In this implementation, if any text is already in the composer during upload, files get sent as an attachment (and after they finish uploading, text gets sent immediately). Naturally, a better UI will be needed.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add basic support for attachments (as per MSC2881) ([\#6683](https://github.com/matrix-org/matrix-react-sdk/pull/6683)). Contributed by @chayleaf.

Preview: https://612723cb1e11b2602d882f7e--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

2021-08-26 07:10 UTC, SimonBrandner requested changes
Thank you for working on this! It's looking great! Just a couple of readability comments 

<hr>

Few other things: 

+ Could you explain in the description which version of the MSC are you implementing (though hopefully it gets split up https://github.com/matrix-org/matrix-doc/pull/2881#discussion_r696338250)
+ AFAIK, this isn't really implementing the MSC since it doesn't use an array I think that should be somehow made more clear
+ Could you also please document this in https://github.com/vector-im/element-web/blob/develop/docs/labs.md
+ I think it would be better UX wise to add a composer to the upload dialog but that is not a necessity since this is in labs and you may want to do that in a separate PR

2021-09-03 04:31 UTC, turt2live reviewed
Woo! Attachments! 

Screenshots/gifs of this in action would be appreciated to make design/product review a bit easier.

The code overall is a bit stringy, but I think that's because the composer code is a bit stringy from having to do so many things. The outstanding comments from Simon I think will at least help with readability and thus make it easier to follow.

I've not done a super in-depth review on this just yet as it'll need to go through product and design review, which will probably end up changing how the thing works and thus changing the code we end up with :)

2021-09-03 04:31 UTC, turt2live commented on src/components/views/rooms/SendMessageComposer.tsx
> +            'rel_type': 'org.matrix.msc2881.m.attachment',
throughout we generally prefer to use `UnstableValue` from the js-sdk for identifiers like this. It makes for transitioning a bit easier, particularly when/if the MSC becomes stable.

There should be some example usages in the code somewhere: look for `new UnstableValue`

2021-09-03 05:49 UTC, pavlukivan commented
I think of implementing https://github.com/matrix-org/matrix-doc/pull/3051 support first, as it's necessary for supporting image replies/multiple attachments. Single relation is pretty limiting here. Hence, I'll convert this into a draft PR for now.

2022-02-22 15:35 UTC, kittykat commented
I'm going to unassign from Design and Product for now until there are some screenshots/gifs to review

2024-09-11 17:46 UTC, closed without merging