Globally replace all console.logs via codemod
matrix-org/matrix-react-sdk pull request #6827
Opened 2021-09-17 10:09 UTC by Palid

Transform all the `console.log` calls to a proper logger.

Used below `jscodeshift` transform script:

js```
const j = require('jscodeshift');
const addImports = require('jscodeshift-add-imports');

const { statement } = j.template;

module.exports = function(fileInfo, api) {
    const root = api.jscodeshift(fileInfo.source);
    let foundConsoleLog = false;
    const newSource = root
        .find(j.MemberExpression, (node) => {
            const { object, property } = node;
            const isConsoleLog = object.type === 'Identifier' &&
                object.name === 'console' &&
                property.type === 'Identifier' &&
                property.name === 'log';
            return isConsoleLog;
        })
        .forEach(function(path) {
            const { value } = path;
            if (value.object.name === 'console' && value.property.name === 'log') {
                foundConsoleLog = true;
                value.object.name = 'logger';
                value.property.name = 'info';
            }
        });

    if (foundConsoleLog) {
        addImports(root, [
            statement`import { logger } from "matrix-js-sdk/src/logger";`,
        ]);
    }

    return newSource.toSource();
};

module.exports.parser = 'ts';

```

2021-09-17 10:12 UTC, Palid commented
Related: https://github.com/vector-im/element-web/issues/18425

2021-09-17 11:47 UTC, dbkr commented
loglevel also has `log.log` which is an alias for `log.debug`. I'd probably suggest changing them to this, that way we can easily tell what was updated from a console.log apart from things where we've made an explicit decision about what level it gets logged at.

2021-09-17 14:16 UTC, Palid commented
> loglevel also has `log.log` which is an alias for `log.debug`. I'd probably suggest changing them to this, that way we can easily tell what was updated from a console.log apart from things where we've made an explicit decision about what level it gets logged at.

updated, have a look again please!

2021-09-18 22:39 UTC, turt2live requested changes
Overall the changes look fine. 

There's quite a few unrelated changes in this PR though, likely from the automated tooling. I'm not really going to point them out in this review (as I largely agree with the choice), but it is unadvertised work: the PR is already large from a console->logger change, so having to review another hundred lines of parenthesis changes becomes frustrating as a reviewer. I suspect it's probably from the automated tooling in combination with local environmental things, but please review diffs before sending them up for review: they should be the smallest possible change.

In bulk PRs like this it's especially important to limit the size of the diff for the reviewer. In smaller PRs, absolutely fix surrounding code quality issues, but not in PRs of this size.

In this case, they've already been reviewed, so it's not worth the effort to remove them. Just a note for next time.

2021-09-18 22:39 UTC, turt2live commented on src/DeviceListener.ts
> +        if (!(await cli.doesServerSupportUnstableFeature("org.matrix.e2e_cross_signing"))) return;
unrelated changes

2021-09-18 22:39 UTC, turt2live commented on src/rageshake/rageshake.js
> -
Please restore this line break.

2021-09-18 22:39 UTC, turt2live commented on src/rageshake/rageshake.js
> -
Please restore this line break.

2021-09-18 22:39 UTC, turt2live commented on src/utils/FontManager.ts
> -
Please restore this line break.

2021-09-20 11:03 UTC, Palid commented
> Overall the changes look fine.
> 
> There's quite a few unrelated changes in this PR though, likely from the automated tooling. I'm not really going to point them out in this review (as I largely agree with the choice), but it is unadvertised work: the PR is already large from a console->logger change, so having to review another hundred lines of parenthesis changes becomes frustrating as a reviewer. I suspect it's probably from the automated tooling in combination with local environmental things, but please review diffs before sending them up for review: they should be the smallest possible change.
> 
> In bulk PRs like this it's especially important to limit the size of the diff for the reviewer. In smaller PRs, absolutely fix surrounding code quality issues, but not in PRs of this size.
> 
> In this case, they've already been reviewed, so it's not worth the effort to remove them. Just a note for next time.

Yeah, those changes have been done by the codemod automatically. We could only go through it file-by-file and remove the changes manually or split into two commits. Makes sense, but in terms of just fixing this thing it's a slight waste of time (especially considering that the codemod was used to save it). 
Any suggestions how to do it in a way that everyone's satisfied?

BTW, I'll fix those comments tomorrow (tuesday), not feeling well today.

2021-09-21 15:15 UTC, turt2live commented
For straightforward changes like `console.log -> logger.log` we likely don't need automated tooling. A find & replace all with the IDE is usually good enough.

For more sophisticated replacements (changing function naming scheme, for example), we should definitely use a tool of some kind, where we can be a bit more relaxed on the "excess stuff" during review.

2021-09-21 15:15 UTC, turt2live reviewed
provisional acceptance - you have merge conflicts (sorry)

2021-09-21 15:16 UTC, Palid commented
> For straightforward changes like `console.log -> logger.log` we likely don't need automated tooling. A find & replace all with the IDE is usually good enough.
> 
> For more sophisticated replacements (changing function naming scheme, for example), we should definitely use a tool of some kind, where we can be a bit more relaxed on the "excess stuff" during review.

In this case we needed tooling to add the proper import, unfortunately. Just search&replace would make it more problematic.

2021-09-21 15:18 UTC, turt2live commented
The import can be resolved by reading build failures, in theory :D

2021-09-21 15:19 UTC, Palid commented
> The import can be resolved by reading build failures, in theory :D

Yes, but why though? 😆

2021-09-21 15:47 UTC, turt2live commented
Mostly to avoid opinionated reviewers from showing up on your PR down the road 😇 

The other option is to just note it in the PR title so it's not as unexpected - something like "Use js-sdk logger and fix minor code style issues". I'd personally still be a bit unhappy about the changes being mixed in, but it would at least be anticipated work.

2021-09-21 15:48 UTC, turt2live approved these changes

2021-09-21 15:48 UTC, merged