Convert `/rooms` to TS
matrix-org/matrix-react-sdk pull request #6839
Opened 2021-09-19 08:53 UTC by SimonBrandner

Type: task
**Requires https://github.com/matrix-org/matrix-js-sdk/pull/1940**

2021-09-20 14:59 UTC, turt2live requested changes
otherwise looks good - thanks! Another one for post-RC :)

2021-09-20 14:59 UTC, turt2live commented on src/components/views/rooms/E2EIcon.tsx
> +}
Should be updated to new naming conventions `E2EState.Verified` etc

2021-09-20 20:33 UTC, turt2live reviewed
The `E2E_STATE` enum should also be renamed to `E2EState` to follow the convention used in practice

2021-09-21 06:19 UTC, SimonBrandner commented
> The `E2E_STATE` enum should also be renamed to `E2EState` to follow the convention used in practice

Oops :man_facepalming:

2021-09-21 15:13 UTC, turt2live approved these changes

2021-09-21 15:13 UTC, merged