Make portrait images (up to 9:19) the same width than landscape in for SIZE_NORMAL setting.
matrix-org/matrix-react-sdk pull request #7188
Opened 2021-11-23 12:01 UTC by toger5

now portrait images are drawn with the same width than Landscape images.
This was the [requested behavior from design](https://github.com/matrix-org/matrix-react-sdk/pull/7017#issuecomment-957761011).
This PR https://github.com/matrix-org/matrix-react-sdk/pull/7171 fixed a bug for really height images but also made portrait images  not behave as desired anymore.
(see the comments in the changed files for the logic used to determine image sizes)
Left old, right new (for the large setting nothing changes)
![image](https://user-images.githubusercontent.com/16718859/143020500-894c3c75-fb75-49d9-952f-db30eac03c31.png)

2021-11-23 23:35 UTC, turt2live approved these changes
The code looks fine, though I'm a bit sad to see portrait images taking up even more space again - it feels like it defeats the purpose of the smaller image size setting.

2021-11-23 23:35 UTC, turt2live commented on src/settings/enums/ImageSize.ts
> +// constraint by: timeline width, manual heigh overrides, SIZE_LARGE.h
```suggestion
// constraint by: timeline width, manual height overrides, SIZE_LARGE.h
```

2021-11-23 23:35 UTC, turt2live commented on src/settings/enums/ImageSize.ts
> +// constraint by: timeline width, manual heigh overrides
```suggestion
// constraint by: timeline width, manual height overrides
```

2021-11-24 15:18 UTC, gaelledel requested changes
@toger5 I'm sorry, there must have been a misunderstanding with this. My original request was to simply make sure that we have a set width for landscape and a set width for portrait whether it is image or video based media.

2021-11-25 11:52 UTC, toger5 commented
I revisited this PR and added another default value for portrait images. They are handled the same way (they are sized so that the width fits the requested width, EXCEPT if the height exceeds a maximum)  but just use different default values now.
 - this makes sure 16:9 images and 9:16 images take the same area in the timeline.
 - for images with an aspect ration lesser than 1:1 it introduces a new width so that the timeline is less chaotic.
 
left old, right new
<img width="300px" src="https://user-images.githubusercontent.com/16718859/143436340-84573f9f-43b4-482b-865a-e5eafdc5a172.png">

2021-11-29 11:46 UTC, gaelledel reviewed
Perfect, thank you very much @toger5!

2021-11-29 13:38 UTC, gaelledel approved these changes

2021-11-29 14:01 UTC, merged