Add new line in settings label
matrix-org/matrix-react-sdk pull request #7451
Opened 2021-12-28 13:27 UTC by toger5

Fixes: https://github.com/vector-im/element-web/issues/20365

2021-12-28 13:47 UTC, kittykat commented
Looks better than before:
![Screenshot from 2021-12-28 13-45-13](https://user-images.githubusercontent.com/51663/147572648-73509771-8028-474a-9ce1-07757a99c05b.png)

Should the toddle be aligned to the switch title or to the switch title and description (the latter is the case with this change)?

2021-12-28 13:49 UTC, toger5 commented
Do we know how this was done before? (toggle alignment)

2021-12-28 15:53 UTC, LynHyper commented
In Settings, General the "Manage integrations" slider is aligned with the normal text and not the grey text so I think that's what's used.

2021-12-28 18:04 UTC, toger5 commented
I updated the alignment (see intial post for screenshots)

2021-12-29 10:40 UTC, kittykat approved these changes
Testing Netlify build with and without Large Font accessibility setting, but look good :+1: and Amsha confirmed that it should be centred to setting title.

2021-12-29 11:10 UTC, toger5 commented
Good you thought about the large font option! I haven't tested it with that yet.

2021-12-29 11:15 UTC, toger5 commented
Did you also look through the code changes, or is there a code review still needed?

2021-12-29 12:30 UTC, kittykat commented
> Did you also look through the code changes, or is there a code review still needed?

I'm not a developer, so you may want a review from someone else but they do look sane to me

2022-01-03 18:03 UTC, turt2live requested changes

2022-01-03 18:03 UTC, turt2live commented on src/components/views/elements/SettingsFlag.tsx
>                          </span> }
if we want a block element, why not a `div` instead of a manual linebreak?

2022-01-03 18:05 UTC, toger5 commented on res/css/views/elements/_SettingsFlag.scss
> +    padding-top: 3.5px;
I was pretty sure that there are 7px difference in the height of the toggle Button and the Text. But it is not noticable at all. So going with 4 should be totally fine as well.

2022-01-03 22:35 UTC, turt2live approved these changes
thanks :)

2022-01-04 09:57 UTC, merged