Add view in room to action bar in thread list
matrix-org/matrix-react-sdk pull request #7519
Opened 2022-01-12 11:56 UTC by gsouquet

Fixes https://github.com/vector-im/element-web/issues/20348

<img width="318" alt="Screen Shot 2022-01-12 at 11 54 17" src="https://user-images.githubusercontent.com/769871/149136038-07316d1e-1bb9-44cc-b027-1ac9215210a9.png">

2022-01-12 12:06 UTC, t3chguy approved these changes
LGTM otherwise

2022-01-12 12:06 UTC, t3chguy commented on src/components/views/rooms/EventTile.tsx
> +                                onClick={(e) => this.viewInRoom(e)}
can we make viewInRoom an arrow func and avoid this one?

2022-01-12 12:12 UTC, janogarcia requested changes
@gsouquet Thanks Germain for making progress with this! I haven't run the test build, but if it looks as in the screenshot, I’d point out that the [original proposal](https://github.com/vector-im/element-web/issues/20348) was to get rid of the overflow menu in this context, moving both actions — "View in room", and "Copy link to thread" — out of it.

2022-01-12 17:27 UTC, gsouquet commented
Yeah apologies, I got mixed up, this is now fixed

<img width="313" alt="Screen Shot 2022-01-12 at 17 23 02" src="https://user-images.githubusercontent.com/769871/149190851-5c3c3b70-d43c-488a-8cd8-7420a9d30491.png">

2022-01-19 10:23 UTC, janogarcia approved these changes
@gsouquet Thanks for updating it! 👍

2022-01-19 10:39 UTC, merged