Expose redaction power level in room settings
matrix-org/matrix-react-sdk pull request #7599
Opened 2022-01-21 17:56 UTC by SimonBrandner

Type: enhancement
Fixes https://github.com/vector-im/element-web/issues/20590

2022-01-21 19:07 UTC, turt2live approved these changes
code looks fine, but I think this requires product and/or design to look at it - there's potential confusion between this setting and `redacts`, which achieve very different things.

There's also potential for concerns around making it easy for people to block self-redactions in rooms from a product perspective. We might be better off inventing a UI flow for making announcement-only rooms instead.

2022-01-24 11:45 UTC, t3chguy requested changes

2022-01-24 11:45 UTC, t3chguy commented on src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
> +            [EventType.RoomRedaction]: _td("Redact messages"),
the string should be `Remove`

![image](https://user-images.githubusercontent.com/2403652/150777380-701490d0-e00d-46cb-a2e4-1aeb958b2a38.png)

2022-02-28 10:35 UTC, kittykat commented
@SimonBrandner can you share a screenshot of what this will look like in in the UI please?

2022-02-28 16:43 UTC, kittykat requested changes
Can you please move the new setting to be above "Remove messages sent by others" and change the string from "Remove messages" to "Remove your own messages"?

Otherwise LGTM

2022-02-28 17:12 UTC, SimonBrandner commented
From a quick look, adding some sort of ordering might be a bigger change, so I'd rather leave it for a separate PR

2022-02-28 18:09 UTC, SimonBrandner commented
![2022-02-28_19-08](https://user-images.githubusercontent.com/25768714/156035314-57a682fc-9715-4b52-afb9-4b616b59553e.png)

Updated image

2022-03-01 09:38 UTC, t3chguy approved these changes

2022-03-01 14:34 UTC, kittykat approved these changes

2022-03-01 16:41 UTC, merged