replace user id with displayname and add type to diffs
matrix-org/matrix-react-sdk pull request #7781
Opened 2022-02-10 21:33 UTC by chagai95

Makes more sense to show the display name and not the user ID, I think.

![image](https://user-images.githubusercontent.com/31655082/153301299-284498fb-eb5b-417c-b14b-6b5d2eb615fb.png)

Signed-off-by: Chagai Friedlander chagai95@gmail.com

2022-02-11 10:36 UTC, t3chguy requested changes

2022-02-11 10:36 UTC, t3chguy commented on src/TextForEvent.tsx
> +        const displayName = MatrixClientPeg.get().getUser(userId).displayName;
Displaynames are per-room, not global, so you can't use the displayName of getUser in a room. You'll need to get the room member instead

2022-02-11 10:36 UTC, t3chguy commented on src/TextForEvent.tsx
> +                displayName: diff.displayName,
You need to run the `i18n` script to regen the i18n files

2022-05-09 06:31 UTC, t3chguy commented
Hello @chagai95 are you able to iterate on this PR based on the feedback?

Thanks

2022-05-10 11:12 UTC, chagai95 commented
> Hello @chagai95 are you able to iterate on this PR based on the feedback?
> 
> Thanks

Hey, I should be able to, thx for the ping, I'll try getting around to this very soon.

2022-10-12 02:26 UTC, aaronraimist commented
Superseded by https://github.com/matrix-org/matrix-react-sdk/pull/9295

2022-10-12 04:07 UTC, turt2live commented
Closing in favour of https://github.com/matrix-org/matrix-react-sdk/pull/9295

2022-10-12 04:07 UTC, closed without merging