Fix CopyableText overflow
matrix-org/matrix-react-sdk pull request #7851
Opened 2022-02-20 20:43 UTC by pwz266266

Fixes: https://github.com/vector-im/element-web/issues/21040

## Before:
![image](https://user-images.githubusercontent.com/32167120/154863476-016543b6-e267-4294-811c-3b3451f90060.png)

## After:
![image](https://user-images.githubusercontent.com/32167120/154863353-c00e91f9-7908-4d5f-9327-06d8836a88ee.png)

##  Bug Fixes
* Make the CopyableText scrollable so that longer text won't overflow. 
* Scroll bar is hidden.

Signed-off-by: wenzhe <pwz26626664@gmail.com>

2022-02-21 05:22 UTC, SimonBrandner submitted a review, later dismissed
LGTM codewise - thanks!

2022-02-21 09:53 UTC, andybalaam submitted a review, later dismissed
Looks good, thank you!

2022-02-21 09:57 UTC, t3chguy requested changes
The scrollbar should not be missing, that makes the accessibility poor, the text should also have an ellipsis

2022-02-21 10:04 UTC, t3chguy commented on res/css/views/elements/_CopyableText.scss
>          height: 20px;
```suggestion
    .mx_CopyableText_innerText {
        overflow: auto;
    }

    .mx_CopyableText_copyButton {
        flex-shrink: 0;
```

And also get rid of the `cursor`, `margin-left` and `display` rules below too, they're superfluous please

2022-02-22 22:08 UTC, pwz266266 commented
Adapt changes from [t3chguy](https://github.com/t3chguy). LGTM

2022-02-24 13:20 UTC, t3chguy requested changes
Could we get a `margin-right` on `.mx_CopyableText_innerText` just to bring the button a bit further away. The css I told you to remove had a margin-left of 20px which only worked when the text wasn't overflowing, putting the margin on the innerText would work better, I think 16px is plenty though!

![image](https://user-images.githubusercontent.com/2403652/155531457-ac12643f-8b00-423f-830a-cf07f4fb922c.png)

2022-02-24 16:06 UTC, pwz266266 commented
> Could we get a `margin-right` on `.mx_CopyableText_innerText` just to bring the button a bit further away. The css I told you to remove had a margin-left of 20px which only worked when the text wasn't overflowing, putting the margin on the innerText would work better, I think 16px is plenty though!
> 
> ![image](https://user-images.githubusercontent.com/2403652/155531457-ac12643f-8b00-423f-830a-cf07f4fb922c.png)

How about margin-left of 10px? This could bring the same amount of white space around the copy button since the outter CopyableText itself has a padding of 10px.

2022-02-24 17:03 UTC, t3chguy commented
Hmm, playing with it some more I wonder whether it should just have `white-space: break-word;` instead, to make it span multiple lines

2022-02-24 22:28 UTC, pwz266266 commented
> Hmm, playing with it some more I wonder whether it should just have `white-space: break-word;` instead, to make it span multiple lines - what do you think?

I think both make sense, more of a design choice I guess?
Having multiple lines would result in:
![image](https://user-images.githubusercontent.com/32167120/155617186-684807f8-7b9e-44d8-8dff-814ef711e5e6.png)

I also checked other places using this component, should work fine too.
Code pushed which uses `word-break: break-all;`

2022-02-25 11:53 UTC, t3chguy commented
@matrix-org/design the three options here are

Wrap:
![image](https://user-images.githubusercontent.com/2403652/155710436-a0fd62fa-baf5-4adf-9a5b-0699d93adb69.png)

Scroll:
![image](https://user-images.githubusercontent.com/2403652/155710463-6bb6cedd-2c91-46ab-b923-aa5ecc1d025e.png)

Ellipsis:
![image](https://user-images.githubusercontent.com/2403652/155710959-e4fdc412-3587-45c1-8a3c-037b3d3a2f97.png)

2022-05-11 10:55 UTC, janogarcia reviewed
@t3chguy Given that it seems to be collapsed by default and thus not taking up any space in the screen until it's revealed, I'd recommend going for the **Wrap** variant, as long as it doesn't take way too many lines when revealed (let's say more than 20 lines).

---

As an alternate case:

Suppose we had to show similar inputs by default (uncollapsed) in other places where we need to save some space. In that case, I'd recommend using the ellipsis variant so that when clicking on the text, the ellipsis is replaced by a hard cut-off (no horizontal scroll), and the whole string is selected for you.

<img width="378" alt="Frame 6502" src="https://user-images.githubusercontent.com/60790/167833402-9b58b8eb-fe04-45a4-a7d0-15c9f187f5c1.png">

2022-05-11 10:57 UTC, t3chguy commented
@janogarcia this is a re-usable component

![image](https://user-images.githubusercontent.com/2403652/167833702-f49f390a-051f-410b-afc0-936fde02339c.png)

Used in many places already, so the decision here will impact all those. So would you say single-line ellipsis then? In future we could add an expand mechanism if we deem it useful.
Today it just sprawls out, so any decision is better than today's implementation

2022-05-11 11:01 UTC, janogarcia commented
> So would you say single-line ellipsis then?

@t3chguy Makes sense. Would it be possible to implement the on click/selected behavior explained above (please refer to mockup)?

2022-05-11 11:22 UTC, t3chguy commented
@janogarcia yup that should be reasonable

2022-05-11 11:22 UTC, t3chguy commented
@pwz266266 are you up for making the changes outlined above?

2022-05-12 17:04 UTC, janogarcia commented
@t3chguy Turns out that (in an unsurprising way) we have somewhat different renderings/treatments for that component.

**Settings**

We do have both multiline (`Versions`) and single line containers (`Access Token`).

**URLs**

- Default state: Ellipsized if overflowing.
- Selected state: The whole string is selected automatically on clicking on it, but the ellipsis char is not removed.

My recommendation would be implementing the [suggested behavior](https://github.com/matrix-org/matrix-react-sdk/pull/7851#pullrequestreview-969116145) if single line (auto-select + ellipsis that is removed on select), and just applying the auto-select behavior if multi line. It would require performing some updates to the component to have a more robust and consistent one.

---

![settings](https://user-images.githubusercontent.com/60790/168128942-e0f71ff3-8ef1-4dfd-8ad8-1724a02a34cc.png)

![share](https://user-images.githubusercontent.com/60790/168128975-064b9d0a-110c-4ac6-acba-dad6ea91e352.png)

![share-selected](https://user-images.githubusercontent.com/60790/168128995-a52b8df4-1b69-4dfc-8aaf-96687c71c2c5.png)

2022-05-13 10:11 UTC, t3chguy commented
@janogarcia great point, to clarify I was only specifically meaning we tweak the behaviour of CopyableText elements which contain text without any new lines (`\n`) characters.

2022-05-13 11:02 UTC, janogarcia commented
@t3chguy Sure, but given that both cases are so tightly related, it would be a pity to normalize the behavior just for one case (no new lines) while keeping the other one working slightly inconsistently.

To recap, by normalizing the component we actually refer to two separate behaviors:

- How **text auto-selection** should work: On clicking the text, the whole string gets selected. Applies to both single line and multiple line variants. 
- How **overflowing text** should be handled: Show ellipsis if overflowing. Remove ellipsis and cut off text on clicking/selecting it. Only applies to single line variant.

I'd suggest that we normalize both behaviors, text auto-selection and overflow text.

If the former needs to happen in a separate PR because of scope creeping that's OK but, _if possible_, we should try addressing both at the same time as they are quite interdependent.

2022-05-13 11:17 UTC, janogarcia commented
Sometimes we try to keep PRs super atomic, which isn't necessarily a bad thing, but that can also prevent us from introducing/performing more relevant, necessary updates right away once we realize the actual underlying issues.

It's an incremental improvement, I totally agree, but it can sometimes make dealing with UX debt more tedious (splitting the discussion, etc).

2022-05-13 12:25 UTC, t3chguy commented
Perfect, thanks for the recap/summary

2022-05-13 12:26 UTC, t3chguy requested changes
See above, let me know if you need any help at all

2023-05-12 18:17 UTC, closed without merging