Remove harmfull .mx_Dialog font-weight definition
matrix-org/matrix-react-sdk pull request #7880
Opened 2022-02-23 07:16 UTC by globau

Specifying the font-weight here is harmful when using fonts that support
Light or variable weights.

Signed-off-by: glob <byron@glob.com.au>

Notes: Fix a bug (https://github.com/vector-im/element-web/issues/21171) causing poor rendering of custom fonts in dialogs

2022-02-23 08:57 UTC, gsouquet requested changes
It appears that there a couple more occurence of `font-weight: 300` in the codebase that would probably be suceptible to the same issue you raised. Could you update those ones too?

I looked at `@font-face` declaration and it appears that we're loading the following font weights: `400`, `500`, `600`, `700` for `Inter`. And `400` and `700` for `Inconsolata`

Will also loop in the design team to confirm this is a change we're comfortable making

2022-02-23 14:19 UTC, gsouquet approved these changes
Code looks good to me.
Please keep the design reviewers on. Without their approval we will not be abe to move this pull request forward

2022-02-23 15:48 UTC, janogarcia commented
Unsure where those lighter fonts are being used, but, yeah, the current minimum weight should be 400.

2022-02-23 15:53 UTC, janogarcia reviewed
Are the affected components now inheriting the base font-weight of `400`?

2022-02-24 07:04 UTC, globau commented
> Are the affected components now inheriting the base font-weight of `400`?

Excellent question!

As far as I can tell `mx_Dialog` always cascades to 400.

I can't find where `mx_CreateRoom` is used (no references to it under the `src` directory).

I'm not sure what a GroupView is so I can't verify manually in the Element client, but as far as I can tell (with my very limited knowledge here) the default weight for `mx_GroupView_header_shortDesc` _should be_ 400.

2022-02-24 12:26 UTC, t3chguy commented
> I can't find where mx_CreateRoom is used (no references to it under the src directory).

It is no longer used, can we kill that entire file as part of this PR please.

2022-02-24 12:32 UTC, globau commented
> > I can't find where mx_CreateRoom is used (no references to it under the src directory).
> 
> It is no longer used, can we kill that entire file as part of this PR please.

Removing an _potentially_ unused class seems to be unrelated to this issue, and I'd prefer if it were fixed in a separate PR.

2022-02-24 12:34 UTC, t3chguy commented
Editing a class which does not cause your bug due to being unused is also unrelated to this issue though?

2022-02-24 12:38 UTC, janogarcia commented
@globau Thanks for checking!

@t3chguy @gsouquet Can you please check/confirm if removing the declaration for `300` will inherit `400` for the cases where @globau is unsure how to test for?

2022-03-06 13:59 UTC, globau commented
@janogarcia To move this along how about instead of removing the `font-weight: 300` lines I replace them with `font-weight: 400`?

That will guarantee correct rendering regardless of context, however it might mean clean up is required in a different PR due to possible redundancy.

2022-03-08 14:43 UTC, janogarcia commented
@globau Sounds reasonable (ideally, if we could avoid those extra declarations, the better), but I'm afraid that would be up to @t3chguy and @gsouquet.

2022-03-30 18:19 UTC, closed without merging