dont re-prepare voice messages
matrix-org/matrix-react-sdk pull request #7897
Opened 2022-02-25 10:02 UTC by kerryarchibald

Fixes: https://github.com/vector-im/element-web/issues/21206

2022-02-25 15:40 UTC, DoM1niC commented
Threads Composer is brocken too :(

2022-02-25 17:55 UTC, turt2live requested changes
I don't quite understand what the fix is doing, but it seems like it does fix something. Additional comments in-code to describe what's going on would be appreciated as this area is different from most component structures in the app.

2022-02-25 17:55 UTC, turt2live commented on src/audio/Playback.ts
> -
if possible, it'd be good to keep this blank line for code clarity.

2022-02-25 17:55 UTC, turt2live commented on src/audio/Playback.ts
> +        }
this needs a comment, and preferably a blank line after it.

2022-02-28 22:30 UTC, turt2live approved these changes
thanks!

2022-03-01 08:43 UTC, merged