Render image data in reactions
matrix-org/matrix-react-sdk pull request #7903
Opened 2022-02-25 20:06 UTC by AndrewRyanChama

Many messaging services such as Slack and Discord allow for custom
images for reacts, rather than only standard emoji. Currently Element
will only show the plain text of the reaction key.

This PR updates element to render the media content from reaction
events. This does not add a way for users to add custom reactions yet.

This can be useful in the case of bots and bridges, which will be able
to immediately use this functionality.  A picker for Element users will
be added in the future.

This is a solution to https://github.com/vector-im/element-web/issues/2648

Similarly to stickers, the event type should simply be sent with an image content, and it will be displayed appropriately.  For example
```json
 "content": {
    "body": "parrot.gif",
    "info": {
      "size": 15010,
      "mimetype": "image/gif",
      "w": 128,
      "h": 128,
      "xyz.amorgan.blurhash": "UKFg2,Ef0f-V0es:}tR*wf$*xZNH$*NaI:bH"
    },
    "url": "mxc://localhost:8008/zyCSlBnBTQCxhTFDEDNpNobe",
    "m.relates_to": {
      "rel_type": "m.annotation",
      "event_id": "$FqS1dRW7gMe_JhXNSBUy2ApAQNMQ4IL-vywYNqbXRlA",
      "key": ":partyparrot:"
    }
  },
```

Signed off by Andrew Ryan andrewryanchama@clover.club

Original behavior / fallback:
<img width="297" alt="Screen Shot 2022-02-25 at 12 03 45 PM" src="https://user-images.githubusercontent.com/89478935/155788683-6bf94dfb-c39b-422b-bf63-7e47d7ce6d8f.png">
Updated to display image:
<img width="297" alt="Screen Shot 2022-02-25 at 11 54 12 AM" src="https://user-images.githubusercontent.com/89478935/155789028-ac6d6a23-2ba6-4888-8de5-72bd8f26c7a7.png">

2022-02-25 20:20 UTC, turt2live reviewed
Thank you for taking a look at this!

Code-wise this is largely okay, though I do somewhat question the approach. Custom emoji also extends into non-reaction messages which can affect how the technical side gets created.

Before it goes for design/product review, I think it'd be best to involve the Matrix Spec process to align a technical solution. There's already some proposals out there for this sort of thing, so it may just be a case of implementing one of them.

The larger context with custom emoji (and stickerpacks) in Matrix is that it's currently in desperate need of review and technical design. #matrix-spec:matrix.org on Matrix can provide more detail about both custom emoji and the proposal process.

2022-02-25 20:20 UTC, turt2live commented on src/HtmlUtils.tsx
> +    return shortcodes?.length ? `:${shortcodes[0]}:` : char;
unintentional change?

2022-02-25 20:20 UTC, turt2live commented on src/components/views/messages/ReactionImage.tsx
> +Copyright 2018 New Vector Ltd
This should probably be your copyright.

2022-02-25 22:19 UTC, AndrewRyanChama commented
This change doesn't conflict and is compatible with either https://github.com/matrix-org/matrix-doc/pull/1951 or https://github.com/matrix-org/matrix-doc/pull/2545, as both those deal mainly with distributing packs of images and don't cover reactions at all.

I can still put together an msc for this since it might help to make this explicit

2022-06-02 22:34 UTC, turt2live requested changes
Review was re-requested, however I feel this is blocked on product, spec, and design (in roughly that order, but spec is the more important problem at the moment).

2022-12-19 18:15 UTC, williamkray commented
would it be possible to put this and https://github.com/matrix-org/matrix-react-sdk/pull/8087 behind a labs flag or something so that the people who are itching for this can enable, with the understanding that the work is still being finalized from the spec and product side?

i would love to be able to share with my users that the feature they've been asking for for the last 2+ years is at least making progress, even if it's preliminary. using labs flags seems like a pretty common use case for early implementation of non-finalized spec feature testing in element.

2023-09-01 08:47 UTC, Johennes commented
Thank you for your contribution. @daniellekirkwood and I synced up today and have decided to proceed with https://github.com/matrix-org/matrix-react-sdk/pull/11087. I'm closing this pull request because it largely achieves the same thing but has the downside of using the short code as key which has already been criticized in https://github.com/matrix-org/matrix-spec-proposals/pull/3746/files#r866285147.

2023-09-01 08:47 UTC, closed without merging