move findMapStyleUrl
matrix-org/matrix-react-sdk pull request #7982
Opened 2022-03-04 15:15 UTC by kerryarchibald

Fixes: https://github.com/vector-im/element-web/issues/20655

`map_style_url` is not configured in .well-known or config.json
<img width="638" alt="Screenshot 2022-03-04 at 16 15 35" src="https://user-images.githubusercontent.com/3055605/156789307-dfa10748-123e-4acd-90d2-3e9f4d0f2414.png">

`map_style_url` is set in .well-known or config.json but is unreachable
<img width="634" alt="Screenshot 2022-03-04 at 16 13 48" src="https://user-images.githubusercontent.com/3055605/156789140-35b8fa64-6cf0-49ae-8336-7f69f2d9be08.png">

2022-03-08 02:47 UTC, turt2live approved these changes
generally seems fine!

2022-03-08 02:47 UTC, turt2live commented on src/components/views/location/findMapStyleUrl.ts
> +import { logger } from "matrix-js-sdk/src/logger";
needs copyright

2022-03-09 11:02 UTC, gaelledel requested changes
Could we use this style? https://www.figma.com/file/uthEK6xuo9hSQRdWvPAre5/Location-Sharing?node-id=793%3A52185

2022-03-09 17:52 UTC, kerryarchibald commented
<img width="413" alt="Screenshot 2022-03-09 at 18 51 15" src="https://user-images.githubusercontent.com/3055605/157501404-12ad6d5b-c685-4f8b-ba4f-f774f3b5a6f0.png">

2022-03-10 17:33 UTC, gaelledel approved these changes

2022-03-11 08:52 UTC, merged