Normalized shortcut formatting for quote expansion control
matrix-org/matrix-react-sdk pull request #7995
Opened 2022-03-06 08:37 UTC by Sinharitik589

Related to:- https://github.com/vector-im/element-web/issues/19685

Signed-off-by: Ritik Kumar [sinharitik18112835@gmail.com](mailto:sinharitik18112835@gmail.com)

2022-03-07 09:10 UTC, kerryarchibald commented
Hi @Sinharitik589, please fill out the pull request template with an entry for the changelog and some before and after screenshots so we can easily see the changes. You can check our [contributing guide](https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.md#how-to-contribute) for more details.

2022-03-08 15:30 UTC, t3chguy requested changes

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/fi.json
> +    "click":"⇧+napsauta",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/hu.json
> +    "click":"⇧+kattintás",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/components/views/messages/MessageActionBar.tsx
> +                        { _t("click") }
The shift part should be in this string, given the string should be an exact english translation (where pluralisation is not involved) , see https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/ja.json
> +    "click":"⇧＋クリック",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/nl.json
> +    "click":"⇧+click",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/pt_BR.json
> +    "click":"⇧+click",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/nl.json
> +    "click":"⇧+click",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/ru.json
> +    "click":"⇧+нажатие",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/sq.json
> +    "Collapse quotes │ ⇧+click": "Tkurri citimet │⇧+klikim",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/sv.json
> +    "click":"⇧ + klick",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/uk.json
> +    "click":"⇧ + klik",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/vi.json
> +    "click":"⇧ + click",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/i18n/strings/zh_Hant.json
> +    "click":"⇧+點擊",
Same as above

2022-03-08 15:30 UTC, t3chguy commented on src/components/views/messages/MessageActionBar.tsx
> +                        { _t("click") }
Should probably also have spaces around the `+`

<img width="174" alt="image" src="https://user-images.githubusercontent.com/2403652/157269991-116fb674-6b11-4bca-a3d3-29c4d737a633.png">

2022-03-08 18:59 UTC, Sinharitik589 commented
![image](https://user-images.githubusercontent.com/67551927/157306622-c08cd77d-60b7-409d-b90d-cbcb976a8661.png)
changed @t3chguy

2022-03-08 19:07 UTC, t3chguy commented
You appear to have included a lot of unrelated i18n related changes.

2022-03-08 19:36 UTC, Sinharitik589 commented
> You appear to have included a lot of unrelated i18n related changes.

My bad :(  ,fixed it now ..

2022-03-08 20:38 UTC, Sinharitik589 commented on src/components/views/messages/MessageActionBar.tsx
> +                        { `${_t("Click")} + ⇧` }
![image](https://user-images.githubusercontent.com/67551927/157320872-340e8c0a-00a1-4bb7-a1a0-0356958bdf3a.png)

2022-03-09 09:41 UTC, t3chguy approved these changes
This is great, thank you!

2022-03-09 09:52 UTC, merged