Refactor _KeyBackupFailedDialog.scss
matrix-org/matrix-react-sdk pull request #8029
Opened 2022-03-11 06:20 UTC by luixxiul

Closes https://github.com/vector-im/element-web/issues/21387

Moved everything under `.mx_KeyBackupFailedDialog`

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

Notes: none
element-web notes: none

2022-03-11 08:08 UTC, gsouquet requested changes
I'm not entirely sure I understand what problem you're trying to solve here?
The names used are scoped to this modal, I don't really see anyone using them outsite of this context? We probably don't really need to guard against changes by raising the specificity here.

Maybe you can go a bit more into details as to why this is needed?

2022-03-11 12:30 UTC, luixxiul commented
The reason why I felt this would improve the code is that this should prevent an issue such as one on the recent PR of mine ([#8010](https://github.com/matrix-org/matrix-react-sdk/pull/8010/files#diff-fe891f133cbc2e576e4c07537775d9d7a60fbc92885c524b6c43981825a4cb31L73])) from happening. The issue should not have happened if the hierarchy had been defined properly.

This case properties inside `.mx_KeyBackupFailedDialog_title` could be potentially overwritten due to changes of `.mx_Dialog_title`. Applying `!important` to cancel it is not a proper way as you know.

The intention of this PR is not to solve an existing issue, instead it is to help to prevent one from happening by making the structure defined strictly. This file is used infrequently, which I assume is why it will be difficult to detect a bug in case of a big update which involves the whole UI. (Also I picked this minor file up because I am not familiar with the codebase yet and wanted to avoid creating a major visual bug :sweat_smile: )

If the change is not necessary anyway thanks to a policy / consensus, it is totally fine to close the PR.

2022-03-11 14:58 UTC, gsouquet commented
I'm not sure that raising the specificity of selectors and making them more dependant on a specific DOM structure is particularly the way to go especially in a scenario where that does not solve a bug

2022-04-22 07:51 UTC, luixxiul commented
Since the rules correctness cannot be verified by myself, I'm going to close this PR for now.

2022-04-22 07:51 UTC, closed without merging