Set max-width to elements under mx_UserMenu_contextMenu_name
matrix-org/matrix-react-sdk pull request #8089
Opened 2022-03-20 09:39 UTC by luixxiul

Fixes vector-im/element-web#21486

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

2022-03-21 16:47 UTC, luixxiul commented on res/css/structures/_UserMenu.scss
>                  // Automatically grow all subelements to fit the container
Based on this comment it is expected to hide display name and user ID over the width

2022-03-23 16:43 UTC, kerryarchibald requested changes

2022-03-23 16:46 UTC, luixxiul commented on res/css/structures/_UserMenu.scss
> +    width: $contextMenuWidth;
Thanks, I'm going to check it!

2022-03-24 08:45 UTC, kerryarchibald approved these changes
Looks good, thanks!

2022-03-24 08:49 UTC, merged

2022-03-24 09:15 UTC, luixxiul commented
Thanks for reviewing!