fix Searching for a mxid in an encrypted room
matrix-org/matrix-react-sdk pull request #8191
Opened 2022-03-30 09:46 UTC by EECvision

### Bug fixes: 
** #Fixed Searching for a mxid in an encrypted room yields**

In the PR, I added a check to know when a user is searching for a mxid and to search for the id only. eg. 
when a user searches for `@userId:example.org`, the search term will be `@userId`

The code before:
![before](https://user-images.githubusercontent.com/63562663/160801591-52a08c91-ff09-41d1-a9cb-f2c1267b210d.PNG)

The code after:
![after](https://user-images.githubusercontent.com/63562663/160801816-661a4b21-2cbc-4e19-8ed1-f6c8def8df4c.PNG)

This links to the [issue](https://github.com/vector-im/element-web/issues/21535)

2022-03-30 10:32 UTC, andybalaam commented
@EECvision please add `Fixes https://github.com/vector-im/element-web/issues/21535` to the issue description so that github will know to close that issue if this PR is merged.

2022-03-30 11:09 UTC, EECvision commented
This PR Fixes https://github.com/vector-im/element-web/issues/21535

2022-04-09 05:11 UTC, turt2live requested changes

2022-04-09 05:11 UTC, turt2live commented on src/components/structures/RoomView.tsx
> +        const regex = /^@.*:|^#.*:/;
We should be trying to convert user IDs within the query to just their localparts, to fix issues where someone searches for `delete request @user:example.org` (for example) - the user ID will be in the middle of the query and still cause breakage. 

I believe we already have a regex somewhere which does this searching, it just needs to be found.

2023-07-06 14:27 UTC, andybalaam commented
Abandoned - reopen if you are working on it.

2023-07-06 14:27 UTC, closed without merging