Fix warning in `yarn start` output
matrix-org/matrix-react-sdk pull request #8200
Opened 2022-03-31 10:22 UTC by gsouquet

Fixes the warning below

```
WARNING in ../matrix-react-sdk/src/component-index.js 551:68-91
"export 'default' (imported as 'views$location$MapError') was not found in './components/views/location/MapError'
```

2022-03-31 10:26 UTC, t3chguy commented
I would ignore this for now, it'll go away when skinning is removed next week

2022-03-31 10:35 UTC, gsouquet commented
I guess it does not really hurt to put it in now. Looks like we were discussing enforcing folks having `export default` on every file anyway?

2022-03-31 10:40 UTC, t3chguy commented
Yes but exporting the same thing twice is messy, so then please remove the named export

2022-03-31 22:01 UTC, turt2live requested changes
we should support one or the other export - I'm not opinionated on which.

2022-04-01 09:32 UTC, gsouquet commented
Given that we're going with named export in the future (after the conversation we had yesterday). It sounds silly to make this change. We'll live with the warning for that extra week 👍

2022-04-01 09:32 UTC, closed without merging

2022-04-01 15:31 UTC, turt2live commented
oh, good point. I completely forgot we had that conversation already 😅