fix-inconsistent grammer in device sign out modal
matrix-org/matrix-react-sdk pull request #8253
Opened 2022-04-07 14:52 UTC by EECvision

This PR fixes the issue: https://github.com/vector-im/element-web/issues/21699

I correct grammar inconsistency in the device sign out modal.

2022-04-07 14:54 UTC, gsouquet submitted a review, later dismissed

2022-04-07 14:55 UTC, gsouquet commented
I'm not sure I follow the inconsistency you've raised here. 
If you could give a bit more context that'd be good, otherwise I will close the pull request

2022-04-07 14:57 UTC, EECvision commented
> I'm not sure I follow the inconsistency you've raised here. If you could give a bit more context that'd be good, otherwise I will close the pull request

Alright. 

let me make it more detailed

2022-04-07 15:04 UTC, EECvision commented on src/i18n/strings/en_EN.json
> +    "Click the button below to confirm signing out these devices.|one": "Click the button below to confirm signing out these devices.",
Okay. The issue pointed at could not have been valid. Or, was it referring to a different thing.

see https://github.com/vector-im/element-web/issues/21699

2022-04-07 15:11 UTC, EECvision commented
> > I'm not sure I follow the inconsistency you've raised here. If you could give a bit more context that'd be good, otherwise I will close the pull request
> 
> Alright.
> 
> let me make it more detailed

A screenshot of what I changed.

![error1](https://user-images.githubusercontent.com/63562663/162231564-f9901b16-53fc-4349-a936-091a032d069a.PNG)

matrix-react-sdk\src\i18n\strings\en_EN.json Ln:1229 Col: 124

Maybe, I should change the line above Ln: 1229 instead to be singular. Will that be ok?

2022-04-07 17:44 UTC, luixxiul commented
@EECvision This is not related to the issue you work on, but I would like to recommend you to have a look at https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.

I'd write: `This PR fixes https://github.com/vector-im/element-web/issues/21699`.

2022-04-07 18:05 UTC, EECvision commented on src/i18n/strings/en_EN.json
> +    "Click the button below to confirm signing out these devices.|one": "Click the button below to confirm signing out these devices.",
yeah, thank you.

2022-04-07 18:06 UTC, EECvision commented
> @EECvision This is not related to the issue you work on, but I would like to recommend you to have a look at https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.
> 
> I'd write: `This PR fixes https://github.com/vector-im/element-web/issues/21699`.

Okay, thanks.

2022-04-07 19:44 UTC, EECvision commented on src/i18n/strings/en_EN.json
> +    "Click the button below to confirm signing out these devices.|one": "Click the button below to confirm signing out these devices.",
I have found the solution. I was anxious about solving the problem that I did not look well before making my first push.

**Modal for signing out a single device.**
![error1](https://user-images.githubusercontent.com/63562663/162283143-f00bd970-0933-445f-8770-d66fcb70df74.PNG)

**Modal for signing out multiple devices.**
![error2](https://user-images.githubusercontent.com/63562663/162283370-87e33175-2459-478b-8d1c-1fa4784e29ce.PNG)


I will make my push as soon as I finish translating the change in other languages.

2022-04-08 05:02 UTC, EECvision commented on src/i18n/strings/en_EN.json
> +    "Click the button below to confirm signing out these devices.|one": "Click the button below to confirm signing out these devices.",
Hi @gsouquet, I have updated my changes. Thank you.

2022-04-10 06:14 UTC, SimonBrandner commented
@EECvision, if you put `Fixes https://github.com/vector-im/element-web/issues/21699` into the PR description, the PR will automatically close the issue when merged, could you please do that?

2022-04-10 13:55 UTC, EECvision commented
> @EECvision, if you put `Fixes https://github.com/vector-im/element-web/issues/21699` into the PR description, the PR will automatically close the issue when merged, could you please do that?

Thank you I have updated the description.

2022-04-11 09:15 UTC, t3chguy requested changes
Please do not change any i18n files by hand except en_EN, it'll create conflicts in Weblate otherwise. All translations must be done via Weblate.

2022-04-12 10:45 UTC, t3chguy approved these changes
Looks good to me, thanks for your contribution!

2022-04-12 10:47 UTC, t3chguy requested changes
Needs DCO sign-off https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md#sign-off

2022-04-12 12:14 UTC, EECvision commented
> Needs DCO sign-off https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md#sign-off

I have added a sign off to the PR description. Thank you

2022-04-12 13:15 UTC, t3chguy approved these changes
Thanks!

2022-04-12 13:16 UTC, merged