fix-admin-tools-phrase-inconsistency
matrix-org/matrix-react-sdk pull request #8281
Opened 2022-04-11 14:14 UTC by EECvision

This PR `Fixes https://github.com/vector-im/element-web/issues/20578`

I have changed the Admin tools button "Ban" to "Ban from room" so as to be consistently phrased with Remove from room

2022-04-11 14:25 UTC, EECvision commented
Hi @t3chguy, please can you tell me why I am getting the error?

2022-04-11 15:01 UTC, turt2live requested changes
You've changed the string, but not the source file. Additionally, as noted in https://github.com/matrix-org/matrix-react-sdk/pull/7576, this needs to be space-aware.

The PR description should also not have the "Fixes $link" in a code block because it prevents github from working. The PR title should also be a sentence.

2022-04-11 15:11 UTC, EECvision commented
> You've changed the string, but not the source file. Additionally, as noted in #7576, this needs to be space-aware.
> 
> The PR description should also not have the "Fixes $link" in a code block because it prevents github from working. The PR title should also be a sentence.

Alright, thank you. I will fix that.

2022-04-12 08:42 UTC, t3chguy commented on src/components/views/right_panel/UserInfo.tsx
> +                action: isBanned ? _t("Unban") : _t("Ban from room"),
Surely now `ban` is inconsistent from `unban`?

2022-04-12 08:42 UTC, t3chguy commented on src/components/views/right_panel/UserInfo.tsx
>          label = _t("Unban");
Same as above

2022-04-12 09:23 UTC, EECvision commented on src/components/views/right_panel/UserInfo.tsx
> +                action: isBanned ? _t("Unban") : _t("Ban from room"),
Okay, I am towards fixing it.

2022-04-12 15:24 UTC, turt2live commented
Please do not force push after review has been given. It makes review significantly harder and less likely to happen :(

2022-04-12 15:48 UTC, t3chguy commented on src/components/views/right_panel/UserInfo.tsx
> +                    : isBanned ? _t("Unban from room") : _t("Ban from room"),
```suggestion
                action: room.isSpaceRoom()
                    ? (isBanned ? _t("Unban from space") : _t("Ban from space"))
                    : (isBanned ? _t("Unban from room") : _t("Ban from room")),
```

2022-04-12 15:48 UTC, t3chguy commented on src/components/views/right_panel/UserInfo.tsx
> +    | RightPanelPhases.EncryptionPanel;
```suggestion
        | RightPanelPhases.SpaceMemberInfo
        | RightPanelPhases.EncryptionPanel;
```

2022-04-12 16:22 UTC, t3chguy commented on src/components/views/right_panel/UserInfo.tsx
> +    | RightPanelPhases.EncryptionPanel;
Revert the formatting you did, it is unrelated to your PR

2022-04-13 09:01 UTC, EECvision commented
Hi @t3chguy, I have committed your suggestions. Is there any other change I need to make in the PR?

2022-04-14 21:01 UTC, turt2live approved these changes
Thanks!

2022-04-14 21:01 UTC, merged

2022-04-14 21:34 UTC, EECvision commented
> Thanks!



> Thanks!

Thank you