Fix svg images not correctly displaying in e2ee rooms
matrix-org/matrix-react-sdk pull request #8325
Opened 2022-04-14 13:43 UTC by justjanne

Type: Defect
Related: https://github.com/vector-im/element-web/issues/15094
Related: https://github.com/vector-im/element-web/issues/18526

2022-04-14 14:40 UTC, justjanne commented
This PR uses data URLs for embedded SVGs in E2EE rooms and other situations where no PNG version is available. This ensures we get a high quality preview without the risk of exposing our origin to user-defined scripts.

2022-04-14 21:32 UTC, turt2live requested changes
Thanks for taking a look at this, though it's not something we can merge easily. In addition to the comments below, I think this needs explicit review from the security team.

2022-04-14 21:32 UTC, turt2live commented on src/utils/MediaEventHelper.ts
> +    }
these need return types, and a blank line between them

2022-04-14 21:32 UTC, turt2live commented on src/utils/MediaEventHelper.ts
> -    public readonly thumbnailBlob: LazyValue<Blob>;
these were deliberately exposed and should not be hidden. It's for overall performance of the app.

2022-04-14 21:32 UTC, turt2live commented on src/utils/MediaEventHelper.ts
> +                return { mimetype: content.info.mimetype, data };
`info` might not exist, and `decryptFile` should be responsible for mimetype detection.

2022-04-14 21:32 UTC, turt2live commented on src/utils/MediaEventHelper.ts
> +                    return { mimetype: content.info.thumbnail_info.mimetype, data };
`info` might not exist, and `decryptFile` should be responsible for mimetype detection.

`thumbnail_info` also might not exist

2022-04-14 21:32 UTC, turt2live commented on src/utils/MediaEventHelper.ts
> +    return `data:${blob.mimetype};base64,${await blob.data.text().then(btoa)}`;
This opens us up to XSS attacks, which we do not want.

2022-04-14 21:32 UTC, turt2live commented on src/utils/MediaEventHelper.ts
> -    public readonly thumbnailBlob: LazyValue<Blob>;
(also used by projects downstream of us)

2022-04-14 23:46 UTC, justjanne commented
@turt2live I appreciate the review, after all this is just a first attempt at experimenting with potential solutions that allow us to get SVG previews working.

I'll experiment further with this over the easter weekend, though I don't expect that I'll get a clean fix done soon.

(I actually thought I had left the PR in draft status, but that may have gotten lost at some point)

2022-04-15 00:38 UTC, turt2live commented
ah, apologies for the early review then 😅 

This is a relatively security sensitive area though, particularly the object URL handling.

2022-04-25 14:35 UTC, closed without merging