Implement spacing for the thread list and timeline
matrix-org/matrix-react-sdk pull request #8337
Opened 2022-04-15 17:03 UTC by luixxiul

Closes https://github.com/vector-im/element-web/issues/21759

2022-04-15 19:50 UTC, luixxiul commented
The unread indicator is yet to be styled (I am not sure how to have it displayed) :frowning:

2022-04-17 10:02 UTC, luixxiul commented
The existing visual bug that the top right and bottom border-radius inside the thread panel are not effective should be able to be fixed by merging the style rules with those of the chat panel with a maximized widget (confirmed locally).

![after](https://user-images.githubusercontent.com/3362943/163709642-ec62eb80-4ef5-4f7e-818c-eb9ba7dff06c.png)

Since this is a different issue and requires some refactoring, I guess this should be addressed with another PR, but it can be fixed on this PR if that is preferred.

2022-04-19 09:18 UTC, t3chguy approved these changes
Looks sane code-wise!

2022-04-19 10:50 UTC, luixxiul commented
Thank you for reviewing!

2022-04-20 09:02 UTC, luixxiul commented
The conflict was fixed.

2022-04-20 13:47 UTC, luixxiul commented
https://github.com/matrix-org/matrix-react-sdk/pull/8337/commits/72949b322ec154e10e0f32f843851e628115368a should have not included in this PR. I'm dropping it.

2022-04-26 14:12 UTC, janogarcia requested changes
@luixxiul Thanks for the awesome contribution, Suguru. 👏

Just a few details that would need to be improved to get this merged.

---

**Thread list: Spacing**

I've annotated the spacing values that should be fixed (current value as measured vs expected value in respective callout).

![spacing-thread-list](https://user-images.githubusercontent.com/60790/165318415-9944e011-66f2-4e35-9e46-e3a4dcfe816e.png)

---

**Thread list: Contextual actions hover behavior**

Please notice how the preceding thread gets the hover focus when the user tries to reach the contextual actions buttons in the thread immediately below it.

![hover-stack](https://user-images.githubusercontent.com/60790/165319215-998b3e04-108a-4ff6-b3f9-1d9fafebb342.gif)

---

**Thread list: Unread indicator**

> The unread indicator is yet to be styled (I am not sure how to have it displayed) 😦

You'll need two separate accounts to be able to test this (i.e., replying to your threads with a different account). That said, there's currently a bug that is preventing this from working correctly ([I reported it today](https://github.com/vector-im/element-web/issues/21927)).

2022-04-26 14:25 UTC, janogarcia commented
@luixxiul In case you missed it (I guess GitHub doesn't notify you on edits of review comments) I added a new section in my comment for the **Thread list: Unread indicator**.

2022-04-26 14:41 UTC, janogarcia commented
> @janogarcia Thanks for checking in detail! I'll work on the improvement per your suggestions.

@luixxiul Thank you for your time. 🙏

2022-04-27 06:25 UTC, janogarcia commented
@t3chguy I couldn't test @luixxiul latest changes on Netlify. GitHub seems to be complaining about running workflows for first-time contributors. Can we please approve running them?

2022-04-27 14:49 UTC, janogarcia commented
Thanks, @luixxiul!

Unfortunately, I'm not getting the same output as in your screenshots. It seems that a number of spacing regressions were introduced at some point.

---

**Thread list**

![spacing](https://user-images.githubusercontent.com/60790/165545641-7d718d2b-65b3-479a-9007-805780160846.png)

2022-04-27 17:23 UTC, luixxiul commented
@janogarcia I'm not sure how that happened but it might be related to the conflict due to the latest change. I'll fix the conflict and ping you then..

2022-04-28 06:52 UTC, luixxiul commented
@janogarcia The conflicts were fixed, and the spacing style rules were adjusted. Would you please check again? I've tried my best but it is hard to see 1px difference on my monitor :eyeglasses:

2022-04-28 07:53 UTC, janogarcia commented
@luixxiul Everything's looking fine. Great job! Only if we could update `.mx_ThreadView .mx_EventTile:not([data-layout=bubble])` top padding to be `16px` ? 🙏

2022-04-28 07:56 UTC, janogarcia requested changes
Minimal change request in my previous comment, otherwise looking great. 👍

2022-04-28 09:04 UTC, luixxiul commented
@janogarcia No problem, I'm going to check it very soon (I hope there is not a hacky solution required :grin:  )

2022-04-28 09:15 UTC, luixxiul commented
I found a regression due to a recent commit of this PR, and I'm going to address it as well.

2022-04-28 12:17 UTC, luixxiul commented on res/css/views/rooms/_EventTile.scss
> +            padding-top: $spacing-16;
@janogarcia `.mx_ThreadView .mx_EventTile:not([data-layout=bubble])`'s top padding is set with this line.

2022-04-28 12:30 UTC, luixxiul commented on res/css/views/right_panel/_ThreadPanel.scss
> -                    width: $MessageTimestamp_width;
These are partial revert of https://github.com/matrix-org/matrix-react-sdk/pull/8337/commits/addd6a723f2a49192c26dc4e2397de9157962646. They are not required thanks to the original properties on [_GroupLayout.scss](https://github.com/matrix-org/matrix-react-sdk/blob/472222c195d5d953d673519f7ba8e00cf56fc4ca/res/css/views/rooms/_GroupLayout.scss#L32).

2022-04-28 15:52 UTC, luixxiul commented
@janogarcia thank you very much for taking your time! :smile:

2022-04-29 10:31 UTC, t3chguy commented on src/components/views/rooms/EventTile.tsx
> +        ) {
```suggestion
        } else if (this.context.timelineRenderingType === TimelineRenderingType.ThreadsList ||
            (this.context.timelineRenderingType === TimelineRenderingType.Thread && !this.props.continuation)
        ) {
```

2022-04-29 10:35 UTC, luixxiul commented
Going to fix the conflict

2022-04-29 10:56 UTC, t3chguy approved these changes
:shipit: Thanks for this!!

2022-04-29 11:03 UTC, merged