Apply corrections identified by SonarQube
matrix-org/matrix-react-sdk pull request #8457
Opened 2022-05-01 09:14 UTC by t3chguy

2022-05-01 11:10 UTC, t3chguy commented
Sonar unhappy due to lack of coverage being hooked up

2022-05-02 01:35 UTC, turt2live requested changes
otherwise lgtm - thanks!

2022-05-02 01:35 UTC, turt2live commented on src/RoomInvite.tsx
>      // Valid enough by our standards
the comment structure of this function needs to change too, if we're doing this. The `return true` was deliberate for code clarity, given the comment blocks.

2022-05-03 20:52 UTC, turt2live approved these changes

2022-05-03 21:04 UTC, merged