Add README badges
matrix-org/matrix-react-sdk pull request #8458
Opened 2022-05-01 11:05 UTC by t3chguy

2022-05-02 01:37 UTC, turt2live requested changes
otherwise lgtm

2022-05-02 01:37 UTC, turt2live commented on README.md
> +![npm](https://img.shields.io/npm/v/matrix-react-sdk)
needs link

2022-05-02 08:26 UTC, t3chguy commented on README.md
> +![npm](https://img.shields.io/npm/v/matrix-react-sdk)
```suggestion
[![npm](https://img.shields.io/npm/v/matrix-react-sdk)](https://www.npmjs.com/package/matrix-react-sdk)
```

2022-05-03 20:53 UTC, turt2live approved these changes

2022-05-03 20:54 UTC, merged