Live location sharing: don't group beacon info with room creation summary
matrix-org/matrix-react-sdk pull request #8468
Opened 2022-05-02 14:39 UTC by kerryarchibald

2022-05-02 22:29 UTC, t3chguy reviewed
The code looks to do what the PR says, but there's no explanation anywhere as to *why*

2022-05-03 08:22 UTC, kerryarchibald commented
@t3chguy added some context.

2022-05-03 08:26 UTC, t3chguy requested changes

2022-05-03 08:26 UTC, t3chguy commented on src/components/structures/MessagePanel.tsx
> +        }
The comment on lines L1081-1083 needs updating too

2022-05-03 08:34 UTC, t3chguy approved these changes
Thanks!

2022-05-03 09:04 UTC, merged