Fixes right panel composer look and feel
matrix-org/matrix-react-sdk pull request #8783
Opened 2022-06-08 08:42 UTC by gsouquet

Fixes https://github.com/vector-im/element-web/issues/22459
 
<table>
<tr>
	<td> 🤮 Before
	<td> 💅 After
<tr>
	<td> <img width="478" alt="Screen Shot 2022-06-08 at 09 39 54" src="https://user-images.githubusercontent.com/769871/172572201-e871fb27-e7e8-4f09-b02f-b720ecb96db0.png">
	<td> <img width="354" alt="Screen Shot 2022-06-08 at 09 35 54" src="https://user-images.githubusercontent.com/769871/172572137-a9e1a99a-ff98-488f-90f4-3a2fad9a571f.png">
</table>

I removed the top outline on the reply preview container as the composer is already in a box when used in that container and the border radius used there does not match the border radius of the outer container.

2022-06-08 14:19 UTC, DoM1niC commented
![grafik](https://user-images.githubusercontent.com/1436958/172640037-3a02fca6-c7e5-4f59-a921-3abfaa8a6c85.png)
Emojis in Composer does not look fit

2022-06-08 15:19 UTC, gsouquet commented
@DoM1niC I'm not sure I can reproduce that. I'd recommend you open a ticket describing steps to reproduce

2022-06-08 15:39 UTC, niquewoodhouse requested changes
Nice, I think a couple of more tweaks help the composer fit more into the right panel.

.mx_MessageComposer_row padding: 8px 12px

this makes the composer a bit shorter by default so it fits better into the smaller space, although it does seems to make the action icons jump around a bit in the screenshot below.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1587166/172653242-0904808f-7b15-46ba-8154-0d226ea22422.png">

Content:

I'm not sure if this was implemented but in the Threads designs, the hint was "Reply to thread" not the same as the default composer hint "Send encrypted message..."  - if that was implemented, can it return please?  It gives user more context.

Border-colour: please could we remove the focus colour border change for now, while gathering more feedback?  I think it makes the composer fit more naturally next to it's icons which is more noticeable on the threads

2022-06-09 10:18 UTC, luixxiul commented
> <img alt="image" width="332" src="https://user-images.githubusercontent.com/1587166/172653242-0904808f-7b15-46ba-8154-0d226ea22422.png">

Why not simply using flex align-items: center, removing all of the block margin in pixel values around there, because flexbox model is intended to be used for ensuring the same height for all of the elements inside it?

For example, of my closed PR: [pull/8799/commits/d5b5ef93ed911ca7d7ace521364360798cea52e5](https://github.com/matrix-org/matrix-react-sdk/pull/8799/commits/d5b5ef93ed911ca7d7ace521364360798cea52e5)

2022-06-14 04:00 UTC, turt2live commented
blocked on future of the composer

2022-06-20 05:15 UTC, luixxiul commented
@DoM1niC it was very easy to reproduce the issue, and the issue was logged here: https://github.com/vector-im/element-web/issues/22508

> ![grafik](https://user-images.githubusercontent.com/1436958/172640037-3a02fca6-c7e5-4f59-a921-3abfaa8a6c85.png) Emojis in Composer does not look fit, this issue can fixed too in this PR?

2022-06-27 08:43 UTC, closed without merging