Fix clock line break in voice message player on monospace font
matrix-org/matrix-react-sdk pull request #8815
Opened 2022-06-11 15:26 UTC by luixxiul

This PR applies the same fix as https://github.com/matrix-org/matrix-react-sdk/pull/8320 to the clock on voice message player on the timeline.

|Before|After|
|---------|------|
|![before3](https://user-images.githubusercontent.com/3362943/173194137-a87696d6-320d-4e7d-ac23-11337323f3fb.png)|![after3](https://user-images.githubusercontent.com/3362943/173194108-51a5a28a-c51e-4ddc-961c-22aaf3167ae3.png)|
|![before](https://user-images.githubusercontent.com/3362943/173194117-dec53235-a267-46a0-a7a1-dfbe234512e8.png)|![after](https://user-images.githubusercontent.com/3362943/173194100-47f81fa0-cf38-4e98-bf15-00e7f1585d3d.png)|
|![before1](https://user-images.githubusercontent.com/3362943/173194123-ddc3b050-714b-48f4-a9ac-5614b42ad3d3.png)|![after1](https://user-images.githubusercontent.com/3362943/173194105-0e079636-66ef-4b8f-b546-abfc66e079b2.png)|
|![before2](https://user-images.githubusercontent.com/3362943/173194129-ee9f5fa2-c86e-4a31-9651-ec3b296a5674.png)|![after2](https://user-images.githubusercontent.com/3362943/173194106-564acf26-cc07-4c3b-a054-d9e28c2d6f3e.png)|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

2022-06-15 18:47 UTC, turt2live requested changes
The changes overall are almost certainly sane, however this bit of the app is heavily designed and needs to meet those designs.

Ideally we'd have screenshot tests to prove that nothing has changed here, as there appears to be quite a lot which has changed by accident.

2022-06-15 18:47 UTC, turt2live commented on res/css/views/audio_messages/_PlaybackContainer.scss
> +        display: flex;
Nested flexboxes end up going poorly on Safari/Firefox, and I don't think we need it here.

2022-06-15 18:47 UTC, turt2live commented on res/css/views/audio_messages/_PlaybackContainer.scss
> +    @mixin AudioPlayer;
I feel like we should be using a class rather than a mixin.

2022-06-15 18:47 UTC, turt2live commented on res/css/_common.scss
> +        min-width: $font-42px; // for flexbox
which flexbox?

2022-06-15 18:47 UTC, turt2live commented on res/css/_common.scss
> +    .mx_SeekBar,
should this be tightly scoped?

2022-06-15 18:47 UTC, turt2live commented on res/css/views/audio_messages/_PlaybackContainer.scss
> -            top: -2px; // visually vertically centered
this was moving the seek bar 2px up, which is still needed.

2022-06-15 18:47 UTC, turt2live commented on res/css/views/audio_messages/_PlaybackContainer.scss
> +.mx_MessageComposer_controls {
We shouldn't be targeting the composer here - we need to be targeting the PlaybackContainer classes itself.

2022-06-15 18:47 UTC, turt2live commented on res/css/views/audio_messages/_PlaybackContainer.scss
> -            text-align: right;
This text-align was fixing a layout issue that is introduced by this PR where the clock ends up not matching the designs:
![image](https://user-images.githubusercontent.com/1190097/173901937-28b0501c-0421-477b-bf21-500379336168.png)

(this PR)

There should be no padding or margin on the right side of the clock.

2022-06-15 19:02 UTC, luixxiul commented
The PR was initially created before the latest change was added to the player, and it looks like many of the changes of this PR got obsolete since then.

> this bit of the app is heavily designed and needs to meet those designs.

I am not sure if I follow; where are those designs?

2022-06-15 19:03 UTC, turt2live commented
I don't think the designs are public, unfortunately :( 

We have very strict tolerances on the padding/margins for the voice message components though - I'm going to look into adding screenshot tests for this area.

2022-06-17 15:33 UTC, luixxiul commented
If the design is not publicly available, there is not really something I could do here.. Closing for now.

2022-06-17 15:33 UTC, closed without merging