Improve security room settings tab style rules
matrix-org/matrix-react-sdk pull request #8844
Opened 2022-06-14 16:17 UTC by luixxiul

|Before|After|
|---------|------|
|![before](https://user-images.githubusercontent.com/3362943/173626248-02d92a6f-ff16-4523-ab6a-c7301b02043a.png)|![after](https://user-images.githubusercontent.com/3362943/173626218-8347f38b-0124-41c4-b1f1-97ee49bfdb36.png)|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

2022-06-14 16:19 UTC, luixxiul commented on res/css/views/settings/tabs/room/_SecurityRoomSettingsTab.scss
> -.mx_SecurityRoomSettingsTab_encryptionSection {
This was added with https://github.com/matrix-org/matrix-react-sdk/pull/2523/files#diff-32beddecb1bd760a65b15adab68b83321fff88243061955848e3bca9c4554048R32, and this selector is no longer used.

2022-06-15 06:46 UTC, weeman1337 requested changes
Hi @luixxiul thank you for your contribution.

Can you fix the style lint errors and then re-request review please?

2022-06-15 07:48 UTC, luixxiul commented
@weeman1337 Done. It looks like I have removed the last line break while fixing the conflict.

2022-06-15 07:54 UTC, luixxiul commented
Also the spacing around the link is going to be adjusted with another PR to realize the same layout as Space setting's visibility tab.

2022-07-01 09:14 UTC, weeman1337 commented
@luixxiul can you please update this branch to develop? I will then give it another review on the Netlify deployment.

2022-07-05 14:24 UTC, weeman1337 approved these changes
Tested on the Netlify deployment. Thanks @luixxiul

2022-07-05 14:24 UTC, merged