Apply variables to ensure the spacing is properly applied to 'cancel' button on Space settings general tab
matrix-org/matrix-react-sdk pull request #8846
Opened 2022-06-15 09:35 UTC by luixxiul

|Before|After|
|---------|------|
|![before](https://user-images.githubusercontent.com/3362943/173795402-bfb0ad36-0b05-4e84-826a-2ab7365c8e0c.png)|![after](https://user-images.githubusercontent.com/3362943/173795379-683f8816-4495-48d7-b991-c70922a7496b.png)|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: task

2022-06-15 09:37 UTC, luixxiul commented on res/css/views/dialogs/_SpaceSettingsDialog.scss
> -            margin: 7px 18px;
The style of `Upload` link button next to the avatar is specified with `_SpaceBasicSettings.scss` so removing this line does not change that style.

2022-06-16 16:05 UTC, kerryarchibald requested changes
Both other settings (user and room) line up the cancel button directly to the left of the container:

Room:
<img width="461" alt="Screenshot 2022-06-16 at 18 03 38" src="https://user-images.githubusercontent.com/3055605/174115340-5ed8ddff-6191-4d41-9571-df3de74d7991.png">
Profile:
<img width="484" alt="Screenshot 2022-06-16 at 18 03 21" src="https://user-images.githubusercontent.com/3055605/174115344-c06ead5c-6f5e-476c-b92c-7aa050fb9058.png">

I think a better change would be to align the space settings design with room and user.

2022-06-16 16:08 UTC, luixxiul commented
@kerryarchibald Is it OK to change the current UI? Please note that this PR does not change the current UI.

2023-03-07 05:32 UTC, luixxiul commented
Closing due to no response for a very long time.

2023-03-07 05:32 UTC, closed without merging