Move New Search Experience out of beta
matrix-org/matrix-react-sdk pull request #8859
Opened 2022-06-17 10:09 UTC by justjanne

Type: Enhancement
Related: https://github.com/vector-im/element-web/issues/22553

2022-06-17 10:37 UTC, luixxiul commented
Let's not forget to remove `.mx_BetaCard_betaPill` inside `_SpotlightDialog.scss` as well :-)

2022-06-17 10:39 UTC, luixxiul commented
Let's not forget to remove `.mx_BetaCard_betaPill` inside `_SpotlightDialog.scss` as well :-)

2022-06-17 15:47 UTC, weeman1337 commented
Does it make sense to keep a labs setting? I cannot uncheck it anyway

![image](https://user-images.githubusercontent.com/6216686/174332667-4a267633-1e7d-4181-85fb-a5991440f215.png)

2022-06-17 15:48 UTC, justjanne commented
It shouldn’t be in there anymore, thanks for finding that!

2022-06-17 15:57 UTC, weeman1337 requested changes
Tested on the Netlify Deployment. Seems to be working. :+1:   
Can you check my comment in the code about the unused Styles?

2022-06-17 15:57 UTC, weeman1337 commented on src/components/structures/RoomSearch.tsx
> -            'mx_RoomSearch_hasQuery': this.state.query,
Some of these classes doesn't seem to be used anymore but they are still around in the Sass files. Can you chat that please and eventually remove them?

2022-06-17 16:26 UTC, weeman1337 approved these changes
:+1:

2022-06-17 17:26 UTC, turt2live commented
(there's also docs in element-web's labs.md which might need deleting)

2022-06-28 09:16 UTC, kittykat approved these changes

2022-06-28 09:21 UTC, kittykat commented
> Does it make sense to keep a labs setting? I cannot uncheck it anyway
> 
> ![image](https://user-images.githubusercontent.com/6216686/174332667-4a267633-1e7d-4181-85fb-a5991440f215.png)

I think it would be better removed

2022-06-28 09:23 UTC, niquewoodhouse approved these changes
🚀

2022-06-28 10:02 UTC, merged