Apply inline start padding to selected lines on modern layout only
matrix-org/matrix-react-sdk pull request #9006
Opened 2022-07-07 11:39 UTC by luixxiul

This PR removes inline start padding from selected lines on IRC layout and applies it to ones on modern layout.

|Before|After|
|---------|------|
|![before1](https://user-images.githubusercontent.com/3362943/177764744-188d2c9f-55c2-47c4-9682-4abb0752b850.png)|![after1](https://user-images.githubusercontent.com/3362943/177764698-a98a5dcd-46de-4240-afc1-fa3d9d902b79.png)|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

2022-07-07 12:32 UTC, kerryarchibald commented
The expand/collapse icon button on hidden events is overflowing outside the message highlight in IRC

Develop:
<img width="207" alt="Screenshot 2022-07-07 at 14 29 46" src="https://user-images.githubusercontent.com/3055605/177773660-3fdb9d84-5d32-4ddd-a6c5-3efe97290c05.png">

netlify:
<img width="158" alt="Screenshot 2022-07-07 at 14 29 59" src="https://user-images.githubusercontent.com/3055605/177773679-1eed5487-c906-4228-9b61-1cf62dca1011.png">

2022-07-11 08:22 UTC, kerryarchibald commented
@luixxiul We would really like to start covering some of these sensitive areas with screenshot tests to give us more confidence in changes. 
We use percy along with cypress for screenshot tests, our [cypress docs are here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md), this section especially about [screenshots](https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#percy-visual-testing). 
The [threads tests](https://github.com/matrix-org/matrix-react-sdk/blob/develop/cypress/e2e/5-threads/threads.spec.ts#L81-L92) already create a room and send a message so could be a good jumping off point. 

Would you feel comfortable adding a small test case to cover some of the scenarios here?

2022-07-14 08:48 UTC, SimonBrandner commented on cypress/e2e/14-timeline/timeline.spec.ts
> +            cy.setSettingValue("useOnlyCurrentProfiles", null, SettingLevel.ACCOUNT, false);
I think this is a leftover that doesn't need to be here?

2022-07-14 08:48 UTC, SimonBrandner commented on cypress/e2e/14-timeline/timeline.spec.ts
> +                cy.get(".mx_BasicMessageComposer_input").type(" Edit{enter}");
```suggestion
                cy.get(".mx_BasicMessageComposer_input").type("Edit{enter}");
```

2022-07-14 12:45 UTC, luixxiul commented on cypress/e2e/14-timeline/timeline.spec.ts
> +            cy.get(".mx_RoomView_body .mx_GenericEventListSummary[data-layout=irc] .mx_GenericEventListSummary_summary")
Thanks for the information. This is my very first time to write a test, so any suggestion helps!

2022-07-14 12:49 UTC, luixxiul commented on res/css/views/rooms/_EventTile.scss
> +            &.mx_EventTile_selected .mx_EventTile_line {
This PR intends to add inline start padding (padding-left) only to the modern layout, removing it from IRC layout, so what you suggest is to create another same test for the modern layout in order to make sure that a regression does not happen on that layout? :thinking:

2022-07-14 12:55 UTC, SimonBrandner commented on cypress/e2e/14-timeline/timeline.spec.ts
> +                cy.get(".mx_BasicMessageComposer_input").type(" Edit{enter}");
Ah, probably doesn't really matter

2022-07-14 16:35 UTC, luixxiul commented on res/css/views/rooms/_EventTile.scss
> +            &.mx_EventTile_selected .mx_EventTile_line {
Created another test for modern/group layout.

2022-07-14 17:04 UTC, luixxiul commented
What would be a preferred way of waiting until room configuration is finished? `cy.contains(".mx_RoomView_body .mx_GenericEventListSummary[data-layout=irc] " + ...` seems to fail intermittently.

2022-07-15 03:32 UTC, luixxiul commented
Here is the cropped screenshot of the cypress run on CI.

![Untitled](https://user-images.githubusercontent.com/3362943/179144457-c6fc37d3-e58b-42d4-a4f2-204997044e90.png)

The `Hello` line is not supposed to appear at the top of the room.

2022-07-16 17:51 UTC, luixxiul commented
Creating a test for modern/group layout, I found an inconsistent padding setting of selected info event line. The commit above should fix it.

|Before|After|
|---------|------|
|![before](https://user-images.githubusercontent.com/3362943/179366482-f07058c7-6624-4a1f-84b1-87562e89ff43.png)|![after](https://user-images.githubusercontent.com/3362943/179366418-7fe0638f-73b3-44cf-a740-21bacc199f14.png)|

2022-07-18 12:00 UTC, weeman1337 requested changes

2022-07-23 15:33 UTC, SimonBrandner approved these changes
Looks sane

2022-08-01 06:19 UTC, weeman1337 approved these changes
:+1:

2022-08-01 06:19 UTC, merged