Fix dismissing edit composer when change was undone
matrix-org/matrix-react-sdk pull request #9109
Opened 2022-07-27 10:11 UTC by t3chguy

Fixes https://github.com/vector-im/element-web/issues/22932

2022-07-27 11:04 UTC, weeman1337 commented
Shouldn't we write a test for that to prevent breaking it in the future?

2022-07-27 13:29 UTC, weeman1337 approved these changes
Tested, works :+1:

2022-07-27 18:05 UTC, SimonBrandner requested changes
Yes, as @weeman1337 said, a test here would be very helpful, please

2022-08-02 13:49 UTC, SimonBrandner approved these changes

2022-08-02 13:54 UTC, merged