Refactor login flow types into matrix-js-sdk
matrix-org/matrix-react-sdk pull request #9232
Opened 2022-09-01 19:02 UTC by hughns

The corresponding PR for matrix-js-sdk is https://github.com/matrix-org/matrix-js-sdk/pull/2669 which must be merged at the same time (was originally part of ~~https://github.com/matrix-org/matrix-js-sdk/pull/2633~~)

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

2022-09-07 04:13 UTC, turt2live requested changes
it appears as though a commit is missing - this does not compile.

2022-09-11 20:34 UTC, hughns commented
@turt2live unless you are looking at something different, is the issue that it depends on the js-sdk branch given by https://github.com/matrix-org/matrix-js-sdk/pull/2633?

2022-09-11 21:53 UTC, hughns commented
@turt2live the required changes are now on js-sdk develop branch but don't seem to be pulled in for the test on this PR. What have I done wrong? 🤦‍♂️

2022-09-12 21:41 UTC, turt2live commented
it's probably the lockfile being a huge pain, but let's see if another merge does it.

Initial review was based on the diff being a large shade of red, fwiw - didn't see the js-sdk PR at all and it should have considered it as part of the build.

2022-09-12 21:47 UTC, turt2live commented
oh, the react-sdk PR got reverted.

@hughns what's the status of this?

2022-09-14 12:44 UTC, hughns commented
@turt2live the status is that there is a new smaller PR https://github.com/matrix-org/matrix-js-sdk/pull/2669 which does the remaining change (which is what broke react-sdk earlier in the week).

2022-09-21 21:14 UTC, turt2live approved these changes

2022-09-21 21:14 UTC, turt2live commented on src/Login.ts
> +    IdentityProviderBrand, IIdentityProvider, ISSOFlow, LoginFlow,
```suggestion
    IdentityProviderBrand,
    IIdentityProvider,
    ISSOFlow,
    LoginFlow,
```

2022-09-22 15:24 UTC, merged