remove the grey gradient on images in the timeline
matrix-org/matrix-react-sdk pull request #9241
Opened 2022-09-03 14:50 UTC by ara4n

given we now show timestamps with a nice lozenge overlay,
so the gradient is unnecessary and just screws up the image.

fixes https://github.com/vector-im/element-web/issues/21651

2022-09-03 15:46 UTC, robintown requested changes
The timestamp still isn't contained in an overlay, though?

![image](https://user-images.githubusercontent.com/48614497/188278153-c6b49849-4053-4f23-bcdd-44d7605f6a44.png)

2022-09-03 16:23 UTC, ara4n commented
oh, right. bleurgh. guess the timestamp needs a lozenge much like the image name + size.

2022-09-04 22:03 UTC, ara4n commented
fixed, hopefully. PTAL

2022-09-06 22:12 UTC, amshakal reviewed
An elegant solution. Thanks!

2022-09-07 03:16 UTC, robintown approved these changes
Looks good, though @ara4n note that the mobile apps are still stuck with the gradient. Given that you feel strongly about the gradient we should probably file issues for them as well :)

2022-09-07 08:27 UTC, amshakal approved these changes

2022-09-08 14:54 UTC, merged