Hide the "Message" button in the sidebar if the CreateRooms components should not be shown
matrix-org/matrix-react-sdk pull request #9271
Opened 2022-09-12 15:07 UTC by dhenneke

When using `ComponentVisibilityCustomisations` to hide certain features from the UI, the "Message" link in the people section of a room is still visible and leads to an error, if the room creation is [disabled in the homeserver](https://github.com/matrix-org/synapse-user-restrictions).

Before:
<table>
<td>
<img width="168" alt="image" src="https://user-images.githubusercontent.com/720821/189686213-e6078ba0-567a-4119-8f41-3b45d7cb788e.png">
</td>
<td>
<img width="595" alt="image" src="https://user-images.githubusercontent.com/720821/189686279-bb5c36e1-11e6-408f-b14e-74957c0ddac9.png">
</td>
</tr>
</table>

After:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/720821/189686325-c982718e-6c2a-4f84-ac0d-73255cd05716.png">

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2022-09-12 17:06 UTC, SimonBrandner requested changes
LGTM codewise

Would it be possible to write tests for this change?

2022-09-12 17:34 UTC, dhenneke commented
I could try to write a unit test tomorrow.

2022-09-12 17:37 UTC, SimonBrandner commented
> I could try to write a unit test tomorrow.

Absolutely awesome! Take the time you need and in case you need anything, be sure to visit https://matrix.to/#/#element-dev:matrix.org

2022-09-13 09:20 UTC, SimonBrandner reviewed
Could you please fix the strict TS warnings?

LGTM otherwise

2022-09-13 09:20 UTC, SimonBrandner commented on test/components/views/right_panel/UserInfo-test.tsx
> +            (shouldShowComponent as jest.Mock).mockImplementation((component) => {
You should be able to use `mocked()` here

2022-09-13 09:23 UTC, dhenneke commented
I added additional test for the component. I never worked with `enzyme` before and was surprised that it was used in this file while other components seem to use `@testing-library/react` which I'm more familiar with. But I hope it's correct in this way.

2022-09-13 09:28 UTC, t3chguy commented
@dhenneke enzyme is considered deprecated here, please use RTL instead. Enzyme is blocking our React 18 upgrade

2024-01-25 11:21 UTC, dbkr approved these changes

2024-01-25 11:22 UTC, dbkr commented
Hey - apologies for this dropping off our radar. This looks fine now though. I'm assuming we don't have write permission to the fork: could you pull in the changes from develop so all the tests run?

2024-01-25 18:08 UTC, dhenneke commented
Neither do I... Maybe @maheichyk could help out?

2024-01-26 09:35 UTC, maheichyk commented
> Hey - apologies for this dropping off our radar. This looks fine now though. I'm assuming we don't have write permission to the fork: could you pull in the changes from develop so all the tests run?

@dbkr branch is updated. Could you please have a look and merge is fine?

2024-01-26 15:16 UTC, merged