Add room topic to room info
matrix-org/matrix-react-sdk pull request #9334
Opened 2022-09-30 07:16 UTC by Arnei

For very long room titles and/or windows with small width/resolution, the room topic in the room header becomes hidden.
![Bildschirmfoto vom 2022-09-30 09-12-08](https://user-images.githubusercontent.com/14070005/193212509-a56f84a0-1dc0-4e1d-a90e-baa32767f5bd.png)

To make it easily accessible, I suggest adding the room topic to the room information.
![Bildschirmfoto vom 2022-09-30 09-12-29](https://user-images.githubusercontent.com/14070005/193212533-be5d9024-1e69-4d0a-b8a0-d4726bf2c07c.png)

Signed-off-by: Arne Wilken arnepokemon@yahoo.de

2022-09-30 07:38 UTC, gsouquet requested changes
Thank you for raising this pull request!

I'm not entirely convinced that having this information in the `RoomSummaryCard` is the way to go. I would try to fiddle with the CSS to make sure that the topic is always a tiny bit visible in the room header.
That way we can show the topic modal when clicking it that displays the expanded room title and expanded room topic. 
But I will let a designer give their review

Regarding the code you wrote, I believe we should make `InfoTopic` generic as it's too tied to the context where it's used at the moment. And for this pull request to be accepted you'll need to have some test coverage of your changes

2022-09-30 10:09 UTC, Arnei commented
Hi gsouquet, thanks for your very fast feedback. 

I am also not 100% sure adding the room topic to `RoomSummaryCard` is the best way of doing this. I merely assumed it would be more intuitive for users to click on the "room info" button when they want to know the topic of the room.

2022-09-30 10:10 UTC, Arnei commented on src/components/views/right_panel/RoomSummaryCard.tsx
> +        WebkitLineClamp: 'none',
Thanks for pointing that out, should be fixed now.

2022-09-30 10:11 UTC, Arnei commented on src/components/views/right_panel/RoomSummaryCard.tsx
> +    const lineHeight = 16;                      // Basically font-size
Wasn't aware you could do that, TIL.

2022-11-07 16:43 UTC, florianduros commented
One solution also is to display the topic name in the topic tooltip. Currently we are displaying `Room options`, maybe it'll more relevant to display here the full topic name.

2024-02-22 07:31 UTC, MidhunSureshR commented
Hello :wave:, thanks for the PR but unfortunately this is no longer relevant with the new room header which can be enabled in the labs settings

2024-02-22 07:31 UTC, closed without merging