Fix missing avatar for show current profiles
matrix-org/matrix-react-sdk pull request #9563
Opened 2022-11-09 13:20 UTC by gsouquet

Fixes https://github.com/vector-im/element-web/issues/23733

## Checklist

* [ ] Tests written for new code (and old code if feasible)
  - Did not manage to reproduce this bug in a test environment
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

2022-11-09 14:37 UTC, t3chguy requested changes
Given this is a fix for a regression, can we get a test which asserts that it doesn't break again please?

2022-11-09 15:10 UTC, gsouquet commented
@t3chguy I have not been able to reproduce those steps in testing just yet. I can try on for longer but haven't had any luck yet :/

2022-11-09 15:16 UTC, t3chguy commented
I can reproduce after enabling

![image](https://user-images.githubusercontent.com/2403652/200868425-0d198f02-ad7a-4ebe-b029-e7a129c47b92.png)

and refreshing

![image](https://user-images.githubusercontent.com/2403652/200868461-ed9f9170-905f-4e8c-8bec-973cc847d155.png)

The test doesn't have to be a cypress test, just a minimal test case which would have caught this edge is plenty

2022-11-10 09:37 UTC, gsouquet commented on src/components/views/avatars/MemberAvatar.tsx
> +    const [title, setTitle] = useState<string>();
Unfortunately using `useMemo` does not fix the bug here. I'll stick with `useEffect`

2022-11-10 13:51 UTC, robintown commented
@gsouquet I think I've managed to fix this in a simpler way: https://github.com/matrix-org/matrix-react-sdk/commit/51932493b24421dc2b7573ac3287a549319d1879

The issue seems to be that pills are rendered in isolated component trees, and so don't have a room in their RoomContext to work with. Falling back to the prop member in this case restores the previous behavior.

2022-11-11 12:47 UTC, t3chguy approved these changes
Looks sane to me!

2022-11-11 16:02 UTC, merged